bcgov/bcparks.ca

- src/cms/data/pages.json
- src/staging/package.json
- src/staging/src/pages/alerts.js
- src/staging/src/pages/index.js
- src/staging/src/styles/home.scss
- BC-521
- added button to homepage 'See all advisories'
- linked buttons to /alerts page, wildfire and flooding buttons autofilter results upon navigation.
- [ x] New feature (non-breaking change which adds functionality)
Requires dropping and restoring db. 
Filtering occurs client side and uses existing `allStrapiPublicAdvisory` call. In the future, filtering can be achieved with API calls.
- [ x] No
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] I have made corresponding changes to the documentation
- [x ] New and existing unit tests pass …
> BC-521 filtering homepage advisories

- src/staging/src/styles/global.scss
May break a few things but we can't have everything with
`display: block;`.
> NOBUG: remove global style overrides

- src/staging/src/components/header.js
- src/staging/src/pages/explore.js
Fixed Header build error
Header component wasn't rendering anything if `mode` isn't set to `internal`.  This causes Gatsby build to fail.  For this PR I removed the `mode` check if block for now since it's not really used.  We can add it back later if desired.
> NOBUG: But also a bug: Fixed Header build error

- src/cms/data/functions/loadPar.js
- src/cms/data/park-details.json
Gatsby assumes all areas have names and fails to build if they don't.
Caused by changes in https://github.com/bcgov/bcparks.ca/pull/237
> NOBUG: fix missing protected area names

- src/staging/package.json
Fixes `warn Plugin gatsby-plugin-sass is not compatible with your gatsby version 3.14.6 - It requires gatsby@^2.0.0`
> NOBUG: update sass plugin

- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-test.yaml
- .github/workflows/on-tag-push.yaml
- infrastructure/cronjobs/image-pruner-cronjob.dc.yaml
- tools/imagetag-prune/Dockerfile
- tools/imagetag-prune/README.md
- tools/imagetag-prune/imagePruner.js
- tools/imagetag-prune/index.js
- tools/imagetag-prune/package.json
- Added a simple utility to help prune older container image tags
- Added a new Github Action to retag images from git hash to the release tag (e.g., from `strapi:f60463d`  to `strapi:v1.0.16`) when a new release tag is created
> NOBUG: Add image pruner utility

- .github/workflows/build-public.yaml
BRS-394
https://bcparksdigital.atlassian.net/browse/BRS-394
This change adds a webhook to the build-public github actions workflow to alert the rocketchat channel `osprey-alerts` if the build workflow fails.
The webhook must be accompanied by a JSON payload containing `workflow` and `repo` fields, for context.
Use the `curl` below to test the bot for incoming webhooks - otherwise, the bot should only show alerts when the build workflow fails.
`curl -X POST -H 'Content-Type: application/json' --data '{"workflow":"Test workflow","repo":"testUser/testRepo"}' https://chat.developer.gov.bc.ca/hooks/aPYwd4PeHJh5Wnf7u/MmZPC2AZQoFKuSsGwzmxLtMwX3CmHZYLHYPqLnxAdhZsFLJX`
> BRS-394 add rocketchat alerts for build workflow failures

- .github/workflows/build-dev.yaml
- infrastructure/helm/bcparks/templates/cms/cms-deployment.yaml
- infrastructure/helm/bcparks/templates/redis/redis-configmap.yaml
- infrastructure/helm/bcparks/templates/redis/redis-deployment.yaml
- infrastructure/helm/bcparks/templates/redis/redis-service.yaml
- infrastructure/helm/bcparks/templates/secrets/redis-secret.yaml
- infrastructure/helm/bcparks/values.yaml
- src/cms/config/middleware.js
- src/cms/package.json
BRS-380
https://bcparksdigital.atlassian.net/browse/BRS-380
- Added strapi-caching-middleware
- Added Redis OpenShift resources
- strapi-caching-middleware is disabled by default.  It can be enabled with `STRAPI_CACHE_ENABLED=true` for in memory caching.  
- To enable Redis integration, set `STRAPI_CACHE_TYPE=redis`, and `REDIS_HOST`, `REDIS_PORT`, `REDIS_PASSWORD` if not using default values
> BRS-380 Add strapi caching middleware and redis

- src/cms/api/park-photo/models/park-photo.settings.json
We should be using imageUrl & thumbnailUrl anyways. If any file fields fields are present, `gatsby-source-strapi` always loads all the images in them (!!), which has been a cause of build failures and slows things down.
> NOBUG: remove strapi image fields on parkphoto

- src/staging/Caddyfile
Fixed the incorrect caching config for Gatsby Caddy.  `/public/page-data/*` was incorrect, the correct path should be `/page-data/*`
> NOBUG: Fix page-data cache for Gatsby Caddy

- infrastructure/helm/bcparks/values.yaml
BRS-442
https://bcparksdigital.atlassian.net/browse/BRS-442
Bump Patroni image tag version to the upgraded Patroni version (Patroni 2.0.1 - Postgresql 12.4)
> BRS-442 Bump Patroni image tag

- .github/workflows/build-public.yaml
- infrastructure/helm/bcparks/templates/public/public-deployment.yaml
- src/staging/src/components/footer.js
BRS-411 
https://bcparksdigital.atlassian.net/browse/BRS-411 
I'm using the `react-helmet` package to load the Snowplow script into the `Footer` component.  It will attempt to load it from `/_scripts/snowplow.js` path.  The snowplow.js file is mounted into the container at runtime from OpenShift ConfigMap.  This allows us to use different script per environment and we are able to update them on the fly without rebuilding.
I have created the ConfigMap in dev, test and prod.  So this PR will just work once deployed.  Note that the `snowplow.js` value in prod is currently a placeholder and won't do anything when mounted.
> BRS-411 Add ability to mount snowplow from configmap

- src/staging/src/components/megaMenu/desktopMenu.js
- src/staging/src/components/megaMenu/mobileMenu.js
BRS-446
https://bcparksdigital.atlassian.net/browse/BRS-446
Fixes issue flagged by QA. Makes the book a campsite links from the header in the same tab to match the behaviour of the buttons on the park details page.
> BRS-446: open camping site in same tab

- src/staging/src/pages/explore.js
- src/staging/src/pages/index.js
BRS-393
https://bcparksdigital.atlassian.net/browse/BRS-393
Old Behaviour: Page tab title (helmet) doesn't update when navigating back home from 404 page.
Reason: Home page does not have `SEO` or `Helmet` component to update tab wording on navigation.
Solution: `SEO` component added to home page. A quick comb of other major pages was done to see if this problem existed anywhere else. Updated tab titles now read as follows:
Home page: `Home | BC Parks`
Explore page `Explore | BC Parks`
> BRS-393 react helmet shows correct page title on home & explore pages

- src/staging/src/components/park/advisoryDetails.js
- src/staging/src/components/park/campingDetails.js
- src/staging/src/components/park/parkActivity.js
- src/staging/src/components/park/parkFacility.js
- src/staging/src/styles/cmsSnippets/parkInfoPage.scss
BRS-395
https://bcparksdigital.atlassian.net/browse/BRS-395
This change is part of a series of updates to replace MUI Accordion components with bootstrap equivalents.
This particular change updates the accordion components on the park information pages.
NOTE: `b24b177` is to fix accordion collapsing jitters and to add keys to mapped React child components. The original commit, `663a8ee`, contained the major accordion changes, but this history was lost in a poor rebase. All changes now contained in `b24b177`.
> BRS-395-3 replacing accordion components in park information page with bootstrap

- src/cms/api/protected-area/services/protected-area.js
- src/staging/gatsby-node.js
- src/staging/src/components/advisories/advisoryCard.js
- src/staging/src/pages/alerts.js
- src/staging/src/pages/parks.js
BRS-410
https://bcparksdigital.atlassian.net/browse/BRS-410
Consumes the `isDisplayed` flag added to strapi in #308.  This is part 2 of 2 replacing https://github.com/bcgov/bcparks.ca/pull/301 - the plan is to deploy that change, set the data, then merge and deploy this one.
Once it's in place, we can run the following query to show all protected areas via API endpoint:
```
UPDATE protected_areas SET published_at = NOW() WHERE published_at IS NULL;
```
> BRS-410 (part 2): check park display flag on alerts, park pages, and search

- src/cms/api/protected-area/services/protected-area.js
- src/staging/gatsby-config.js
- src/staging/src/components/park/parkAccessStatus.js
- src/staging/src/pages/explore.js
BRS-339
https://bcparksdigital.atlassian.net/browse/BRS-339
This ticket changes the accessStatus component on the parks exploration page to match the actual accessStatus of the advisories associated with the park, and not infer accessStatus indirectly.
When searching for parks, the API already returns the titles of the advisories within the park object, so the API has been slightly modified to return the whole advisory, including the accessStatus.
Unfortunately, the structure of an advisory within a park object as mentioned above differs from that of an advisory directly returned via the API,. The React Component `ParkAccessStatus` which displays the access status on the parks details pages was modified to be able to accept the differing structures, so that this component could be also …
> BRS-339 Match explore page park status with highest precedence advisory

- src/cms/api/park-photo/models/park-photo.settings.json
BRS-335
https://bcparksdigital.atlassian.net/browse/BRS-335
``sortOrder`` is to be used to order photos in the display (lowest first)
``isFeatured`` is a boolean value to indicate the main photo forvsearch results, etc. Ideally there should be one featured photo per park, but that is not easily enforcable in Strapi, so I think we can fall back to sortOrder if there are multiple values.
> BRS-335 (part 1): add sort order and featured fields

- src/staging/src/components/search/searchFilter.js
- src/staging/src/pages/explore.js
BRS-408
https://bcparksdigital.atlassian.net/browse/BRS-408
This change resets the park pagination to page 1 after filters are updated. The `searchFilter` component is used in mobile view which has different handler functions for when a filter is checked/unchecked. This change passes the `setCurrentPage` state function from the explore page to the `searchFilter` component so the currentPage state can be tracked there.
> BRS-408 pagination reset after filter update on mobile view

- src/cms/api/protected-area/services/protected-area.js
- src/staging/gatsby-node.js
- src/staging/src/templates/park.js
BRS-335
https://bcparksdigital.atlassian.net/browse/BRS-335
Uses the new feature photo/sort order fields to rank photos in search results and photo galleries.
> BRS-335 (part 2): use photo sort order

- src/staging/src/components/advisories/advisoryFilter.js
- src/staging/src/pages/alerts.js
BRS-471
https://bcparksdigital.atlassian.net/browse/BRS-471
This change removes a conditional statement wrapping the advisory filter that would hide the filter if there were no advisories matching the search criteria.
> BRS-471 advisory filters still visible when no advisories present

- src/staging/src/pages/intro.js
- src/staging/src/styles/betaLanding.scss
BRS-457
https://bcparksdigital.atlassian.net/browse/BRS-457
Some scss styles directly applied to html elements at the root level in `betaLanding.scss` were leaking into other parts of the site. This change wraps the contents of `betaLanding.scss` in a class that can be applied only to the intro page, to properly segregate the styles.
A quick scan of the other scss files did not immediately reveal similar cases where styles may be cascading incorrectly, but if future styling issues are uncovered, they can be specifically addressed quite easily on a case-by-case basis in future tickets.
> BRS-457 review of incorrectly cascading intro page styles

- src/staging/gatsby-node.js
BRS-415
https://bcparksdigital.atlassian.net/browse/BRS-415
In `gatsby-node.js`, the boolean `hasDayUsePass` was being imported as a string, causing some parks to incorrectly display a "Get Day Use Pass" button.
> BRS-415 BUG: hasDayUsePass should be imported as boolean

- src/cms/api/protected-area/custom/protected-area-status.js
BRS-377
https://bcparksdigital.atlassian.net/browse/BRS-377
When you pass an orcs filter to park-access-statuses, the Strapi value in park-access-status-cache is overwritten.  You have to wait 5 minutes for the cron job to fix it. 
1. go to https://test-cms.bcparks.ca/park-access-statuses-cache (note the size of the response)
2. go to https://test-cms.bcparks.ca/park-access-statuses?orcs=255
3. go to https://test-cms.bcparks.ca/park-access-statuses-cache (the response is much, much smaller)
Note that now the cache only contains data for orcs 255.  It will correct itself within 5 minutes the next time the cron job runs. You can also fix it by going to https://test-cms.bcparks.ca/park-access-statuses with no querystring.
> BWT-377: Passing an ?orcs= filter to /park-access-statuses overwrites park-access-status-cache

- src/cms/package.json
CM-69
https://bcparksdigital.atlassian.net/browse/CM-69
Tiny fix to add dependency back in at the root of the project. This should fix the build error.
> CM-69: added ckeditor5-react back in at project root

- src/staging/src/styles/betaLanding.scss
- src/staging/src/styles/global.scss
CM-113, CM-132
https://bcparksdigital.atlassian.net/browse/CM-113
https://bcparksdigital.atlassian.net/browse/CM-132
Minor CSS fix to make headers white inside of the homepage feature box.
Minor CSS fix to ensure tables render full-width and that header rows are light grey for contrast.
> CM-113: header color override, CM-132 tables full width

- tools/syncdb/README.md
- tools/syncdb/export-db.ps1
- tools/syncdb/import-db.ps1
CM-60
https://bcparksdigital.atlassian.net/browse/CM-60
1. Updated syncdb scripts to use 'cp' instead of 'rsync'.  This fixes the error `cannot use rsync: rsync not available in container`
2. Added instructions for importing into Docker Desktop
> CM-60: Updated syncdb scripts to use 'cp' instead of 'rsync'

- src/cms/data/functions/loadOtherData.js
- src/cms/data/functions/loadPar.js
BRS-147
https://bcparksdigital.atlassian.net/browse/BRS-147
1. Updated the import script so parks keep the "isDisplayed" status that is already set in Strapi.
2. Don't create any new parks from park-details.json that don't already exist (they are not needed and they break Gatsby builds)
3. Refactored code to undo a hack when updating ProtectedAreas. I discovered the right way to call the API.
> CM-147: Edits to import scripts

- src/staging/gatsby-node.js
- src/staging/src/templates/staticContent1.js
- src/staging/src/templates/staticLanding1.js
- src/staging/src/utils/helpers.js
CM-145
https://bcparksdigital.atlassian.net/browse/CM-145
- Added `Title` in Gatsby to display on FE
- Updated the logic in `staticContent1.js`. `title` does not exist so replaced it with `Title`
- Move the `renderBreadcrumbs` function to `helpers.js` to be used in other templates
- Added breadcrumbs and title in `staticLanding.js` if the page does not have HTMLArea
- This ^ temp code for the edge case can be changed after https://bcparksdigital.atlassian.net/browse/CM-143
> CM-145: added Title on Gatsby

- src/staging/src/styles/global.scss
CM-136
https://bcparksdigital.atlassian.net/browse/CM-136
Minor CSS bugfix to ensure that `th` tags in rows get styling applied to them.
> CM-136: minor fix for table header styles to extend to row headers

- src/staging/src/components/park/mapLocation.js
- src/staging/src/templates/park.js
CM-9
https://bcparksdigital.atlassian.net/browse/CM-9
- Hide the map if a park doesn't have a latitude and longitude
- Hide the entire location section if the park doesn't have either a latitude and longitude or a location note
> CM-9: Parks without lat/long

- src/staging/src/components/park/mapLocation.js
CM-209
https://bcparksdigital.atlassian.net/browse/CM-209
When you click on a park layer in the embedded ArcGIS map, it reveals a pop with an URL to the parks page. 
This is both incorrect, as it's a legacy url, and not useful since the user is on the page. I've disable click events as none are needed. Click and drag continues to work.
> CM-209: disabled click event on arcgis maps

- src/cms/api/park-operation/models/park-operation.settings.json
- src/cms/api/site/models/site.settings.json
- src/staging/gatsby-config.js
- src/staging/gatsby-node.js
- src/staging/src/templates/park.js
- src/staging/src/templates/site.js
- src/staging/src/utils/constants.js
CM-162
https://bcparksdigital.atlassian.net/browse/CM-162
- Added new fields and a new relation: `slug`, `hasDayUsePass`, `description`, `locationNotes`, and `parkOperation`
- Added a new path for site page: `/protectedArea.slug/site.siteName` eg. `/parks/mount-robson/berg-lake-trail`
- Added a site template based on the design mockup.
- Those new fields  `slug`, `hasDayUsePass`, `description`, and `locationNotes` are available on Strapi, but won't be available on Gatsby (front-end) at this moment to avoid the build error.
> CM-162: Add site template

- src/cms/data/park-facility-xref.json
- tools/legacy-scrape/visitor-services-patches/ScrapePatch -- ContentScrape line 961.vb
CM-248
https://bcparksdigital.atlassian.net/browse/CM-248
- Fixed a bug in the visitor services MS-Access db that was breaking the export of Winter Camping
- Re-scraped ParkActivityXref data
* there are some other changes in the JSON file to do updates to how UTF-8 characters are handled (via CM-231)
> CM-248: Fix missing Winter Camping section

- src/staging/gatsby-node.js
None
None
Fixed a 'missing trailing slash' issue where park pages were being treated as files instead of folders in the browser, so links to child pages were not working
> NOBUG: Fixed relative links issue on park pages

- src/cms/api/site/models/site.settings.json
- src/staging/gatsby-node.js
- src/staging/src/templates/site.js
CM-246
https://bcparksdigital.atlassian.net/browse/CM-246
- Made `siteName` and `protectedArea` relation as required since they’re necessary for the URL path
- TODO: `slug` also should be a required field, after the data import
- Changed URL path using `slug`, if there's no `slug`, `siteName` will be used
- Applied new fields `locationNotes`, `description`, and `hasDayUsePass` to `site.js`
> CM-246: Apply new Strapi fields to Gatsby site template

- src/cms/api/protected-area/services/protected-area.js
CM-200 (bugfix)
https://bcparksdigital.atlassian.net/browse/CM-200
The status "Open to public access" was showing on parks where the access should have been "Open".  This was caused by removing too many fields from the query when making it faster.
> NOBUG: Wrong access status shown on search result page

- src/cms/package.json
Hotfix to solve build errors when using the custom build of CKEditor.
@babel/plugin-transform-block-scoping version 7.20.7 appears to have introduced a bug that causes the build to fail. Updated package.json to require ^7.20.11.
> hotfix: forced later version of dependency to fix bug with ckeditor init

- src/cms/api/page/models/page.settings.json
- src/cms/api/park-sub-page/models/park-sub-page.settings.json
- src/cms/api/protected-area/models/protected-area.settings.json
- src/cms/api/site/models/site.settings.json
- src/staging/gatsby-node.js
CM-314
https://bcparksdigital.atlassian.net/browse/CM-314
- Change site slug fallback logic
- If there's only `siteName`: `siteName` will be used as a path
- If there's both `slug` and `siteName`: `slug` will be used as a path
- Note: Since `siteName` is a required field, there's always `siteName`
- Added regex to all `slug` fields to prevent editors to add any whitespaces
-  `^[a-z0-9]+(?:-[a-z0-9]+)*$` accepts all special characters but whitespace 
- `^[a-z0-9]+(?:-[a-z0-9]+)*$|^$` accepts all special characters but whitespace, or an empty string because some of the slug fields are not required
> CM-314: Change site slug fallback

- src/staging/src/pages/find-a-park.js
CM-329
https://bcparksdigital.atlassian.net/browse/CM-329
Hide inactive activity and facility filters from the find a park page. These are being filtered out by the search query, and thus always resulting in no matching parks.
> CM-329: Fix for some filters not working on Find a Park page

- src/staging/gatsby-node.js
- src/staging/package.json
- src/staging/src/pages/active-advisories.js
CM-326
https://bcparksdigital.atlassian.net/browse/CM-326
- Removed warnings when running `yarn start`/`yarn build`
- Deleted `Helmet` for the warning `warning  'Helmet' is defined but never used  no-unused-vars`
- Added webpack config for the warning `Conflicting order. Following module has been added:`
- Changed the sass version for the warning `Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.`
1. Run `yarn` at `staging`
2. Run `yarn build`
3. Check if these warnings are not displayed
> CM-326: Fix build issues

- src/staging/src/pages/active-advisories.js
CM-279
https://bcparksdigital.atlassian.net/browse/CM-279
- There are 455 `PublicAdvisories` on [TEST](https://test-cms.bcparks.ca/admin/plugins/content-manager/collectionType/application::public-advisory.public-advisory?page=1&pageSize=10&_sort=title:ASC)
- [Previous endpoint](https://test-cms.bcparks.ca/public-advisories/count?protectedAreas.published_at_null=false&protectedAreas.isDisplayed=true) `/public-advisories/count?protectedAreas.published_at_null=false&protectedAreas.isDisplayed=true` has 550 `PublicAdvisories`
- Changed endpoint to `/public-advisories/count` to get proper data
- ^ [New endpoint](https://test-cms.bcparks.ca/public-advisories/count?) has 455 `PublicAdvisories`
- Somehow filtered endpoint count doesn't work properly 🥲
- However, filtered endpoint and additional …
> CM-279: Change api endpoint for counter

- src/staging/gatsby-node.js
CM-312
https://bcparksdigital.atlassian.net/browse/CM-312
Added the regex we're using for Parks to add trailing slashes to any pages we're creating using `createPage()` in `gatsby-config.js`
> CM-312: trailing slashes for pages, park sub pages and sites

- src/staging/src/components/park/campingDetails.js
- src/staging/src/components/park/parkActivity.js
- src/staging/src/components/park/parkFacility.js
- src/staging/src/styles/cmsSnippets/parkInfoPage.scss
- src/staging/src/templates/park.js
- src/staging/src/templates/site.js
- src/staging/src/utils/helpers.js
CM-372
https://bcparksdigital.atlassian.net/browse/CM-372
- Moved `isNullOrWhiteSpace` to `helpers.js`
- Hid arrow icon if `description` is null, empty, or having only whitespace
- Hid accordion if `description` is null, empty, or having only whitespace
- Added conditional class/styling to indicate the accordion is not clickable
- Applied these changes to the activities, facilities, and camping section
> CM-372: Not display empty camping section

- src/staging/src/templates/site.js
CM-263
https://bcparksdigital.atlassian.net/browse/CM-263
On site pages, we only want to show advisories that are either 
a. At the park level or higher (they don't specify any specific sites)
b. That specify this specific site.
If an advisory specifies a specific site, but it is not the site for the current page, then it should be excluded.
> CM-263: Exclude advisories for other sites at the same park

- src/staging/Caddyfile
CM-360
https://bcparksdigital.atlassian.net/browse/CM-360
NOTE: These changes won't actually do anything until the DNS is cutover. But we can use www.bcparks.ca now with a hosts file to do testing to ensure that the same pattern will work for beta.bcparks.ca later.  
code changes:
1. Added caddy directive to redirect all requests to www.bcparks.ca to bcparks.ca.  
2. Also added a commented-out version for beta.bcparks.ca, but the comment can't be removed until DNS cutover.
Two new routes were also added to OpenShift PROD. To test them you need to add these entries to your /etc/host file...
- 142.34.194.118  bcparks.ca
- 142.34.194.118  www.bcparks.ca
The new routes are called vanity-bcparks.ca and vanity-www.  Wildcard SSL certificates have been added for both routes.  
- …
> CM-360: caddy redirect for www.bcparks.ca

- src/staging/Caddyfile
CM-360
https://bcparksdigital.atlassian.net/browse/CM-360
Fixed caddy redirect.  I believe the previous format was trying to bind something to port 80 and getting an error:
```
run: loading initial config: loading new config: http app module: start: tcp: listening on :80: listen tcp :80: bind: permission denied
```
This format has been tested using Docker Desktop and it does do the redirect properly, however I'm still not sure why Port 80 was being used.
> CM-360: Fix Caddyfile

- .github/workflows/build-public.yaml
- src/kong/README.md
CM-272
https://bcparksdigital.atlassian.net/browse/CM-272
This includes updates to the KONG docs as well as an update to the GitHub action to change the build API from Strapi to the BC Gov endpoint.
> Cm 272 update kong docs

- src/cms/config/functions/cron.js
CM-398
https://bcparksdigital.atlassian.net/browse/CM-398
Reduced the cron frequency to once per hour, at 2 minutes past the hour.  
BCGW replication is hourly at 10 minutes past the hour.
Strapi cron jobs use "node-schedule". Full documentation for node-schedule is here:
https://www.npmjs.com/package/node-schedule
The change is based on the example _"Execute a cron job when the minute is 42 (e.g. 19:42, 20:42, etc.)."_
> CM-398: Reduce the cron frequency to once per hour

- src/staging/src/pages/find-a-park.js
- src/staging/src/styles/search.scss
CM-394
https://bcparksdigital.atlassian.net/browse/CM-394
- Added a [map link](https://governmentofbc.maps.arcgis.com/apps/webappviewer/index.html?id=077ef73a1eae4ca88f2bafbb831215af&query=British_Columbia_Parks_Ecological_Reserves_and_Protected_Areas_8747,ORCS_PRIMARY,0000) to the park search page based on [Figma](https://www.figma.com/file/CoXGPkDLN7HKkt0kPuqWhv/BC-Parks-Website?node-id=4296%3A41877)
- Changed HTML structure by adding the map link
- Added styling for the map link
> CM-394: Add map link to park search page

- src/staging/src/components/megaMenu.js
CM-97
https://bcparksdigital.atlassian.net/browse/CM-97
- The error was because the element with `role="menu"` did not contain any child element with `role="menuitem"`
- Added `role="menuitem"` to the menu item elements
- Added `role="presentation"` to the  `<li>` elements 
- Ref: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menu_role#example_1_navigation_menu
> CM-97: Fix aria menu error

- src/staging/src/pages/find-a-park.js
CM-115
https://bcparksdigital.atlassian.net/browse/CM-115
- The error was because there's no `label` for the `input` field
- Added `aria-label` to `TextField` prop
> CM-115: Add aria-label to input field

- src/staging/package.json
None
None
- @molund found a warning `warn Plugin gatsby-plugin-robots-txt is not compatible with your gatsby version 3.15.0 - It requires gatsby@^5.0.0`
- To fix this, downgraded it to version `1.7.1`
- Tested it by deleting `node_modules` and running `yarn build`
> NOBUG: Downgrade gatsby-plugin-robots-txt

- src/staging/gatsby-node.js
None
Removed unnecessary build warnings "Unable to parse oldUrl" for parks where this field is blank.
> NOBUG: Fix build warning parsing oldUrl

- src/staging/src/components/advisories/advisoryCard.js
- src/staging/src/pages/active-advisories.js
CM-493
https://bcparksdigital.atlassian.net/browse/CM-493
Fixed an issue where the first parkname was being repeated multiple times on advisories associated with multiple parks.
This issue stems from changes made in BWT-426.  The broken code can now be reverted because protectedAreaName was imported as UTF-8 during the data migration.  
Note: a tech-debt ticket has been created to revert the BWT-426 changes in other places.
https://bcparksdigital.atlassian.net/browse/CM-495
> CM-493: Fix an issue with repeated parkname tags on advisories

- src/cms/config/functions/slugValidator.js
CM-544
https://bcparksdigital.atlassian.net/browse/CM-544
When a brand-new page is published for the first time, the hooks are called, but the context is missing so the slug is treated as blank or undefined.  This PR updates the slug validators so they will no longer simulaneously act as required field validators.
> CM-544: slug validators should pass for blank/null/undefined slug

- src/staging/package.json
- src/staging/src/components/park/parkOverview.js
CM-529
https://bcparksdigital.atlassian.net/browse/CM-529
- Added tabindex to skip <a> element by tabbing when the section is not expanded
> CM-529: Skip park overview by tabbing

- src/staging/src/components/megaMenu.js
- src/staging/src/styles/megaMenu/megaMenu.scss
CM-459
https://bcparksdigital.atlassian.net/browse/CM-459
Update the megamenu based on [the new design](https://www.figma.com/file/CoXGPkDLN7HKkt0kPuqWhv/BC-Parks-Website?node-id=4740%3A45874&t=5bcAEdnAtciqhCd0-1)
Added up/down arrow icon
Hover - no action, but display underline as a hover state
Click - open the menu, and change the background colour to white as a click state
Fixed accessibility warnings
```
193:48  warning  Non-interactive elements should not be assigned interactive roles
jsx-a11y/no-noninteractive-element-to-interactive-role
224:21  warning  Non-interactive elements should not be assigned interactive roles
jsx-a11y/no-noninteractive-element-to-interactive-role
287:17  warning  Non-interactive elements should not be assigned interactive roles …
```
> CM-459: Update megamenu

- src/cms/src/api/park-activity/controllers/park-activity.js
- src/cms/src/api/park-facility/controllers/park-facility.js
- src/cms/src/api/public-advisory-audit/content-types/public-advisory-audit/lifecycles.js
- src/cms/src/api/public-advisory-audit/controllers/public-advisory-audit.js
- src/cms/src/api/public-advisory/controllers/public-advisory.js
CM-596
https://bcparksdigital.atlassian.net/browse/CM-596
Fixed an issue where relations weren't being saved to public advisories in the lifecycle hook on public advisory audits.
> CM-596: Fix for advisory relations not saving

- src/cms/src/api/protected-area/controllers/protected-area.js
- src/cms/src/api/protected-area/custom/protected-area-status.js
- src/cms/src/api/protected-area/services/protected-area-status.js
- src/cms/src/api/public-advisory/content-types/public-advisory/schema.json
- src/cms/src/api/public-advisory/controllers/public-advisory.js
- src/cms/src/api/public-advisory/services/public-advisory.js
- src/gatsby/src/pages/active-advisories.js
- src/gatsby/src/pages/find-a-park.js
CM-621
https://bcparksdigital.atlassian.net/browse/CM-621
Fixes an issue where some advisories were not appearing on the public advisories search page.  This was happening because the querystring parameter was called `_q` and it was conflicting with an undocumented parameter in the Strapi 4 API (which I believe is actually a remnant from Strapi 3).  `_q` was renamed to `queryText`.
> CM-621: Fix for missing advisories

- src/cms/src/api/park-activity/controllers/park-activity.js
- src/cms/src/api/park-facility/controllers/park-facility.js
- src/cms/src/api/public-advisory-audit/controllers/public-advisory-audit.js
CM-621
https://bcparksdigital.atlassian.net/browse/CM-621
Fixed the implantation of rest-cache invalidation
1. call `clearByUid()` asynchronously
2. also invalidate the public-advisories when creating a new public-advisory-audit
> CM-621: Fixed cache invalidation

- src/gatsby/gatsby-config.js
None
None
1. Hard-code the sitemap location to the prod sitemap on all environments
2. Remove incorrect subdirectory `/sitemap/` from sitemap path in robots.txt file
> NOBUG: Fix incorrect sitemap location in robots.txt

- src/gatsby/package.json
None
None
- Fix Gatsby build error
```
SplitChunksPlugin
Cache group "shared" conflicts with existing chunk.
Both have the same name "380d42e81165839365c4703ae67985f785a96bdc" and existing chunk is not a parent of the selected modules.
Use a different name for the cache group or make sure that the existing chunk is a parent (e. g. via dependOn).
HINT: You can omit "name" to automatically create a name.
BREAKING CHANGE: webpack < 5 used to allow to use an entrypoint as splitChunk. This is no longer allowed when the entrypoint is not a parent of the selected modules.
Remove this entrypoint and add modules to cache group's 'test' instead. If you need modules to be evaluated on startup, add them to the existing entrypoints (make them arrays). See migration guide of more info.
not finished …
```
> NOBUG: Fix gatsby build error

- src/cms/src/api/public-advisory-audit/content-types/public-advisory-audit/lifecycles.js
CM-596
https://bcparksdigital.atlassian.net/browse/CM-596
Renamed published_at to publishedAt in the public-advisory-audit lifecycle hook.  This fixes an error that was causing the `beforeUpdate` hook to short-circuit because it was checking the truthiness of `published_at` which no longer existed.  I believe it was only working previously because of a bug in the staff portal that was fixed in [CM-609](https://github.com/bcgov/bcparks.ca/pull/646/commits/5385d72a7c3bcdbda0de9b5c51e21d4b04ef82db).
> CM-596: Fix error in public advisory lifecycle hook

- src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
CM-626
https://bcparksdigital.atlassian.net/browse/CM-626
Fixed a bug where all advisories were displaying _"plus 4 more regions(s)"_ in the Associated Parks(s) column.
> CM-626: Fix advisory region display bug

- src/gatsby/src/pages/active-advisories.js
None
None
- Fix the warning below
```
warn 
/Users/ayumi/Downloads/projects/bcparks/strapi4/src/gatsby/src/pages/active-advisories.js
45:10  warning  'advisoryCount' is assigned a value
but never used  no-unused-vars
```
> NOBUG: Fix warning

- .github/workflows/publish-gatsby.yaml
- src/gatsby/gatsby-config.js
None
None
In the first request where it uses the API token, gatsby-source-strapi calls a non-pubic content manager route that isn't available to Kong
> NOBUG: Use alternate URL endpoint for environments with Kong

- infrastructure/helm/bcparks/templates/cms/cms-deployment.yaml
- infrastructure/helm/bcparks/values-test.yaml
- infrastructure/helm/bcparks/values.yaml
- src/cms/config/plugins.js
CM-657
https://bcparksdigital.atlassian.net/browse/CM-657
I discovered we had an Openshift environment variable called STRAPI_CACHE_TTL that was not being used.  It was set to 300000 milliseconds on OpenShift (5 minutes).  We had our maxAge set to 3600000 (1 hour).  I have adjusted the Strapi config to use this variable.  
I also removed another variable that wasn’t being used by Strapi4 from OpenShift (STRAPI_CACHE_TIMEOUT was set to 10000). Strapi3 was using a different plugin called strapi-middleware-cache and the cacheTimeout setting is not applicable in the new Strapi4 plugin (strapi-plugin-rest-cache / strapi-provider-rest-cache-redis)
> CM-657: Reduce Redis cache time from 1 hour to 5 minutes

- src/gatsby/src/templates/park.js
- src/gatsby/src/templates/site.js
CM-658
https://bcparksdigital.atlassian.net/browse/CM-658
This is a shot-in-the-dark attempt to fix an issue where Gatsby is serving cached public advisories after they are removed.  
We noticed while debugging the issue that the issue that the `finally` in this code was running before the `then`.  
```
useEffect(() => {
setIsLoadingAdvisories(true)
loadAdvisories(apiBaseUrl, park.orcs)
.then(response => {
if (response.status === 200) {
setAdvisories(response.data.data)
setAdvisoryLoadError(false)
} else {
setAdvisories([])
setAdvisoryLoadError(true)
}
})
.finally(() => {
setIsLoadingAdvisories(false)
})
}, [apiBaseUrl, park.orcs])
```
This could be caused by an issue with promises, and turned out that `loadAdvisories` was marked as `async` but it did not contain an `await` keyword. …
> CM-658: Fix Gatsby caching issue

- src/cms/src/api/park-activity/controllers/park-activity.js
- src/cms/src/api/park-facility/controllers/park-facility.js
- src/cms/src/api/public-advisory-audit/controllers/public-advisory-audit.js
CM-657
https://bcparksdigital.atlassian.net/browse/CM-657
Changed the implementation of cache clearing hooks.  There is no documentation for `clearByUid`, but after reading the source code, I believe our implementation was not working.  
see: https://github.com/strapi-community/strapi-plugin-rest-cache/blob/main/packages/strapi-plugin-rest-cache/server/utils/config/getRouteRegExp.js
We were not passing in a value for `params` , so this code would have been triggered....
```
if (!params) {
return [];
}
```
Passing in an empty object will return false, and furthermore the code above says `// wildcard: clear all routes` so I set wildcard to true.
> CM-657: Change implementation of cache clearing hooks

- src/cms/src/api/public-advisory-audit/content-types/public-advisory-audit/lifecycles.js
CM-659
https://bcparksdigital.atlassian.net/browse/CM-659
Fixed a duplicate key error when re-publishing an inactive public advisory.
> CM-659: Fix error re-publishing an inactive advisory

- src/cms/config/plugins.js
CM-657
https://bcparksdigital.atlassian.net/browse/CM-657
Temporarily disabling caching for public advisories until we can determine the right configuration.
> CM-657: Disable caching for public advisories

- src/cms/config/plugins.js
- src/cms/src/api/public-advisory-audit/controllers/public-advisory-audit.js
- src/cms/src/api/public-advisory/content-types/public-advisory/lifecycles.js
- src/gatsby/src/templates/park.js
- src/gatsby/src/templates/site.js
CM-658
https://bcparksdigital.atlassian.net/browse/CM-658
1. Hooks on the publicAdvisoryAudit controller were being used to trigger the cache to be cleared for publicAdvisory. These hooks were moved to the publicAdvisory model and implemented for all crud operations. _(The previous implementation was later determined to be working, but the new implementation eliminates a possible race condition)_
2. Set hitpass to false in the rest-cache plugin configuration because the default setting led to confusion and made it much harder to debug from a web browser.
3. Modify Axios calls to remove the redundant trailing slash from public-advisories because this was causing cache invalidation to fail.
4. Re-enable caching for publicAdvisory
See comments in the Jira ticket for further details.
> CM-658: Fix issues invalidating the publicAdvisory rest cache

- src/cms/src/api/fire-ban-prohibition/controllers/fire-ban-prohibition.js
- src/cms/src/api/fire-ban-prohibition/routes/custom.js
- src/cms/src/api/fire-ban-prohibition/services/fire-ban-prohibition.js
CM-555
https://bcparksdigital.atlassian.net/browse/CM-555
This change adds a new REST endpoint that will be called by a cron script to propagate campfire bans to ProtectedAreas based on FireBanProhibitions.
The new endpoint can be tested from Postman using a bearer token (API Token) that is generated from the Strapi admin interface.  The token type should be "custom" or "full access". Custom tokens must be granted access to the propagate endpoint. 
**Postman Settings**
request method: POST
test url:  [server url]/api/fire-ban-prohibitions/propagate
Authorization Type: Bearer Token
Token:  [the token you generated]
**Testing Notes**
- Add firebans manually through the Strapi admin interface to test
- Only firebans with the word 'campfire' (case insensitve) in the descriptions will be …
> CM-555: Propagate campfire bans to ProtectedAreas based on FireBanProhibitions

- src/cms/src/api/protected-area/content-types/protected-area/lifecycles.js
CM-664
https://bcparksdigital.atlassian.net/browse/CM-664
Two of the lifecycle hooks on protectedAreas were still using Strapi3 code. This was resulting in an error that was causing changes made via Strapi admin to be rolled back.
> CM-664: Convert protectedArea lifecyle hooks to Strapi4 syntax

- src/cms/src/api/public-advisory-audit/content-types/public-advisory-audit/lifecycles.js
- src/cms/src/api/public-advisory-audit/controllers/public-advisory-audit.js
CM-666
https://bcparksdigital.atlassian.net/browse/CM-666
On some records, the updatedBy and createdBy fields were causing errors saving public advisories.  These fields are not actually used to track anything for data saved from the staff portal so they are not needed.  The staff portal uses Keycloak users and the audit data is stored in separate fields.
> CM-666: updatedBy and createdBy cause errors saving public advisories

- src/cms/src/api/public-advisory-audit/content-types/public-advisory-audit/lifecycles.js
- src/cms/src/api/public-advisory-audit/controllers/public-advisory-audit.js
(cherry picked from #698)
CM-666
https://bcparksdigital.atlassian.net/browse/CM-666
On some records, the updatedBy and createdBy fields were causing errors saving public advisories. These fields are not actually used to track anything for data saved from the staff portal, so they are not needed. The staff portal uses Keycloak users and the audit data is stored in separate fields.
> CM-666: Hotfix for errors saving public advisories

- src/gatsby/src/utils/usePreRenderVideo.js
None
None
- Fix a warning below:
```
warn /Users/ayumi/Downloads/projects/bcparks/strapi4/src/gatsby/src/utils/usePreRenderVideo.js
56:6 warning React Hook useEffect has a missing dependency: 'slugify'.
Either include it or remove the dependency array react-hooks/exhaustive-deps
```
> NOBUG: Fix useEffect warning

- src/gatsby/src/styles/footer.scss
- src/gatsby/src/styles/megaMenu/megaMenu.scss
None
None
- Foley found out that the BC parks logos in the header and the footer are rendered weirdly on Safari. 
Access to https://alpha-dev.bcparks.ca 
- It was because of the Gatsby static image change in this ticket.
https://bcparksdigital.atlassian.net/browse/CM-454
- Add fix to keep image size both on Safari/Chrome
> NOBUG: Fix broken static image on safari

- src/admin/package.json
CM-663
https://bcparksdigital.atlassian.net/browse/CM-663
Fixed peer dependency error, which only happened with `npm install` and not with `yarn`.
> CM-663: Fixed build

- .github/workflows/build-dev.yaml
CM-663
https://bcparksdigital.atlassian.net/browse/CM-663
Temporary build fix to get around node-sass/node-gyp dependency on Python 2
> CM-663: Revert docker container to Node.js v14

- src/cms/src/api/protected-area/custom/protected-area-status.js
CM-654
https://bcparksdigital.atlassian.net/browse/CM-654
- Add eventType to parkAccessStatus API
- On PROD, eventType is null: [https://cms.bcparks.ca/api/park-access-statuses/?populate=*&filters[orcs][$eq]=75](https://cms.bcparks.ca/api/park-access-statuses/?populate=%2A&filters%5Borcs%5D%5B$eq%5D=75)
- On local, eventType should be "wildfire": [http://localhost:1337/api/park-access-statuses/?populate=*&filters[orcs][$eq]=75](http://localhost:1337/api/park-access-statuses/?populate=%2A&filters%5Borcs%5D%5B$eq%5D=75)
> CM-654: Add eventType to parkAccessStatus api

- src/cms/package.json
NONE
NONE
Added back the gatsby-preview plugin because removing it leaves behind some settings in the Strapi admin panel and causes errors.  Further investigation is needed before removing this plugin
> NOBUG: Added back strapi/plugin-gatsby-preview

- src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
- src/admin/src/components/page/advisory/Advisory.js
- src/admin/src/validators/AdvisoryValidator.js
- src/cms/database/migrations/2023.05.23T00.00.00.listing-rank-not-null.js
- src/cms/src/api/public-advisory-audit/content-types/public-advisory-audit/schema.json
- src/cms/src/api/public-advisory/content-types/public-advisory/schema.json
- src/cms/src/api/public-advisory/controllers/public-advisory.js
- src/cms/src/api/public-advisory/routes/custom.js
- src/gatsby/src/templates/park.js
- src/gatsby/src/templates/site.js
- src/gatsby/src/utils/advisoryHelper.js
CM-653
The numeric public-advisory field ‘listingRank’ is used to override the default sort order of advisories on a park page.  Occasionally, an advisory (or advisories) needs to be pinned to the top of the list. A higher number is equivalent to a higher priority on the page.
This was a bit more complicated than expected because there is a bug in the way Strapi sorts nulls on Postgres databases.  As a work-around, I had to ensure that the listingRank is set to zero and is never null.  
https://github.com/strapi/strapi/issues/12593
As part of this change, `loadAdvisories` was also refactored and optimized with the following goals:
1. Reduce code duplication between sites and parks
2. Optimize the JSON payload for public advisories on park …
> CM-653: Sort advisories by listing rank

- src/admin/package-lock.json
- src/admin/package.json
None
None
Bump react-scripts to 5.0.1 to fix critical dependabot alerts.
Note: this causes some `Failed to parse source map...` warnings when you run `npm run build` but it doesn't seem to break anything
> NOBUG: Bump react-scripts to 5.0.1 to fix critical dependabot alerts

- src/cms/config/middlewares.js
CM-289
https://bcparksdigital.atlassian.net/browse/CM-289
- Fix this warning below when editors enter the YouTube URL in the RTE field
```
Refused to execute inline script because it violates the following Content Security Policy directive:
"script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256FDyPg8CqqIpPAfGVKx1YeKduyLs0ghNYWII21wL+7HM='),
or a nonce ('nonce-...') is required to enable inline execution.
```
> CM-289: Fix youtube url in RTE error

- src/admin/src/components/page/advisory/Advisory.js
None (discovered while testing CM-663)
None
Fixes a bug where the staff portal create/edit advisory form gets an error and goes to the error page if there are any sites with no protectedArea defined.  This issue was discovered while testing CM-663 and caused by testing done for CM-99.
> NOBUG: Fix staff portal create/edit screen crash

- src/gatsby/src/utils/advisoryHelper.js
CM-653
Change to sort order for public advisories to always have listingRank first. As per client UAT feedback
> CM-653: Sort by listingRank first

- src/gatsby/src/components/park/advisoryDetails.js
- src/gatsby/src/utils/advisoryHelper.js
CM-653
Removed redundant double sorting of public advisories.  I decided to keep the client side sorting (instead of the server-side sorting) because there are issues with null sorting in Strapi, and work-arounds are easier on client-side than on server-side.  
https://github.com/strapi/strapi/issues/12593
> CM-653: Remove double-sorting of public advisories

- src/cms/src/api/management-document-type/content-types/management-document-type/schema.json
- src/cms/src/api/management-document-type/controllers/management-document-type.js
- src/cms/src/api/management-document-type/routes/management-document-type.js
- src/cms/src/api/management-document-type/services/management-document-type.js
- src/cms/src/api/management-document/content-types/management-document/schema.json
- src/cms/src/api/management-document/controllers/management-document.js
- src/cms/src/api/management-document/routes/management-document.js
- src/cms/src/api/management-document/services/management-document.js
- src/cms/src/api/protected-area/content-types/protected-area/schema.json
- src/cms/src/api/site/content-types/site/schema.json
- src/gatsby/gatsby-config.js
- src/gatsby/gatsby-node.js
- src/gatsby/src/pages/about/park-management-plans/approved.js
- src/gatsby/src/styles/listPage.scss
- CM-437
- CM-636
- https://bcparksdigital.atlassian.net/browse/CM-437
- https://bcparksdigital.atlassian.net/browse/CM-636
- Add the approved management plans page at `/about/park-management-plans/approved`
- Add new collections `managementDocument` and `managementDocumentType`
- Could not query `managementDocument.documentType`
- `managementDocument.documentType` is null on at `http://localhost:8000/___graphql` even there's data on Strapi
> CM-437: Add approved management plans page

- .gitignore
- infrastructure/helm/bcparks/templates/cms/cms-deployment.yaml
- infrastructure/helm/bcparks/values.yaml
- src/cms/config/plugins.js
- src/kong/public-prod.yaml
- src/kong/public-test.yaml
CM-669
https://bcparksdigital.atlassian.net/browse/CM-669
Enable the GraphQL playground and introspection for all environments.  
- A new environment variable was also added to OpenShift that allows this setting to be disabled for individual environments.  
- The GraphQL endpoint was also added to Kong for the TEST and PROD environments
> CM-669: Enable GraphQL playground and introspection

- src/gatsby/gatsby-node.js
- src/gatsby/src/components/pageContent/pageContent.js
- src/gatsby/src/components/pageContent/pageSection.js
CM-723
https://bcparksdigital.atlassian.net/browse/CM-723
Fixes a bug from the Strapi 4 / Gatsby 4 update that caused broken anchor links.  
NOTE: This hotfix PR is different from https://github.com/bcgov/bcparks.ca/pull/743 because it does not rely on https://github.com/bcgov/bcparks.ca/pull/720.
> CM-723: Bugfix for page section ID's changed from int to guid

- infrastructure/helm/bcparks/templates/cms/cms-hpa.yaml
- infrastructure/helm/bcparks/templates/public/public-hpa.yaml
- infrastructure/helm/bcparks/values-prod.yaml
- infrastructure/helm/bcparks/values.yaml
None
None
The site went down for a couple of minutes, and upon further inspection the public containers had been crashing.  
I double the memory, CPU, and HPA maxReplicas limit for these containers.  
This change is already applied to OpenShift PROD.
> NOBUG: Increase resource levels for 'public' deployments

- src/gatsby/src/styles/parks.scss
CM-726
https://bcparksdigital.atlassian.net/browse/CM-726
Fixed button text colour so it doesn't inherit from `.parks-container a`
> CM-726: Fix button text color in park page accordions

- src/cms/src/api/protected-area/custom/protected-area-status.js
CM-668
https://bcparksdigital.atlassian.net/browse/CM-668
Added 4 new custom filters to park-access-status
1. eventType
2. eventType_ne
3. eventType_contains (case-insensitive)
4. accessStatus_contains (case-insensitive)
Also, some other refactoring and optimizations are included:
1. Refactored the query to allow additional filters against protected-areas to be combined with custom filters.
2. Reduced the number of fields returned for parkActivities and parkFacilities to make the endpoint return significantly less data. 
3. Custom filters are no longer mutually exclusive and can be combined
> CM-668: Add 4 new custom filters to park-access-status

- src/cms/src/api/protected-area/services/protected-area.js
- src/gatsby/src/components/park/parkAccessStatus.js
CM-730
https://bcparksdigital.atlassian.net/browse/CM-730
Bugfix for incorrect access statuses in park search results.  A json attribute `access_status_id` was missing from the SQL query, and the naming standard also changed when we did the Strapi 4 update (it previously would have been called `accessStatus` not `access_status_id`).
> CM-730: Bugfix for incorrect access statuses in park search results

- src/cms/src/api/protected-area/custom/protected-area-status.js
CM-739
https://bcparksdigital.atlassian.net/browse/CM-739
Removed legacy code from the park-access-status view that looked up firebans by fire-centre. It now uses the `protectedArea.hasCampfireBan` value instead (which is populated by a cron job)
> CM-739: Fire bans in fire-zones not don't show in park-access-status

- infrastructure/helm/bcparks/templates/secrets/cms-secret.yaml
- src/cms/config/cron-tasks.js
- src/cms/src/extensions/users-permissions/strategies/keycloak-users-permissions.js
CM-592
https://bcparksdigital.atlassian.net/browse/CM-592
Simplified logic to reduce local dev setup steps
This PR also 
- removes some openshift secrets that were only used during the Strapi v3 seed step
- includes a minor change to cron job logging
> NOBUG: Use username instead of email for keycloak auth

- src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
- src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.css
- src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
- src/admin/src/components/shared/tooltip/LightTooltip.js
- src/admin/src/utils/AdvisoryDataUtil.js
- src/admin/src/utils/CmsDataUtil.js
- src/cms/src/api/park-name/services/park-name.js
CM-588
https://bcparksdigital.atlassian.net/browse/CM-588
Added a "show archived" checkbox to the advisory dashboard.  By default, any unpublished advisories that have not been modified for more than 30 days will now be hidden.  
Additional changes were also made to populate fewer fields in Strapi REST requests.
> CM-588: Add toggle for showing archived advisories

- src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
- src/admin/src/utils/AdvisoryDataUtil.js
CM-588
https://bcparksdigital.atlassian.net/browse/CM-588
- Instead of returning up to 2000 records, return advisories up to 18 months old. This is easier to communicate in the tooltip, and it is still well under the API limit.
- Use sessionStorage instead of localStorage to save state of the checkbox. This ensures that it keeps reverting to the shorter list and doesn't get stuck on the longer list.
> CM-588: UX updates to "Show archived" filter

- src/kong/public-prod.yaml
- src/kong/public-test.yaml
CM-559
Added the proxy-cache plugin to Kong with a 15-second expiry.
> CM-559: Add the proxy-cache plugin to Kong

- src/gatsby/src/templates/park.js
None
Added a `fields` list to the query, so it only returns fields that are used by the Gatsby application code.
This query gets run every time a park page is loaded, so it's best to make it as fast as possible in terms of IO, network traffic and overall load on Strapi.
> NOBUG: Optimized the query on park pages for firebans

- src/cms/src/api/access-status/content-types/access-status/schema.json
CM-652
Added a groupLabel field to the access-status collection, so it can be released to prod before CM-652 is implemented and pre-populated with data or populated with a migration during the next release.
> CM-652: Add a groupLabel field to Access-Status

- infrastructure/helm/bcparks/templates/cms/cms-hpa.yaml
- infrastructure/helm/bcparks/templates/public/public-hpa.yaml
- infrastructure/helm/bcparks/values-prod.yaml
- infrastructure/helm/bcparks/values.yaml
None
Adjusting memory limits and horizontal pod autoscaler settings to try to fix the issue where pods were never scaling back down after scaling up.
The approach is based on a comment in this Stack overflow post: https://stackoverflow.com/a/58571471/2616170
_"An issue might be that you're using the memory utilization as a metric, which is not a good autoscaling metric."_
I have increased the memory thresholds and also added CPU as a second metric.  
The memory `request` level for Patroni was also increased, because it was noted that the "Lead" pod was continually running at a level above the `request` setting
> NOBUG: Adjust HPA thresholds

- src/cms/src/api/protected-area/services/protected-area.js
None
Fixed a React warning discovered while testing the Gatsby 5 update (`id` was being used as a key, and it was undefined)
> NOBUG: Fixed missing key warning on find-a-park page

- src/gatsby/src/styles/parks.scss
- src/gatsby/src/styles/staticContent1.scss
- src/gatsby/src/templates/parkSubPage.js
- src/gatsby/src/templates/staticContent1.js
CM-701
CM-702
Changed parks page header photos to be less tall, smoothed it out responsively. Still not consistent with non-park pages.
Added breadcrumbs to mobile view for non-parks pages. Tried to smooth out spacing a bit, but still very different than park pages.
> CM-701: Reduced header image height on park pages

- src/gatsby/src/components/scrollToTop.js
CM-522
- Remove the hover state (change of opacity) on tablet and mobile since it requires users to double-tap
> CM-522: Remove hover state on mobile

- src/cms/src/api/public-advisory/services/public-advisory.js
- src/gatsby/src/archived/intro.js
- src/gatsby/src/components/advisories/advisoryFilter.js
- src/gatsby/src/pages/active-advisories.js
CM-802
The query on the active advisories page has been slower since an advisory was added which impacts 1023 separated protected areas.  This change will make two updates to the query to make it faster
- Search in protectedAreaName instead of parkNames
- Use $eq instead of $containsi for eventType filters
Note: As a result of the first change, fewer results will be returned for park name searches, This is not ideal, but this is a hotfix to deal with a performance issue. The back-end for this search feature will likely be replaced with Elasticsearch in the near future.
> CM-802: Optimize the query for the active advisories page

- src/cms/src/api/public-advisory/controllers/public-advisory.js
CM-801
Allow sites without a slug in the site list on /public-advisories/items (the slugified sitename is used as a fallback in the code)
> CM-801: Don't hide sites with no slug from public-advisories/items

- src/cms/src/api/public-advisory/services/public-advisory.js
- src/gatsby/src/pages/active-advisories.js
CM-803
1. Fixed a bug caused by the hotfix in #838.  Searching for "Wildfire" or "Flood" should return event types that start with these words, not just exact matches.  
2. Tuned the query to return a much smaller result set.  Previously the REST call was returning many unused fields which resulted in a 1.3MB payload for the request: https://bcparks.api.gov.bc.ca/api/public-advisories?populate=*&queryText&_eventType=Wildfire%20risk&limit=10&start=0
> CM-803: Advisory search to use $startsWith: eventType & remove populate=*

- infrastructure/helm/bcparks/templates/patroni/patroni-statefulset.yaml
- infrastructure/helm/bcparks/values-alpha-test.yaml
- infrastructure/helm/bcparks/values-prod.yaml
- infrastructure/helm/bcparks/values-test.yaml
- infrastructure/helm/bcparks/values.yaml
None
Updated helm settings to address issues with Strapi and Patroni
1. Increased request memory, minReplicas and memoryUtilizationThreshold for Strapi to to make strapi shut down extra pods faster, but always keep at least 3 running.
2. Increased memory and cpu for patroni
3. Adjusted health checks for patroni so it will restart itself less often
4. Increased rest cache ttl from 5 minutes to 30 minutes
NOTE: these changes are already on prod
> NOBUG: Update helm config to tune Patroni and Strapi

- src/cms/config/plugins.js
None
Temporary change on alpha-dev to see if the amountLimit change made with the graphQL playground ticket was the cause of slower queries.
> NOBUG: Change the Strapi GraphQL amountLimit to 2500 for Rob

- src/gatsby/src/components/park/parkAccessStatus.js
CM-652
- Update access status to group label on the park page
- The status in the park page header and the status in the dates of operation has been changed to group label
> CM-652: Update access status to group label on park page

- src/gatsby/src/components/park/parkOverview.js
CM-823
- Changed `isLong` definition as greater than 260 px
> CM-823: Changed isLong definition as greater than 260 px

- src/gatsby/gatsby-config.js
CM-828
Changed the pageSize for protectedAreas in the `gatsby-source-strapi` settings from 250 (the default) to 100, and removed the ignored setting of 1000 that was in the wrong place.  This will hopefully fix the issue with periodic 504 gateway timeout errors when running the Publish Gatsby GitHub action.
> CM-828: Change pageSize for Gatsby protectedAreas from 250 to 100

- src/cms/config/plugins.js
None
Temporarily increase GraphQL amountLimit to 2500 to fix issue with dates.bcparks.ca that was introduced by https://github.com/bcgov/bcparks.ca/pull/717. This will be reverted when https://github.com/bcgov/bcparks.ca/pull/854 is deployed to PROD.
> NOBUG: Temporarily increase GraphQL amountLimit to 2500

- src/gatsby/src/components/park/parkOverview.js
CM-823
- Variable `isLong` should be true if it's greater than 259 because `classes.collapsed` `maxHeight` is 260 px
> CM-823: Change isLong to 259 from 260

- src/gatsby/src/components/search/mainSearch.js
CM-849
Tabbing over "Search by activity" on Home page redirects the user to the Find a park page
> CM-849: Remove onKeyDown from homepage Search By Activity link

- src/gatsby/src/styles/staticContent1.scss
CM-841
Reduce the breadcrumb padding on small screens to match content, 
The issue was only happening on screens smaller than 415px because the left and right padding was being reduced on the content below at the 415px breakpoint.  I added some extra CSS to also reduce the padding on the breadcrumbs at sizes below 415px.
> CM-841: Reduce breadcrumb padding on small screens to match content

- src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
CM-852
- Show "Limited services" instead of "No services" in the winter text for parks that are open year round
- Remove the word "gate" from marine parks (because they have beaches, not gates)
> CM-852: Special text for year-round parks and marine parks

- src/cms/src/api/search/controllers/search.js
- src/cms/src/api/search/routes/search.js
- src/elastic/index.js
- src/elastic/package.json
- src/elastic/scripts/indexParks.js
- src/elastic/server.js
- src/elastic/transformers/park.js
- src/elastic/utils/taskQueue.js
CM-123
- Made indexing faster by batching photo requests
- Split the cron job into a separate server.js file to better follow node standards
- Use exec to write timestamps instead of fs.write to prevent async file locking
> CM-851: Made indexing faster by batching photo requests

- infrastructure/helm/bcparks/values-alpha-test.yaml
- infrastructure/helm/bcparks/values-prod.yaml
- infrastructure/helm/bcparks/values-test.yaml
- infrastructure/helm/bcparks/values.yaml
CM-828
- Increased CPU limits for CMS pods from 500m to 750m for all environments to undo a change that may have caused Gatsby builds to start failing.
- Refactored and tuned other settings 
- Removed resource limits from DEV and TEST environments so they are only defined in values.yaml. Now they can be updated in one place
- Removed minReplicas settings from CMS and Public on the TEST environment because they were the same as the defaults in values.yaml
- Decreased the memory limit on dev and test environments from 2Gi to 1250Mi because these should not be higher than PROD
- Decreased CMS CPU requests on DEV and TEST environments from 125m to 75m because these environments sit idle most of the time and the OCIO is asking teams to use lower CPU requests on dev and test.
- Decreased CMS …
> CM-828: Helm updates

- src/gatsby/src/pages/find-a-park.js
CM-869
Added missing backcountry camping icon which was missing from search result cards.  
NOTE: Further work is needed to update the card layout. Seven icons don't fit properly on medium-sized screens. See the ticket for design.
> CM-869: Add missing backcountry camping icon

- src/cms/src/api/protected-area/custom/protected-area-search.js
- src/cms/src/api/protected-area/services/search.js
CM-871
Added region filters. 
Syntax is as follows:
`http://localhost:1337/api/protected-areas/search?queryText=golden&regions[]=1&regions[]=2`
(1 and 2 are the **regionNumber** field from the Regions collection)
Note that region filters are "OR" filters, not "AND" filters like the other filters.  Region aggregations also behave as "OR" and are nested differently than other aggregations.
> CM-871: Back-end for region filters

- src/cms/src/api/protected-area/custom/protected-area-search.js
- src/cms/src/api/protected-area/services/search.js
CM-871
Updated aggregations to use activityNumber, facilityNumber, regionNumber instead of activityCode, facilityCode, regionName.  This will make the front-end easier to implement because no extra data is neeeded to do lookups.
Also included zeros in the buckets and removed unused aggregations (hasCamping, typeCode, marineProtectedArea)
> CM-871: Use numbers for aggregations instead of codes and names

- src/cms/src/api/protected-area/services/search.js
- src/elasticmanager/transformers/park.js
CM-857
When queryText is 1 or 2 characters, autocomplete should only return parks that start with queryText. If it's 3 or more characters, then queryText can be at the start of any word in the parknames or protectedAreaName. **NOTE: data must be reindexed for this to work properly.**
Also limited the result set to the following fields:  
- "orcs",
- "protectedAreaName",
- "hasCampfireBan",
- "slug",
- "parkFacilities",
- "parkActivities",
- "parkLocations",
- "advisories"
Also enabled fuzziness for park search
> CM-857: autosuggest should only return parks that start with queryText

- src/cms/src/api/protected-area/services/search.js
- src/cms/src/api/search-indexing/controllers/search-indexing.js
- src/elasticmanager/scripts/createParkIndex.js
- src/elasticmanager/transformers/park.js
None
Added latitude and longitude to Elasticsearch for demo purposes.  `node index.js rebuild` is required.  
Example of "parks near me" query
```
GET /bcparks-protected-areas-local/_search
{
"_source": [
"parkLocations.managementArea",
"protectedAreaName"
],
"query": {
"geo_distance": {
"distance": "50km",
"locationGeo": "49.129,-122.724"
}
},
"sort": [
{
"_geo_distance": {
"locationGeo": "49.129,-122.724",
"order": "asc",
"unit": "km",
"mode": "min",
"distance_type": "arc",
"ignore_unmapped": true
}
}
]
}
```
> NOBUG: Added latitude and longitude to Elasticsearch

- src/gatsby/gatsby-config.js
CM-824
The way to turn off "download as an app" is to remove `gatsby-plugin-manifest`, but that plugin also turns the site into a progressive web app and controls things like the browser colour on mobile. So I just changed the wording of the message instead of removing the plugin.  Instead of saying "gatsby-starter-default' it will say "bcparks.ca".
> CM-824: Update the 'download as an app' message

- src/gatsby/src/templates/park.js
None
- `window.location.replace` should work only if the page URL has a hash
> NOBUG: Fix redirecting issue on park page

- src/cms/src/api/protected-area/custom/protected-area-search.js
- src/cms/src/api/protected-area/services/search.js
CM-888
OR aggregations for camping and regions need to each have filters for the other group.
> CM-888: Incorrect aggregations for camping and regions

- .github/workflows/build-dev.yaml
- .github/workflows/deploy-alpha-test.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-test.yaml
None
Bump repository-dispatch to v2 because v1 uses node12 (which is deprecated by GitHub)
> NOBUG: Bump repository-dispatch to v2

- .github/workflows/build-dev.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-test.yaml
- .github/workflows/on-pr.yaml
None
Update actions/checkout to v3 because v2 uses node12 (which is deprecated)
> NOBUG: Update actions/checkout to v3

- src/cms/src/api/public-advisory-audit/content-types/public-advisory-audit/lifecycles.js
- src/cms/src/api/public-advisory/content-types/public-advisory/lifecycles.js
- src/cms/src/api/search-indexing/controllers/search-indexing.js
- src/elasticmanager/scripts/indexParks.js
CM-917
1. Fixed public-advisory afterCreate and afterUpdate hooks to use `ctx.params.data` instead of `ctx.result` because the latter did not contain the public advisory id.
2. Updated public-advisory-audit lifecycle hooks to use `strapi.entityservice.create` and `strapi.entityservice.delete` instead of `strapi.db.create` and `strapi.db.delete`. These are higher level methods and might work more reliably with chained lifecycle hooks.
3. Updated `getParksForIndexing()` to use `query.publicationState = "preview"`. This fixes a bug where unpublished parks were not being removed and items were being left in the task queue.
> CM-917: Elasticsearch indexing fixes

- src/cms/database/migrations/2023.08.31T00.00.07.search-region.js
- src/cms/src/api/management-area/content-types/management-area/schema.json
- src/cms/src/api/search-region/content-types/search-region/schema.json
- src/cms/src/api/search-region/controllers/search-region.js
- src/cms/src/api/search-region/routes/search-region.js
- src/cms/src/api/search-region/services/search-region.js
CM-904
Create and populate the Search-regions collection type
NOTE: You might need to run this SQL command after you merge this change because according to [the docs](https://docs.strapi.io/dev-docs/database-migrations), _"migrations are run automatically when the application starts and are executed before the automated schema migrations that Strapi also performs on boot."_
```
delete from strapi_migrations where name = '2023.08.31T00.00.07.search-region.js'
```
> CM-904: Create and populate Search-regions

- src/gatsby/gatsby-browser.js
CM-907
1. Fixed an issue where park pages were scrolling to the middle of the page
2. Fixed an issue where the find-a-park page wasn't scrolling all the way back to where the user came from
This is based on a suggested work-around for this Gatsby issue: https://github.com/gatsbyjs/gatsby/issues/38201
> CM-907: Temp fix for Gatsby scroll restoration

- src/gatsby/src/components/park/parkDates.js
- src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
CM-927
- Change the wording "not yet available" to "unavailable" on park dates. The new wording still allows parks with missing dates to be identified without falsely implying that there will be dates entered sometime in the future. 
- Removed the conditional check from park pages that showed "Main camping season dates" instead of "Main operating season dates" for camping facilities.
> CM-927: Change "not yet available" to "unavailable" on park dates

- src/gatsby/src/styles/staticLanding1.scss
CM-866
- Add `!important` to the original CSS to override material ui style when the page is loaded
> CM-866: Add css to override material ui style when page is loaded

- src/cms/src/plugins/strapi-plugin-ckeditor/admin/src/components/Input/CKEditor/theme/common.js
CM-874
Change the initial (unfocussed) max-height for CKEditor from 12.5rem to 700px to match the focussed max-height.
> CM-874: Change initial max-height for ck-editor from 12.5rem to 700px

- src/gatsby/src/components/search/mobileFilters.js
CM-935
Removed call to `navigate` because it was clearing the querystring and losing the search state.
> CM-935: On Mobile devices-> Filters does not retain when navigating back

- src/elasticmanager/scripts/indexParks.js
- src/elasticmanager/utils/elasticClient.js
CM-851
Fixed a bug where the entire park object was being passed to removePark instead of just the id.
> CM-851: Fix for error removing parks from elasticsearch

- src/gatsby/src/pages/find-a-park.js
- src/gatsby/src/templates/park.js
CM-941
Restore the search querystring in cases where history.back cannot be used
> CM-941: Retain search query after in-page navigation

- infrastructure/helm/bcparks/values-prod.yaml
- infrastructure/helm/bcparks/values.yaml
CM-944
Fix for issue where the rest cache was empty.
- Pass in values as strings because long integers can get converted to exponents by Helm
- Reduce the cache duration for PROD for 30 minutes to 10 minutes
- Reduce the cache duration for all other environments to 1 minute
> CM-944: Update strapi-rest-cache ttl & fix helm issue

- src/elasticmanager/transformers/park.js
- src/gatsby/gatsby-config.js
- src/gatsby/src/templates/park.js
CM-495
Remove unused fields from Gatsby GraphQL to reduce the number of joins needed to populate the data from Strapi
> CM-495: Revert the use of escaped parknames on park pages

- src/cms/src/plugins/strapi-plugin-ckeditor/admin/src/components/Input/CKEditor/theme/common.js
CM-958
- Public site has override CSS which changes `a` text link colour to be normal text colour if it does not have  `href` link, so applied this override CSS to the ck editor CSS
> CM-958: Update ck editor CSS for a without href link

- src/gatsby/gatsby-browser.js
CM-960
Fixed issue preventing park pages from scrolling with location.hash coming from a Gatsby Link
> CM-960: Links on top of the park page do not function

- src/gatsby/gatsby-config.js
CM-976
- Fix missing management document type in the management documents list
- Merge it to main since this issue is happening on PROD
> CM-976: Fix missing management document type in management documents list

- infrastructure/helm/bcparks/templates/elasticmanager/elasticmanager-deployment.yaml
- infrastructure/helm/bcparks/values.yaml
- src/cms/config/middlewares.js
- src/cms/src/api/geo-shape/content-types/geo-shape/schema.json
- src/cms/src/api/geo-shape/controllers/geo-shape.js
- src/cms/src/api/geo-shape/routes/geo-shape.js
- src/cms/src/api/geo-shape/services/geo-shape.js
- src/cms/src/api/protected-area/content-types/protected-area/schema.json
- src/cms/src/api/search-indexing/controllers/search-indexing.js
- src/elasticmanager/.env.example
- src/elasticmanager/index.js
- src/elasticmanager/scripts/createParkIndex.js
- src/elasticmanager/scripts/indexParks.js
- src/elasticmanager/scripts/populateGeoShapes.js
- src/elasticmanager/scripts/queueAllParks.js
- src/elasticmanager/transformers/park.js
- src/elasticmanager/utils/commandLine.js
- src/elasticmanager/utils/geoHelpers.js
CM-963
CM-964
Add geo-shapes to Elasticsearch and Strapi
Note: In order to run this, you need to complete the following steps:
1. copy the `GEOSHAPE_URL` key from `src\elasticmanager\.env.example` to `src\elasticmanager\.env`
2. add permissions to the new Geo-shapes collection type in Strapi admin
- public role: find and findOne
- authenticated role: all permissions
3. run `node index.js rebuild` in the Elasticmanager
> CM-964: Add geoshapes to Strapi and Elasticsearch

- src/gatsby/src/components/megaMenu.js
- src/gatsby/src/styles/megaMenu/megaMenu.scss
CM-704
- If users click a sub-item in megamenu twice, megamenu keeps open but sub-item menu will be hidden
> CM-704: Hide sub menu items when menu item is clicked twice

- src/cms/src/api/fire-ban-prohibition/services/fire-ban-prohibition.js
CM-994
Fixes a bug where draft fire bans were being propagated to protected areas.  
The propagate script uses the Strapi Entity Service API, and the default publicationState for the Entity Service API is “preview” (whereas the default publication state for the REST API is “live”)
> CM-994: Don't propagate draft fire bans

- src/cms/src/api/protected-area/custom/protected-area-search.js
- src/cms/src/api/protected-area/services/search.js
CM-965
Added a `near` parameter to the querystring for `/protected-areas/search`.  This overrides the default sort order and sorts by distance to the designated point instead.
e.g. http://localhost:1337/api/protected-areas/search?near=49.129,-122.724&queryText=park&areas[]=3&campings[]=1&_start=0&_limit=10
> CM-965: Back-end for radius search

- src/cms/src/api/fire-ban-prohibition/controllers/fire-ban-prohibition.js
- src/cms/src/api/fire-ban-prohibition/services/fire-ban-prohibition.js
CM-994
Compare the list of parks with firebans before and after running the propagation script.  Any parks with firebans added or removed need to be re-indexed.
> CM-994: reindex parks updated by fireban propagation

- src/elasticmanager/index.js
CM-1022
Removed calls to `populateGeoShapes()` from `reindex`, `rebuild`, and `once` scripts.  populateGeoShapes is now only called from the cron job and from the specific `geoshapes` script.  The previous implementation made it too easy to get multiple populateGeoShapes jobs running simultaneously, which could results in data integrity issues.
> NOBUG: Elasticmanager geoshape changes

- src/cms/src/api/protected-area/services/search.js
- src/elasticmanager/transformers/park.js
None
This fixes an issue where you couldn't search for ec manning without periods (you could only search for "E.C. Manning")
The lowercase park names are now being stored in Elasticsearch with periods removed.
> NOBUG: Handle search for ec manning without periods

- src/cms/database/migrations/2023.10.17T00.00.08.search-cities.js
- src/cms/src/api/search-city/content-types/search-city/schema.json
- src/cms/src/api/search-city/controllers/search-city.js
- src/cms/src/api/search-city/routes/search-city.js
- src/cms/src/api/search-city/services/search-city.js
- src/gatsby/gatsby-config.js
- src/gatsby/src/pages/find-a-park.js
CM-1028
Added Search_city collection to Strapi
In order to populate this on your local, you will need to complete the following extra steps
1. Run `npm run develop`
2. Stop Strapi, and run these commands in your postgres docker container 
`psql -U postgres -d cms`
`delete from strapi_migrations where name = '2023.10.17T00.00.08.search-cities.js';`
3. Run `npm run develop` again
4. Edit the  Roles on Strapi, and assign the following roles to Seach-city
- Public Role: find and findOne
- Authenticated Role: all permissions
5. The GraphQL query has already been added to `find-a-park.js`.  It is currently filtering for `rank: {lte: 4}`
> CM-1028: Add search cities

- infrastructure/kong/clean.js
None
Exclude search cities from Kong export.  BC Parks is not the authoritative source for this data.
> NOBUG: Update kong for search cities

- src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
- src/cms/src/api/public-advisory-audit/controllers/public-advisory-audit.js
CM-1023
- 4 calls to `validAdvisoryData()` were missing the `linksRef` parameter
- Also fixed an unrelated issue that was causing a 500 error retrieving history for public advisory audits
> CM-1023: bugfix for submit advisory and save draft as submitter

- src/cms/src/api/park-photo/content-types/park-photo/schema.json
CM-881
Add a maxlength of 255 characters to the photo caption input.  
NOTE: This will show a warning to users, but it won't actually stop them from saving.
> CM-881: Add maxLength to photo caption RTE

- src/gatsby/src/components/search/mainSearch.js
- src/gatsby/src/components/search/parkNameSearch.js
CM-1057
- Fixed missing value in the park name search field when redirecting from the home page
- Fixed bookmarkable URL
- Fixed an issue where the spacebar was triggering a search from the home page, so you couldn't type names with more than 1 word.
> CM-1057: autosuggest park name missing in field on park page

- src/gatsby/src/components/search/parkNameSearch.js
- src/gatsby/src/pages/find-a-park.js
CM-1054
- Fix park name option render issue that is 1 letter behind the call
- Use useCallbuck instead of useEffect
Reference: https://stackoverflow.com/questions/71242392/options-not-showing-when-using-custom-input-in-react-bootstrap-typeahead
> CM-1054: Fix park name option render issue

- src/gatsby/src/components/search/cityNameSearch.js
- src/gatsby/src/components/search/parkNameSearch.js
CM-1060
- If the user types the same as one of the options in the near a city field, the user can search parks without selecting
- If the user types some words in the by park name field, the user can search with the enter key
> CM-1060: Fix near a city field search issue

- infrastructure/aws-opensearch/README.md
- infrastructure/aws-opensearch/setup/README.md
- infrastructure/aws-opensearch/setup/tfstate.tf
CM-1047
Updates to Terraform stemming from work on https://github.com/bcgov/bcparks-dam
> CM-1047: Terraform updates

- src/gatsby/src/pages/find-a-park.js
CM-1119
- Fix search park field refreshing issue
- The issue occurred when a user typed some words and searched, and then typed again without deleting the previous search term (e.g. Search "adams" and select text "adams" and type some new words without clearing the field)
> CM-1119: Fix search park field refreshing issue

- src/gatsby/src/pages/find-a-park.js
CM-1125
Two extra rest calls were happening with `near=0,0` in the querystring when the bookmarkable URL was being loaded.  I think this might have been causing a race condition that was causing the error in CM-1125.
> CM-1125: Fix race condition causing 4 REST calls instead of 2.

- src/gatsby/src/components/search/parkNameSearch.js
None
Update the behaviour of the arrow keys in the park name drop down to match the city dropdown. With this change, users can use the up-arrow key to go back up to the text input (like on Google)
> NOBUG: arrow key behaviour consistency

- src/gatsby/src/pages/find-a-park.js
CM-1140
Improvements to park search REST call efficiency and logging.
1. `near=0,0&radius=100` parameters are not needed when no geo query is specified
2. `radius=50` query is not needed when no geo query is specified
> CM-1140: Fix park search REST API call logging issues

- src/gatsby/src/pages/find-a-park.js
CM-1140
Fixed an edge case where near=0,0 was still being passed in REST API params
> CM-1140: Fix for Current Location default init values

- src/gatsby/src/pages/find-a-park.js
CM-1145
- Reverted the 2nd commit on PR #1134 
- Use `underfinied` instead of `""` when clearing qsLocation
> CM-1145: Fix issue with current location

- src/gatsby/src/styles/parks.scss
CM-1153
Added 4 pixels top margin to big images on park page photo galleries to fix alignment issue
> CM-1153: Fix photo gallery alignment issue

- src/elasticmanager/transformers/park/operatingDates.js
- src/gatsby/gatsby-config.js
- src/gatsby/gatsby-node.js
- src/gatsby/src/components/park/parkAccessStatus.js
- src/gatsby/src/components/park/parkDates.js
- src/gatsby/src/components/park/parkHeader.js
- src/gatsby/src/components/search/parkCard.js
- src/gatsby/src/templates/park.js
- src/gatsby/src/templates/site.js
CM-1148
- Added a new "Seasonal restrictions" status which is triggered by park gates closures and subarea closures
Testing notes:
- you'll need to re-index elasticsearch after applying this change because `subareaTypeId` was renamed to `subAreaTypeId`.
- parkSubAreaType and parkSubArea must each have at least one record with a value for `closureAffectsAccessStatus`
> - frontcountry camping. day use, day use area, and picnic area sub-area-types should all be set to true, everything else should be `false`
> - set all frount country campgrounds subareas with "overflow" in their name to `false`
> - only parks that would otherwise show as `Open` will show as Seasonal restrictions when the criteria is met
> - closed and inactive subareas are ignored
> - sub area dates must be explicity set to …
> CM-1148: Park access status - update logic to include gates

- src/gatsby/src/components/park/parkAccessStatus.js
CM-1148
Fixes a white screen error that happens on alpha-dev when we forget to re-index Elasticsearch after deployment.
> CM-1148: Better error handling when the search index hasn't been updated

- src/gatsby/src/styles/search.scss
CM-1133
- Fix park search text overlapping with a clear button
> CM-1133: Fix park search text overlapping with a clear button

- infrastructure/helm/bcparks/templates/cms/cms-hpa.yaml
- infrastructure/helm/bcparks/templates/public/public-hpa.yaml
- infrastructure/helm/bcparks/values-alpha-dev.yaml
- infrastructure/helm/bcparks/values-prod.yaml
- infrastructure/helm/bcparks/values.yaml
None
- Removed memory triggers from HorizontalPodAutoscalers for cms and public (memory triggers have proven to behave weirdly due to memory leaks and are not a reliable metric)
- Updated some settings for the ETL cron jobs
> NOBUG: Update autoscalers & add cron settings

- src/gatsby/src/components/park/parkAccessStatus.js
- src/gatsby/src/components/park/parkDates.js
- src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
- src/gatsby/src/styles/listPage.scss
- src/gatsby/src/utils/parkDatesHelper.js
CM-1201
CM-1154
Minor updates to gate logic and display based on UX and QA feedback
CM-1201: 
- Reverted back to single-line accessStatus/gateText display on larger devices
- Streamlined logic for determining when to add a period in the text
- Updated some logic that was adding `&nbsp;` characters to date phrases so it is used more sparingly. It was messing up formatting in some places where it wasn't needed.
CM-1154:
- Removed the check for marineProtectedArea
- Don't hide the gate sentence when `hasParkGate === false`. Instead just remove the word "gate" from the sentence.
> CM-1201: Update gate logic and display

- src/gatsby/gatsby-config.js
CM-1148
Fixed a Gatsby issue where park-operation-sub-area-dates were not getting refreshed unless `gatsby clean` was run
> CM-1148: Fix caching issue with park-operation-sub-area-dates

- src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
- src/admin/src/components/page/advisory/Advisory.js
- src/admin/src/validators/AdvisoryValidator.js
CM-1097
- Remove the pre-populated value from the requested by field
- If a user is a submitter, then there's no requested by field. If a submitter creates an advisory, the submitter name is no longer required in validation but the key cloak data will be applied automatically (same as the advisory status).
> CM-1097: Remove pre-populated value from the requested by field

- src/cms/config/cron-tasks.js
CM-1018
The examples in the Strapi documentation show that date filters should be passed to the Strapi entityService as ISO strings, not date objects https://docs.strapi.io/dev-docs/api/entity-service/filter#and
> CM-1018: Fix for scheduled advisory publish and expiry

- infrastructure/helm/bcparks/templates/scheduler/scheduler-deployment.yaml
- infrastructure/helm/bcparks/values.yaml
- src/cms/src/api/public-advisory/controllers/public-advisory.js
- src/cms/src/api/public-advisory/services/scheduling.js
- src/scheduler/.env.example
- src/scheduler/email-alerts/scripts/mailer.js
- src/scheduler/email-alerts/scripts/sendAdvisoryEmails.js
- src/scheduler/email-alerts/templates/public-advisory.ejs
CM-1167
Added the last email trigger for advisories expiring in 1 week
Note that the entry in the queued tasks may be added up to 3 times, but the `THROTTLE_MINUTES` setting in the scheduler will ensure that only 1 email is sent about any specific advisory every 10 minutes. 
Additional changes included in this PR:
1. Fix incorrect smtp server address in helm charts
2. Added environment-specific urls for linking to the public site and the admin site in emails 
3. Added the sender name "Staff Web Portal" to the email `from` header.  
4. Fixed an error in mail subjects, so the advisory headline is prepended to the subject
5. Minor updates to email font colours
> CM-1167: Email notification for advisories expiring soon

- src/cms/src/components/parks/link-card.json
CM-1325
- Remove 2 fields from link-card component since they're not used
- Not sure why, but it seems to be added in this commit: https://github.com/bcgov/bcparks.ca/commit/e602dc0bf7f4b4fdf0734f2a7888612c04a9ad9f#diff-c53d24251a9175ad00c95800a25d18d3ca2fe73d56361bf94d5c0a22eeaf7de9
> CM-1325: Remove unused fields from link-card component

- src/cms/database/migrations/2024.03.14T00.00.11.natural-resource-districts.js
- src/cms/database/migrations/2024.03.14T00.00.12.natural-resource-districts-mapping.js
- src/cms/src/api/natural-resource-district/content-types/natural-resource-district/schema.json
- src/cms/src/api/natural-resource-district/controllers/natural-resource-district.js
- src/cms/src/api/natural-resource-district/routes/natural-resource-district.js
- src/cms/src/api/natural-resource-district/services/natural-resource-district.js
- src/cms/src/api/protected-area/content-types/protected-area/schema.json
CM-1223
This PR adds the Natural-resource-district collection and imports the data.  I had to use two migration files to split up the database transaction in order to read the Natural-resource-district data back from the database and get the generated ids. 
After the schema is updated, you'll need to delete two records from the `strapi_migrations` table and then restart Strapi so the migrations run a second time.
```
delete from strapi_migrations where name like '%natural-resource%';
```
> CM-1223: Add natural resource district data

- src/admin/package-lock.json
- src/admin/package.json
CM-1296
- Fix some of the vulnerabilities
From
```
47 vulnerabilities (19 moderate, 28 high)
```
To
```
45 vulnerabilities (17 moderate, 28 high)
```
- Updated an outdated library
```
Package                              Current          Wanted          Latest  Location                                   Depended by
@babel/preset-react                   7.23.3          7.24.1          7.24.1  node_modules/@babel/preset-react           admin
```
> CM-1296: Update admin libraries

- src/gatsby/src/utils/helpers.js
CM-1335
Show the parks logo if the image url is null. This fixes an error that caused a blank screen.
> CM-1335: Error handling for null image url in search

- infrastructure/helm/bcparks/templates/etl/etl-cronjob.yaml
- infrastructure/helm/bcparks/values.yaml
- src/cms/src/api/fire-ban-prohibition/content-types/fire-ban-prohibition/schema.json
- src/cms/src/api/fire-ban-prohibition/services/fire-ban-prohibition.js
- src/etl/.env.example
- src/etl/index.js
- src/etl/scripts/bcwfs-bans.js
- src/etl/scripts/bcwfs-propagate.js
CM-1328
- Added natural resource districts to the firebans collection
- Added natural resource districts to fireban propagation
- Changed the logic for fireban propagation so a fireban can be propagated based on both a fire centre and a fire zone at the same time
- Added a stand-alone propagation option to the ETL cron job
> CM-1328: Add natural resource districts to fire bans

- src/cms/src/api/park-operation-sub-area-type/content-types/park-operation-sub-area-type/schema.json
- src/cms/src/api/park-operation-sub-area/content-types/park-operation-sub-area/schema.json
- src/cms/src/api/park-operation/content-types/park-operation/schema.json
CM-1307
This change adds support for deep URL links to the BC Parks reservation system, which will be used as part of the park page redesign.  
Four new fields have been added
1. ParkOperation.camisResourceLocationId
2. ParkOperation.camisMapId
3. ParkOperationSubAreaType.reservationTemplateString
- this will be a URL with placeholders, e.g.  https://camping.bcparks.ca/create-booking/results?resourceLocationId={camisResourceLocationId}&mapId={camisMapId}&searchTabGroupId=0&bookingCategoryId=0
4. ParkOperationSubArea.reservationOverrideUrl
- This field provides a mechanism for overriding the templated URLs. Several cases have been identified that will require manual overrides. 
- this is also a URL, but without placeholders, e.g. https://camping.bcparks.ca/create-booking/results?mapId=-2147 …
> CM-1307: Create Strapi fields for URL links to reservation services

- src/cms/src/api/public-advisory/controllers/public-advisory.js
- src/cms/src/api/public-advisory/services/search.js
CM-1270
- Update search advisory api population
- Turned out, a simple misspelling caused an issue that made `standardMessages` missing
> CM-1270: Update search advisory api population

- src/cms/src/api/access-status/content-types/access-status/schema.json
- src/cms/src/api/public-advisory/controllers/public-advisory.js
- src/gatsby/src/templates/park.js
CMS-57
Added a flag to access-status so the seasonal advisory could be suppressed when there was a full park closure
> CMS-57: Add flag to hide seasonal advisories from the park page

- src/cms/src/api/park-photo/content-types/park-photo/lifecycles.js
- src/cms/src/api/park-photo/content-types/park-photo/schema.json
- src/cms/src/api/protected-area/content-types/protected-area/schema.json
- src/cms/src/api/site/content-types/site/schema.json
CMS-62
- Add protectedArea and site relation to parkPhoto
- If protectedArea/site is added to parkPhoto, its orcs/orcsSiteNumber will be updated too
- No change on FE at this moment
- Data migration will be needed
- Nearby park section file should be updated
> CMS-62: Add protectedArea and site relation to parkPhoto

- infrastructure/kong/README.md
- infrastructure/kong/clean.js
- infrastructure/kong/public-prod.yaml
- infrastructure/kong/public-test.yaml
- src/cms/config/plugins.js
- src/cms/src/index.js
CMS-211
This fixes an error reported by BC Parks where https://bcparks.api.gov.bc.ca/api/park-operation-dates was not accessible via the API gateway.  
In addition, two new collection types were added to the API gateway
- emergency-alerts
- natural-resource-districts
The configuration of the documentation plugin (which is used to generate the Kong config) was also updated to hide collection types that are only intended to be used internally for the operation of the website.  
- public-advisory-audit
- queued-task
- search-indexing
- statutory-holiday
- geo-shape
- search-city
- footer-menu
- menu
- website
- uploads plugin
- users-permissions plugin
> CMS-211: Regenerate Kong config

- src/gatsby/src/components/park/parkOverview.js
- src/gatsby/src/styles/parks.scss
CMS-27
- Update park overview to highlights in this park
- If there's `<hr>` in RTE, the expand/collapsed toggle button will be displayed at that position, otherwise, it will display at the height of 260px
> CMS-27: Update park overview to highlights in this park

- src/cms/src/api/public-advisory/controllers/public-advisory.js
CMS-225
This change fixes an error loading advisories on the park operating dates page. To reproduce the error you need to create an advisory with no access status.
> CMS-225: Fix advisories error on park operating dates page

- src/gatsby/src/templates/staticContent1.js
CMS-240
- Add fallback to staticContent page if imageUrl is empty
- Don't display `<img>` and its wrapper `<div>` if imageUrl is empty
> CMS-240: Add fallback to staticContent page if imageUrl is empty

- src/cms/src/api/public-advisory/controllers/public-advisory.js
- src/scheduler/server.js
CMS-239
1. Changed the order of tasks in the scheduler to ensure a 1 minute buffer between expiring or publishing an advisory and updating the park in Elasticsearch.  This might fix a possible race condition where the park could be getting reindexed before we finished running all the lifecycle hooks. As far as I know Patroni only queries the leader, but if my understanding of Patroni is wrong then this could also fix a Postgres replication delay. 
2. Clear the protected area cache when an advisory is expired or published. This probably wasn't causing the bug because the scheduler users the search-indexing API, not the public-advisories API.
> CMS-239: Advisories not updating in Elasticsearch upon auto-expiry

- infrastructure/helm/bcparks/values.yaml
CMS-235
Updated the helm files to reflect the new version of the patroni container.  
Also deleted a reference to a postgres container that was not used.
> NOBUG: Update helm files following patroni upgrade

- src/cms/src/admin/app.js
CMS-163
This block of code never worked in non-dev mode anyway, but now it's causing Strapi admin to fail completely with the error  "process is not defined". The error is on both alpha-dev and alpha-test.
@ayumi-oxd should we just remove this code completely, or keep it because it did work on localdev? I'm leaning toward deleting the entire switch statement
Update: the code has been removed completely
> CMS-163: Fix error running strapi 4.25 in non-dev mode

- src/gatsby/src/archived/intro.js
- src/gatsby/src/components/megaMenu.js
- src/gatsby/src/pages/404.js
- src/gatsby/src/pages/about/management-plans/approved.js
- src/gatsby/src/pages/active-advisories.js
- src/gatsby/src/pages/find-a-park.js
- src/gatsby/src/pages/find-a-park/a-z-list.js
- src/gatsby/src/pages/index.js
- src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
- src/gatsby/src/pages/site-map.js
- src/gatsby/src/styles/cmsSnippets/parkInfoPage.scss
- src/gatsby/src/styles/parks.scss
- src/gatsby/src/templates/park.js
- src/gatsby/src/templates/parkSubPage.js
- src/gatsby/src/templates/site.js
- src/gatsby/src/templates/staticContent1.js
- src/gatsby/src/templates/staticLanding1.js
CMS-238
- Fix the menu child item was not filtered by show boolean
- GraphQL doesn't filter nested relations at the child level (e.g. menu.strapi_children) so filtering was needed on FE
- Fix some styling issues on the Park page
> CMS-238: Fix the menu child item was not filtered by show boolean

- src/cms/database/migrations/2024.07.29T00.00.16.rename-has-reservations.js
- src/cms/src/api/park-operation/content-types/park-operation/schema.json
CMS-246
1. Added the following fields
- hasFrontcountryReservations (replaces hasReservations which will be dropped later)
- hasFrontcountryGroupReservations
- hasFrontcountryCabinReservations
- hasBackcountryGroupReservations
- hasBackcountryWildernessReservations
- hasBackcountryShelterReservations
- hasCanoeCircuitReservations
- hasGroupPicnicReservations
2. Copied data from  hasReservations to hasFrontCountryReservations
Note: you will need to delete the most recent migration from the strapi_migrations table and run it again.
> CMS-246: Add new reservation fields

- src/gatsby/src/utils/helpers.js
CMS-267
- Update handleImgError
- Fix the issue that the previous error state is not inherited
> CMS-267: Update handleImgError

- src/gatsby/src/styles/parks.scss
CMS-307
- Add max width to text content from RTE on the park and site page
- This change doesn't apply to the accordions and the blockquote
> CMS-307: Add max width to text content on park and site page

- src/gatsby/src/styles/search.scss
CMS-38
- Fix nearby park card title wrapping issue on Firefox
> CMS-38: Fix nearby park card title wrapping issue on Firefox

- src/gatsby/src/components/park/parkDates.js
CMS-351
This fixes a bug where inactive subareas are being shown in the dates of operation section.
> CMS-351: Inactive subareas are shown in Dates of Operation

- src/cms/database/migrations/2024.08.22T00.00.20.nature-and-culture.js
- src/cms/src/api/protected-area/content-types/protected-area/schema.json
CMS-353
- This script migrates the nature and culture field into 4 new fields
- Only parks with a parsable nature and culture section will be migrated
- To run the migration script, you'll need to delete a strapi migration and restart strapi
`2024.08.22T00.00.20.nature-and-culture.js`
- The line of code that removes the old data from the natureAndCulture field has been commented out in the migration so QA can compare the data
> CMS-353: Data migration for nature and culture

- src/gatsby/gatsby-node.js
- src/gatsby/package-lock.json
- src/gatsby/package.json
- src/gatsby/src/components/park/parkHeader.js
- src/gatsby/src/components/park/parkPhoto.js
- src/gatsby/src/styles/parks.scss
- src/gatsby/src/templates/park.js
- src/gatsby/src/templates/site.js
CMS-312
- Remove arcgis since we don't have a map on the park page anymore
- According to the Lighthouse, the main performance issue of the park page was rendering images
- [Lighthouse Report Viewer.pdf](https://github.com/user-attachments/files/16806259/Lighthouse.Report.Viewer.pdf)
- I needed to handle external images directly in the component, so used [the lazy load image component](https://www.npmjs.com/package/react-lazy-load-image-component) for lazy loading since gatsby-plugin-image is primarily designed for local images
- Known issue: It slightly takes time to load the access status and the campfire ban in the TLDR section compared to other content because it has to get data through Stapi API
> CMS-312: Add lazy load image component

- src/gatsby/src/components/pageContent/pageMenu.js
CMS-361
- Fix the issue that the first select option doesn't get updated by scrolling
- The value of the "Table of Contents" was a duplicate of the first section value, so that the first option didn't get selected by scrolling
- Disable the "Table of Contents" as an option since it doesn't take the users to any section
> CMS-361: Update page menu on mobile

- src/gatsby/src/components/megaMenu.js
CMS-302
- Fix the issue that the screen readers announce "main menu" and "menu"
- `generateMenus` is wrapped by `<div role="menu"></div>` so this `<h2>` title for the screen readers was redundant
> CMS-302: Update mega menu aria label for screen readers

- src/gatsby/src/styles/parks.scss
CMS-400
- Fix the issue when navigating to the contact section directly from a url
- The last element needed to have a certain height to be scrolled by `useScrollSpy`
> CMS-400: Fix issue when navigating to the contact section directly from a url

- src/gatsby/gatsby-browser.js
- src/gatsby/src/utils/useSnowplowTracking.js
CMS-363
- Added `useEffect` hook to call the snowplow event every time a page renders or re-renders, not just when the router is updated, based on Mike's comment: https://github.com/bcgov/bcparks.ca/pull/1503
- Used `wrapPageElement` to wrap all pages with the custom hook: https://www.gatsbyjs.com/docs/reference/config-files/gatsby-browser/#wrapPageElement
- Need to test it on the DEV/TEST/PROD since we have `GATSBY_ENABLE_SNOWPLOW` in the `.env`
> CMS-363: Update snowplow tracking

- src/gatsby/gatsby-browser.js
CMS-363
- Add snowplow track to onRouteUpdate
- Revert the initial idea since it was needed for single-page applications like Gatsby, where navigation between pages does not trigger a full-page reload
> CMS-363: Add snowplow track to onRouteUpdate

- src/cms/src/api/public-advisory/controllers/public-advisory.js
- src/cms/src/api/public-advisory/services/scheduling.js
CMS-109
- Add email notification for prescheduled advisories
- Send emails 2/5 days before the advisory date (posting date)
> CMS-109: Add email notification for prescheduled advisories

- src/gatsby/src/components/park/parkHeader.js
- src/gatsby/src/components/park/parkPhotoGallery.js
- src/gatsby/src/styles/parks.scss
CMS-93
CMS-297
- Add a comma between the year and the 24 hours in the park header wording, forgot to add it in this PR: https://github.com/bcgov/bcparks.ca/pull/1517/files
- Update photographer credit layout - the layout was off if the caption was wrapped by another element
> CMS-297: Add a comma between the year and the 24 hours in park header wording

- src/gatsby/src/components/park/parkOverview.js
CMS-507
- Fix an issue that show more button disappears
- No need to update `height` when the content has `hr`
> CMS-507: Fix an issue that show more button disappears

- src/cms/src/api/park-operation-sub-area/content-types/park-operation-sub-area/schema.json
- src/cms/src/api/park-operation/content-types/park-operation/schema.json
- src/gatsby/gatsby-node.js
- src/gatsby/src/components/park/parkHeader.js
- src/gatsby/src/templates/park.js
- src/gatsby/src/templates/site.js
CMS-297
- Add gateOpen24Hours to parkOperation and parkOperationSubArea
- Override gateOpenTime, gateCloseTime, gateOpensAtDawn, gateClosesAtDusk if gateOpen24Hours is TRUE
> CMS-297: Add gateOpen24Hours to parkOperation

- src/admin/src/components/page/parkAccessStatus/ParkAccessStatus.js
- src/cms/src/api/park-activity/content-types/park-activity/lifecycles.js
- src/cms/src/api/park-activity/content-types/park-activity/schema.json
- src/cms/src/api/park-camping-type/content-types/park-camping-type/lifecycles.js
- src/cms/src/api/park-camping-type/content-types/park-camping-type/schema.json
- src/cms/src/api/park-facility/content-types/park-facility/lifecycles.js
- src/cms/src/api/park-facility/content-types/park-facility/schema.json
- src/cms/src/api/park-operation-sub-area/content-types/park-operation-sub-area/schema.json
- src/cms/src/api/protected-area/content-types/protected-area/schema.json
- src/cms/src/helpers/validator.js
- src/gatsby/src/components/park/about.js
- src/gatsby/src/components/park/parkAccessStatus.js
- src/gatsby/src/templates/park.js
CMS-49
- CMS-49: Remove smoking ban from park access status table
- CMS-526: Remove natureAndCulture from protectedArea
- CMS-522: Change park-activity, park-facility, and park-camping-type required - Strapi doesn't have a function to make a relational field required so added custom validation in the Strapi lifecycle.
- CMS-532: Remove subAreaTypeId from parkOperationSubArea
> CMS-49: Remove smoking ban from park access status table

- src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
CMS-545
- Found 429 errors happen only on TEST env when fetching the advisories data (e.g. https://bcparks.test.api.gov.bc.ca/api/public-advisories/items?filters[protectedAreas][orcs][$eq]=6197&pagination[limit]=100) but not on other envs or my local. Added retry with `setTimeOut` when it has an error to fix this issue. Any advice is more than welcome since I'm not really sure how to fix it 😅
> CMS-545: Add retry to fetch advisories on park operating dates page

- src/gatsby/src/components/advisories/advisoryPageNav.js
- src/gatsby/src/pages/active-advisories.js
CMS-544
- Fix the issue that the load more button on Active advisory page takes the user back to top of the page
- The previous way caused the page re-rendering - removed `pageIndex` from `getAdvisories` useCallback dependency
> CMS-544: Fix the load more button on Active advisory page takes the user back to top of the page

- src/gatsby/src/components/advisories/advisoryFilter.js
CMS-582
- Update onKeyDown event on advisory event typeahead search
- When you tab focus on the event search
- you can select an event with the arrow keys and search with the enter key
- you can close (skip) the dropdown with the tab key
> CMS-582: Update onKeyDown event on advisory event typeahead search

- src/cms/database/migrations/2024.12.16T00.00.22.rename-has-frontcountry-reservations.js
- src/cms/src/api/park-operation/content-types/park-operation/schema.json
CMS-576
- Add hasReservations back to park-operation
- Data migration from `hasFrontcountryReservations`to `hasReservations`
- Update `hasReservations` value to TRUE if `reservationUrl` is not null
> CMS-576: Add hasReservations back to park-operation

- src/cms/src/api/park-operation/content-types/park-operation/schema.json
- src/gatsby/src/components/park/subArea.js
- src/gatsby/src/templates/park.js
- src/gatsby/src/templates/site.js
CMS-602
- Add more fixes to https://github.com/bcgov/bcparks.ca/pull/1555
- Change `parkOperation.gateNote` to RTE field
- Remove `parkOperationSubArea.generalNote` since it doesn't exist
- Remove unused fields from graphql queries
- Notes fields in use:
- `parkOperation.openNote` - in the TLDR on the Park/Site page
- `parkOperationSubArea.serviceNote`, `parkOperationSubArea.reservationNote`, `parkOperationSubArea.offSeasonNote` - in the Camping accordions on the Park/Site page
> CMS-602: Remove unused fields from graphql queries

- src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
- src/gatsby/src/utils/advisoryHelper.js
CMS-545
- Update API fetching on the park operating dates page
- Previously the API was called 1000 times as the same as the number of parks. 
After talking to @fatbird we've decided to change the API call rather than changing the API rate limit:
- Fetch all the advisories so that we just need one API call
- Filter advisories with `protectedArea.orc` so that we can determine each park access status
> CMS-545: Update api fetching on park operating dates page

- src/gatsby/src/components/advisories/advisoryCard.js
- src/gatsby/src/components/advisories/advisoryLegend.js
- src/gatsby/src/components/htmlContent.js
- src/gatsby/src/components/megaMenu.js
- src/gatsby/src/components/park/advisoryDetails.js
- src/gatsby/src/components/park/campingDetails.js
- src/gatsby/src/components/park/contact.js
- src/gatsby/src/components/park/customToggle.js
- src/gatsby/src/components/park/parkOverview.js
- src/gatsby/src/components/park/parkPhoto.js
- src/gatsby/src/components/search/cityNameSearch.js
- src/gatsby/src/components/search/parkNameSearch.js
- src/gatsby/src/pages/about/management-plans/approved.js
- src/gatsby/src/pages/find-a-park/a-z-list.js
- src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
- src/gatsby/src/styles/listPage.scss
CMS-485
CMS-542
CMS-548
CMS-549
CMS-550
CMS-554
CMS-643
- CMS-485: Add menuitem role to megamenu back button
- CMS-542: Add separation between urgency icon and advisory title
- CMS-548: Skip reading urgency icon label on active advisories page
- CMS-549: Add visually hidden link type to contact link
- It depends on how you guide the VO, but the VO could read only static text, not `aria-label`. Add visually hidden static text in case the VO doesn't read `aria-label`
- CMS-550: Adjust heading level on list pages
- CMS-554: Update status message in typeahead fields
- VO reads the status message if there's no match, but it doesn't read full text "No match. Please check your spelling." 🤔
- CMS-643: Add aria-hidden to expandable html content
- VoiceOver reads the content after users click the …
> CMS-542: Accessibility updates and fixes

- src/gatsby/src/components/megaMenu.js
- src/gatsby/src/components/search/cityNameSearch.js
- src/gatsby/src/components/search/parkNameSearch.js
CMS-665
- Add `aria-label` to the mega menu hamburger icon on mobile
- Fix broken aria reference on the Home page and the Find a Park page
- The target for `aria-describedby` reference was conditional, so applied the same logic to `aria-describedby` value
> CMS-665: Add aria-label to mega menu hamburger icon

- src/cms/src/api/protected-area/custom/protected-area-status.js
CMS-628
- Update public advisories filter to fix incorrect park access statuses display
- `precedence` limit needed to be updated since new access statuses are added
> CMS-628: Update public advisories filter to fix incorrect park access statuses display

- src/gatsby/src/components/megaMenu.js
- src/gatsby/src/styles/megaMenu/megaMenu.scss
CMS-485
- Replace `<nav>` with `<div>` not to contain elements with other roles inside the element with `role=menu`/`role=menuitem`
- SortSite warning:
```
Elements with role=menu must contain or own an element
with role=menuitem or role=menuitemcheckbox or role=menuitemradio
and must not contain elements with other roles. Owned roles: navigation
```
> CMS-485: Replace nav with div not to contain elements with other roles

- src/gatsby/src/components/megaMenu.js
CMS-669
- Skip focusing on hidden menu items - on mobile screen, menu items have to be focus-able only if the menu bar is open
- Add `useScreenSize` to check screen size
- Change `isMenuOpen` state based on screen size
> CMS-669: Skip focusing on hidden menu items

- src/gatsby/src/components/footer.js
- src/gatsby/src/components/megaMenu.js
- src/gatsby/src/components/park/about.js
- src/gatsby/src/components/park/advisoryDetails.js
- src/gatsby/src/components/park/parkActivity.js
- src/gatsby/src/components/park/parkDates.js
- src/gatsby/src/components/park/parkFacility.js
- src/gatsby/src/components/search/mainSearch.js
- src/gatsby/src/pages/find-a-park.js
- src/gatsby/src/utils/snowplowHelper.js
CMS-686
- Remove `url` from snowplow event schema
- URL value will be collected as a `label`
- Change `filter` default value from `null` to an empty obj `{}`
> CMS-686: Remove url from snowplow event schema

- src/gatsby/src/components/megaMenu.js
- src/gatsby/src/styles/bootstrapTheme.scss
CMS-668
CMS-669
- Display 'Skip to main content' when it gets focused on mobile
- Override Bootstrap CSS class
- The button gets focused when using VO, it works on Chrome with MacOS but not with iOS
- Fix an issue that voiceover reads all menu items on mobile even when the menu toggle is closed
- Add `aria-hidden` true to `<nav>` when the menu is closed on mobile 
- TODO: Need to test it on an actual device when it's merged since it's not possible to recreate the issues locally with MacOS
> CMS-669: Fix an issue that voiceover reads all menu items on mobile

- src/gatsby/src/components/park/campingDetails.js
- src/gatsby/src/components/park/parkOverview.js
CMS-643
- Fix an issue that users can't focus on the highlights section when there is no expand toggle
- The second issue that is mentioned in the ticket is not feasible. This is because the content is hidden with CSS, yet there is complete HTML content. Therefore, we can’t select just the visible part to let VO read. 
> Also, even if there is a link, we should first read what is already visible and then navigate to the expand link to expand and access the rest of the hidden content.
> CMS-643: Fix an issue that users can't focus on the highlights section when there is no expand toggle

- src/gatsby/src/components/pageContent/pageMenu.js
- src/gatsby/src/styles/pageContent/pageMenu.scss
- src/gatsby/src/templates/park.js
- src/gatsby/src/templates/parkSubPage.js
- src/gatsby/src/templates/site.js
- src/gatsby/src/templates/staticContent1.js
CMS-646
- Update the table of contents on mobile
- Change it to the list of links, no longer select/option
- It applies to the park page, the site page, and the park subpage. The static content page has the same layout, but it already has a typed-out contents link section, which would be redundant. So, we’ve decided to leave out the mobile change for the static content page.
> CMS-646: Update park page table of contents on mobile

- src/gatsby/src/components/skipToContent.js
- src/gatsby/src/styles/bootstrapTheme.scss
CMS-668
- Hide 'Skip to main content' on mobile since users don't have to skip the menu items
- Revert this change: https://github.com/bcgov/bcparks.ca/pull/1581/files
> CMS-668: Hide 'Skip to main content' on mobile

- src/cms/src/api/park-feature-date/content-types/park-feature-date/schema.json
- src/cms/src/api/park-feature-date/controllers/park-feature-date.js
- src/cms/src/api/park-feature-date/routes/park-feature-date.js
- src/cms/src/api/park-feature-date/services/park-feature-date.js
- src/cms/src/api/park-operation-sub-area/content-types/park-operation-sub-area/schema.json
CMS-682
- Add park feature date collection
- `dateType` options are “Operation”, “Reservation”, and “Winter fee”
- FE change will come after the data migration
> CMS-682: Add park feature date collection

- src/gatsby/src/components/header.js
- src/gatsby/src/components/skipToContent.js
CMS-123
- Fix a broken link accessibility error
- Change it to hide the link on mobile with the screen size state condition, not with CSS
- Error:
> A skip navigation link exists, but the target for the link does not exist or the link is not keyboard accessible.
> Ensure that the target for the link exists and that the link is not hidden with CSS display:none or visibility:hidden.
> CMS-668: Fix a broken link accessibility error

- src/gatsby/src/components/park/advisoryDetails.js
CMS-672
A small fix for the advisories sort order: We're using lodash `orderBy` here so we don't need to pass in a sort function, just an identity function to return the values to compare. I changed `compareAdvisories` to `getAdvisoryDate` to get the display date value, and `orderBy` does the comparison automatically.
Additionally, if the identity function just returns a property and doesn't do anything special, we can just supply the name as a string instead of having to write the function ourselves. I was able to simplify the other 4 sort parameters, so we've got 4 strings and just one function.
> CMS-672: Fix display date sorting for advisories

- src/cms/src/api/public-advisory/controllers/public-advisory.js
- src/gatsby/src/styles/advisories/advisoryCard.scss
CMS-782
- Remove empty p element from advisory description
- Fix that an empty `<p></p>` was added when the description data doesn't exist
> CMS-782: Remove empty p element from advisory description

- src/cms/config/plugins.js
- src/gatsby/gatsby-config.js
- src/gatsby/gatsby-node.js
- src/gatsby/src/components/park/campingDetails.js
- src/gatsby/src/components/park/parkDates.js
- src/gatsby/src/components/park/parkHeader.js
- src/gatsby/src/components/park/subArea.js
- src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
- src/gatsby/src/templates/park.js
- src/gatsby/src/templates/site.js
- src/gatsby/src/utils/parkDatesHelper.js
- src/gatsby/src/utils/subAreaHelper.js
CMS-695
- Get sub area dates from `parkFeatureDate` and `parkOperationSubAreaDate` collections through Strapi API, not GraphQL so that editors can update the dates without the Gatsby build
- Display sub area dates on the Park, Site, and Park operating dates page
- Prioritize dates from `parkFeatureDate` to display, if it doesn't exist display dates from `parkOperationSubAreaDate`
- TODO: Delete `parkOperationSubAreaDate` once we finish data migration from `parkOperationSubAreaDate` to `parkFeatureDate`
- TODO: Test it by publishing dates on DOOT ALPHA-DEV and check if the date is created/updated on Strapi/FE
> CMS-695: Display sub area dates from park feature date collection

- src/gatsby/src/components/park/subArea.js
- src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
- src/gatsby/src/styles/global.scss
- src/gatsby/src/styles/listPage.scss
- src/gatsby/src/styles/parks.scss
CMS-776
- Change wording winter season to winter rate
- Add a tooltip next to "Winter rate" on the park page
- Remove "Winter season" column on the park operating dates page
- If the winter rate dates are not available "Winter rate" will not be displayed
> CMS-776: Change wording winter season to winter rate

- src/cms/package-lock.json
- src/cms/package.json
CMS-747
- Minor update before major update
- Upgrade to strapi 4.25.20
- Upgrade some outdated libraries
- Fix some vulnerabilities
- Add a dependency based on the alert: https://github.com/bcgov/bcparks.ca/security/dependabot/268
> CMS-747: Upgrade to strapi 4.25.20

- .github/workflows/build-dev.yaml
CMS-747
- Update ubi 8 to 9 in build-dev based on our comments here: https://github.com/bcgov/bcparks.ca/pull/1606
> CMS-747: Update ubi 8 to 9 in build-dev

- src/gatsby/src/styles/search.scss
CMS-833
- Global styling was applied over the filter chip class, so added more specificity to the class
- In the `global.scss`
```
button.btn:not(.btn-link):not(.btn-tooltip) { ... }
```
> CMS-833: Add more specificity to filter chip class

- src/gatsby/src/components/megaMenu.js
CMS-807
The mobile menu was closing on touch devices when you did a vertical drag motion to scroll the menu. I don't have my phone set up to work with the debug console, so I might have to rely on Manuji to test this one in depth, but it looks like the cause of this bug was actually the `useEffect` that watches the screen size changing. When you scroll on a mobile browser, the URL bar pops up or disappears and that changes the _vertical_ viewport size, even if the "screen size" isn't really changing. To fix this, I updated the useEffect to only watch the `width` part of the screen size, so it won't close the menu when the address bar changes the effective viewport height.
> CMS-807: Update useEffect to only close menu on width change

- src/gatsby/src/utils/snowplowHelper.js
CMS-839
- As per the snowplow team's request, changed the filter structure from an array to an object in the custom event
From
```
{
"activities": [
"Canoeing"
],
"facilities": [
"Bike park",
"Boat launch"
]
}
```
To
```
{
"activities": "Canoeing",
"facilities": "Bike park, Boat launch"
}
```
> CMS-839: Change snowplow event filter structure

- src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
CMS-845
- Same implementation as the `parkHeader.js`
- If the park access status text is "Closed", the operating date text shouldn't be displayed
- Get the `isParkOpen` state from `parkAccessStatus.js`
- Change the `isParkOpen` state based on the status text and use it as a boolean to display/hide the date text
- TODO: Cherry-pick this commit and the land acknowledgment commit for the hot fix release
> CMS-845: Get a proper access status data on park operating dates page

- src/gatsby/src/templates/park.js
- src/gatsby/src/templates/site.js
- src/gatsby/src/utils/subAreaHelper.js
CMS-823
- Fix an issue where not all facilities are displayed on the park page
- If there was one facility, it was displayed, but if there were more than two facilities, some of them were not displayed
- It was because the function `combineFacilities` returned a result before the for loop finished, because one of the props was passed as an empty array first
- Update the facilities/camping data with `useState` and `useEffect` on the park/site page
> CMS-823: Fix facilities display issue

- src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
CMS-834
- Hide the park list if subareas are loading on the park operating dates page
- Display the loading bar if subareas are loading
- Display the error message if subareas fail to load
- Some code refactoring
> CMS-834: Hide park list if subareas are loading

- src/gatsby/src/components/park/about.js
CMS-901
- Fix an issue where two audios were overlapping, and the audio button doesn’t reset
- If the same audio was used in both "Heritage" and "History", `isActiveAudio` flag didn't have a proper value since its `audioId` was the same
- Add a specific location name to the audio button in the About section
> CMS-901: Add specific location name to audio button in about

- src/gatsby/src/components/park/about.js
- src/gatsby/src/components/park/parkHeader.js
- src/gatsby/src/components/park/parkOverview.js
CMS-870
- Display the audio button only if its URL exists
- Filter `audioClips` with location and URL
> CMS-870: Display audio button only if its url exists

- src/gatsby/src/components/advisories/advisoryLegend.js
CMS-920
- Update links on the active advisories page
- Update the existing Drive BC link title to DriveBC (no spaces)
- Add additional link next to the BCWS/River Forecast/DriveBC links, it’s for EmergencyInfoBC ([EmergencyInfoBC Home - EmergencyInfoBC](https://www.emergencyinfobc.gov.bc.ca/) )
> CMS-920: Update links on active advisories page

- .github/workflows/build-dev.yaml
- .github/workflows/deploy-alpha-test.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-test.yaml
CMS-828
This ticket updates the Github actions to use the built-in "GITHUB_TOKEN" instead of the personal access token we created.
Some details about GITHUB_TOKEN here: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
The personal access token we're using will be invalidated next month, and it's not viable to keep generating new tokens every 90 days when the new policy goes into effect. This GITHUB_TOKEN will hopefully work and never expire. It was recommended by folks in the Platform Services support chat.
(I haven't tested the actions yet, but maybe we can run actions on this branch before we merge?)
> CMS-828: Use GITHUB_TOKEN for repo actions

- src/gatsby/src/utils/parkDatesHelper.js
CMS-776
- Fix that `convertWinterRate` didn't handle multiple date ranges per year
- Split the ranges by comma, then for each range, split by dash, and append the year to both start and end
> CMS-776: Update convert winter rate dates function

- src/cms/src/api/park-feature-date/content-types/park-feature-date/schema.json
CMS-793
CMS-850
- Add "Full service and fees", "Backcountry registration", and  "First come, first served" as a feature date type so that DOOT can send dates with a specific date type
- No FE change at this moment, but these dates will be used on the Park page in the future
> CMS-850: Add 'First come, first served' as feature date type

- src/gatsby/src/templates/park.js
- src/gatsby/src/templates/site.js
- src/gatsby/src/utils/subAreaHelper.js
CMS-123
- Partial revert of https://github.com/bcgov/bcparks.ca/pull/1607
- Remove `isFacilityOpen`, `isActivityOpen`, and `isCampingOpen` from filtering
> CMS-823: Remove isFacilityOpen from filtering

- src/cms/src/api/park-feature-date/content-types/park-feature-date/schema.json
None
- Alpha needs to be rebased since I messed up the history 😅
- Created this PR because I couldn't push since the branch is protected
```
➜  strapi4 git:(alpha) git push --force-with-lease origin alpha
Enumerating objects: 18, done.
Counting objects: 100% (18/18), done.
Delta compression using up to 12 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (10/10), 1.51 KiB | 1.51 MiB/s, done.
Total 10 (delta 7), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (7/7), completed with 7 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/alpha.
remote: 
remote: - Cannot force-push to this branch
To github.com:bcgov/bcparks.ca.git
! [remote rejected]   alpha -> alpha (protected branch hook declined)
error: failed to push some …
```
> CMS-850: Add 'First come, first served' as feature date type (#1623)

- src/gatsby/src/templates/park.js
- src/gatsby/src/templates/site.js
CMS-1007
- Fix an issue where facilities and camping didn't get displayed on the Park page
- This useEffect was implemented in https://github.com/bcgov/bcparks.ca/pull/1613, but the condition `Object.keys(processedSubAreas).length > 0` is not needed, given that not all parks have sub-areas but parks can have facilities and camping
> CMS-1007: Fix facility and camping display issue

- .github/workflows/deploy-alpha-test.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-test.yaml
- .github/workflows/on-tag-push.yaml
CMS-1009 (Using the same ticket from #1636)
I'm deploying the changes from CMS-933 and CMS-1009 to the test environment for UAT, but the GitHub action "on tag push" fails right now because it's trying to tag the admin section image, which no longer exists. This is a quick update to remove the `admin-*` lines from the GitHub actions.
After this is merged into alpha, I'll merge into main and move the `v2.13.0` tag to this commit and deploy to test 👍 
Let me know if you have any concerns!
> CMS-1009: Remove admin images from GitHub actions

- src/cms/database/migrations/2025.09.16T00.00.27.park-feature.js
- src/cms/src/api/park-feature-type/content-types/park-feature-type/schema.json
- src/cms/src/api/park-feature/content-types/park-feature/schema.json
CMS-1254
- Update the park-feature fields
- Change `parkFeature` to `parkFeatureName`
- Add an inverse relation to `parkFeature` so that the editors can see them in the `parkFeatureType` collection 
- Update the migration file - we'll need to do this task again since `parkFeatureName` won't retain the value in `parkFeature`
> CMS-1154: Update park-feature fields

- src/cms/database/migrations/2025.09.05T00.00.24.park-area.js
- src/cms/database/migrations/2025.09.26T00.00.29.park-areas-group-sites-rename.js
- src/cms/src/api/park-area/content-types/park-area/schema.json
CMS-1203
Rename park_areas.group_site to park_areas.group_sites to fix error. Migrations 24 and 27 also need to be re-run to fix the data issue
> CMS-1203: Fixes from QA

- src/cms/src/api/park-area/content-types/park-area/schema.json
- src/cms/src/api/park-feature/content-types/park-feature/schema.json
- src/cms/src/api/park-gate/content-types/park-gate/schema.json
- src/cms/src/api/protected-area/content-types/protected-area/schema.json
CMS-1214
Added missing reciprocal relationships to park-gate to make it easier to find park-gate items in the Strapi admin interface
> CMS-1214: Add reciprocal relationships to park-gate
