bcgov/bcparks.ca

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/page/advisory/Advisory.js
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
src/admin/src/components/page/advisorySummary/AdvisorySummary.js
src/admin/src/components/page/error/Error.js
src/admin/src/routes/AppRouter.js
src/admin/src/utils/AuthorizedElement.js
src/admin/src/utils/AuthorizedFunction.js
src/admin/src/utils/PrivateRoute.js

Added role based authentication

---

src/admin/src/components/page/advisorySummary/AdvisorySummary.js
src/cms/data/functions/initialDataLoad.js
src/cms/data/functions/loadPar.js
src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json

- Fixed errors and temp strapi change to load data

Fixed errors and temp strapi change to load data

---

src/cms/data/functions/initialDataLoad.js
src/cms/data/functions/loadPar.js

Reverted temp fix

---

src/cms/data/functions/initialDataLoad.js
src/cms/data/functions/loadPar.js

Revert "Reverted temp fix"

---

src/cms/config/database.js
src/middleware/Startup.cs

- Fix to resolve knex timeout and removed cors

Fix to resolve knex timeout and removed cors

---

src/cms/data/functions/initialDataLoad.js
src/cms/data/functions/loadPar.js

Revert "Revert "Reverted temp fix""

---

src/cms/config/database.js
src/cms/data/functions/initialDataLoad.js
src/cms/package.json

Fix for knex timeout

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/routes/AppRouter.js
src/cms/data/functions/initialDataLoad.js

Code clean up

---

src/cms/data/functions/initialDataLoad.js
src/cms/data/functions/loadPar.js

Temp fix to be reverted

---

src/cms/data/functions/initialDataLoad.js
src/cms/data/functions/loadPar.js

Revert "Temp fix to be reverted"

---

src/cms/api/park-activity/models/park-activity.js
src/cms/api/park-activity/models/park-activity.settings.json
src/cms/api/park-facility/models/park-facility.js
src/cms/api/park-facility/models/park-facility.settings.json
src/cms/api/protected-area/custom/protected-area-status.js
src/cms/data/functions/loadOtherData.js

- activity and facility load changes
- set default values for activity and facility names
- add more facility and activity data on park status view

changes for activity and facility

---

src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

- handle null values for advisory status

handle null advisory status

---

src/admin/src/components/page/about/About.js
src/admin/src/components/page/about/About.stories.js
src/admin/src/components/page/about/About.test.js
src/admin/src/routes/AppRouter.js

- about page with version and last updated info

about page

---

src/cms/data/functions/initialDataLoad.js
src/cms/data/functions/loadOtherData.js
src/cms/data/functions/loadPar.js
src/cms/data/functions/loadPermissions.js
src/cms/data/functions/loadUtils.js

CMS data load improvements

---

docker-compose.yml

Added CMS dependency to staff app

---

src/cms/api/management-area/documentation/1.0.0/management-area.json
src/cms/api/park-activity/models/park-activity.settings.json
src/cms/api/park-facility/models/park-facility.settings.json
src/cms/api/park-name-type/config/routes.json
src/cms/api/park-name-type/controllers/park-name-type.js
src/cms/api/park-name-type/models/park-name-type.js
src/cms/api/park-name-type/models/park-name-type.settings.json
src/cms/api/park-name-type/services/park-name-type.js
src/cms/api/park-name/config/routes.json
src/cms/api/park-name/controllers/park-name.js
src/cms/api/park-name/models/park-name.js
src/cms/api/park-name/models/park-name.settings.json
src/cms/api/park-name/services/park-name.js
src/cms/api/protected-area/documentation/1.0.0/protected-area.json
src/cms/api/protected-area/models/protected-area.settings.json
src/cms/api/public-advisory/documentation/1.0.0/public-advisory.json
src/cms/api/site/documentation/1.0.0/site.json
src/cms/data/functions/initialDataLoad.js
src/cms/data/functions/loadOtherData.js
src/cms/data/park-name-type.json
src/cms/data/park-name.json
src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json

- BC-230 Load Park Names (Legal, Escaped, Phonetic, Basic, Alias, Historic)

load park names

---

src/admin/src/components/page/about/About.js

- change version to check if openshift is updating

front-end version check

---

src/admin/src/components/page/advisorySummary/AdvisorySummary.js
src/admin/src/utils/AdvisoryUtils.js
src/cms/config/middleware.js

Added cors settings and minor fixes

---

src/cms/config/middleware.js

Added cors settings

---

src/cms/api/protected-area/custom/protected-area-names.js
src/cms/data/functions/loadPermissions.js

BC 231 - Create Park Names API view

park names custom view

---

src/admin/src/components/page/about/About.js
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

- Minor advisory dashboard changes:
- make row clickable
- limit park dropdown select to 20 rows for performance improvement, user can type in values to search more

Ab advisory dashboard

---

src/cms/data/functions/loadOtherData.js

- firezone variable name bug fix

Ab load other data bug fix

---

src/admin/src/components/page/about/About.js
src/admin/src/components/page/cmsContents/CmsContents.css
src/admin/src/components/page/cmsContents/CmsContents.js
src/admin/src/components/page/cmsContents/CmsContents.stories.js
src/admin/src/components/page/cmsContents/CmsContents.test.js
src/admin/src/routes/AppRouter.js
src/cms/data/functions/loadPermissions.js

- BC 237 data validation - helper page

data validation helper page

---

src/admin/src/components/page/about/About.js
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

- test graphql load performance

test graphql load performance

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/page/about/About.js
src/admin/src/components/page/advisory/Advisory.js
src/admin/src/utils/AdvisoryUtils.js
src/admin/src/validators/AdvisoryValidator.js
src/cms/api/fire-zone/models/fire-zone.settings.json
src/cms/api/protected-area/documentation/1.0.0/protected-area.json
src/cms/api/protected-area/models/protected-area.settings.json
src/cms/api/public-advisory/documentation/1.0.0/public-advisory.json
src/cms/api/public-advisory/models/public-advisory.settings.json
src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json

Separated locations in Advisory form

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/page.css
src/admin/src/components/page/about/About.js
src/admin/src/components/page/advisory/Advisory.js
src/admin/src/components/page/advisorySummary/AdvisorySummary.css
src/admin/src/components/page/advisorySummary/AdvisorySummary.js
src/admin/src/components/page/home/Home.js
src/admin/src/validators/AdvisoryValidator.js

Advisory summary updates

---

src/admin/src/components/page/about/About.js
src/admin/src/components/page/advisory/Advisory.js
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
src/admin/src/components/page/advisorySummary/AdvisorySummary.js
src/admin/src/routes/AppRouter.js
src/admin/src/utils/AdvisoryUtil.js
src/admin/src/utils/CmsDataUtil.js

Added application state to store cms data

---

src/admin/src/components/page/about/About.js

version 1.0.0

---

src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

- change advisory dashboard record display limit to 500

change record display limit

---

docker-compose.yml
src/staging/.env.example
src/staging/Dockerfile
src/staging/gatsby-config.js

- rename gatsby/staging env var

rename staging env var

---

src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

- BC 268 Advisory Dashboard - add loading spinner

add loading spinner

---

src/cms/api/fire-centre/models/fire-centre.settings.json
src/cms/api/fire-zone/models/fire-zone.settings.json
src/cms/api/protected-area/documentation/1.0.0/protected-area.json
src/cms/api/protected-area/models/protected-area.settings.json
src/cms/api/public-advisory/documentation/1.0.0/public-advisory.json
src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json

- fix fire zone/protected area relationship

fire zone/protected area relationship

---

src/admin/src/components/page/advisory/Advisory.js
src/admin/src/utils/AdvisoryUtil.js
src/cms/api/management-area/documentation/1.0.0/management-area.json
src/cms/api/management-area/models/management-area.settings.json
src/cms/api/protected-area/documentation/1.0.0/protected-area.json
src/cms/api/protected-area/models/protected-area.settings.json
src/cms/api/public-advisory/documentation/1.0.0/public-advisory.json
src/cms/api/region/documentation/1.0.0/region.json
src/cms/api/section/documentation/1.0.0/section.json
src/cms/data/functions/loadPar.js
src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json

Management area relations

---

src/admin/src/components/page/advisory/Advisory.js
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.css
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
src/cms/data/advisory-status.json
src/cms/data/functions/loadPublicAdvisory.js
src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json

Removed Active status

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/page.css
src/admin/src/components/page/advisory/Advisory.js
src/admin/src/components/page/advisorySummary/AdvisorySummary.js
src/admin/src/components/page/error/Error.js
src/admin/src/validators/AdvisoryValidator.js

- BC-278
- BC-279
- BC-264
- BC-267

Advisory fixes

---

src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.css
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

- BC 277
- BC 282
- BC 283
- BC 284

advisory dashboard fixes

---

src/cms/api/management-area/config/routes.json
src/cms/api/management-area/controllers/management-area.js
src/cms/api/management-area/documentation/1.0.0/management-area.json
src/cms/api/protected-area/config/routes.json
src/cms/api/protected-area/documentation/1.0.0/protected-area.json
src/cms/api/region/config/routes.json
src/cms/api/region/controllers/region.js
src/cms/api/region/documentation/1.0.0/region.json
src/cms/api/section/config/routes.json
src/cms/api/section/controllers/section.js
src/cms/api/section/documentation/1.0.0/section.json
src/cms/api/site/config/routes.json
src/cms/api/site/documentation/1.0.0/site.json
src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json

Param name fixes

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/page/advisory/Advisory.js
src/admin/src/components/page/advisorySummary/AdvisorySummary.js
src/admin/src/utils/AdvisoryUtil.js

Added location removal logic

---

src/admin/src/components/composite/dataTable/DataTable.css
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
src/admin/src/components/page/advisorySummary/AdvisorySummary.js
src/admin/src/components/page/parkStatus/ParkStatus.css
src/admin/src/components/page/parkStatus/ParkStatus.js
src/cms/api/management-area/documentation/1.0.0/management-area.json
src/cms/api/protected-area/custom/protected-area-status.js
src/cms/api/protected-area/documentation/1.0.0/protected-area.json
src/cms/api/site/documentation/1.0.0/site.json
src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json

- BC 75 Parks status - changes
- change the back button on advisory summary

park status changes

---

src/admin/src/components/page/advisorySummary/AdvisorySummary.js

Summary test url fix

---

src/admin/src/components/page/parkStatus/ParkStatus.js

- BC 75 - park status view layout, label, formatting changes

label changes

---

src/cms/data/functions/initialDataLoad.js
src/cms/data/functions/loadParkPhoto.js

- Park photo - load all data and thumbnails, full size images excluded from load.

load all thumbnails

---

src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.css
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

- BC 103 ability to see expired advisories
- BC 308 expiry tooltip

advisory dashboard changes

---

src/cms/data/link-type.json

- BC-299 change the Director’s Order link type to ‘Closure Order’

link type update

---

src/cms/api/park-activity/models/park-activity.settings.json
src/cms/api/park-facility/models/park-facility.settings.json
src/cms/api/protected-area/documentation/1.0.0/protected-area.json
src/cms/api/public-advisory/documentation/1.0.0/public-advisory.json
src/cms/api/site/documentation/1.0.0/site.json
src/cms/api/site/models/site.settings.json
src/cms/data/functions/loadPar.js
src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json

- BC 61 - Custom sites not in PAR
additional fields:
isUnofficialSite 
note

Ab par custom site

---

src/admin/src/components/page/parkStatus/ParkStatus.js
src/admin/src/utils/ExportPdfUtil.js

- park status - header and column name changes

header and column name changes

---

src/admin/src/components/page/parkSearch/ParkSearch.js

Dashboard fix

---

src/admin/src/components/composite/dataTable/DataTable.css
src/admin/src/components/composite/dataTable/DataTable.js
src/admin/src/components/page/advisory/Advisory.js
src/cms/data/link-type.json

Link type and css bug fix

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/composite/header/Header.js
src/admin/src/validators/AdvisoryValidator.js

Advisory form updates

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/page/advisory/Advisory.js
src/admin/src/components/page/advisorySummary/AdvisorySummary.js
src/admin/src/components/page/parkSearch/ParkSearch.js
src/admin/src/utils/AdvisoryUtil.js
src/admin/src/utils/LocationUtil.js

Add or remove sites with location select

---

src/admin/src/components/composite/dataTable/DataTable.js
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
src/admin/src/components/page/parkAccessStatus/ParkAccessStatus.js

- fix data table console errors

fix console errors

---

.github/workflows/main-build.yml

Added env var

---

src/cms/config/plugins.js

Env update

---

src/cms/config/plugins.js

Revert "Env update"

---

.github/workflows/main-build.yml

Revert "Added env var"

---

src/admin/src/components/page/advisory/Advisory.js
src/cms/api/fire-ban-prohibition/models/fire-ban-prohibition.settings.json
src/cms/api/protected-area/custom/protected-area-status.js
src/cms/api/public-advisory-audit/models/public-advisory-audit.js
src/cms/config/functions/cron.js
src/cms/data/functions/initialDataLoad.js
src/cms/data/functions/loadOtherData.js
src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json

- BC-328 strapi/cms  publish/unpublished advisory cron job
- handle null values for wildfire service ban load & page access status
- initial data load - load sequence re-order 

Ab cms cron

---

src/admin/src/components/page/advisory/Advisory.js
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
src/admin/src/components/page/advisorySummary/AdvisorySummary.js
src/cms/data/functions/loadPermissions.js
src/middleware/Controllers/ApiController.cs

- BC 330 Provide a secure API endpoint for the PublicAdvisoryAudit collection

secure advisory audit endpoint

---

src/cms/data/functions/loadParkPhoto.js

- Park photo - delete download files

delete download file

---

src/admin/src/components/page/appDashboard/AppDashboard.js
src/admin/src/validators/AdvisoryValidator.js

Staff portal fixes

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.css
src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/page/advisory/Advisory.js
src/admin/src/utils/CmsDataUtil.js
src/cms/data/functions/initialDataLoad.js
src/cms/data/functions/loadOtherData.js
src/cms/data/standard-message.json
src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json

Ab standard message

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.css
src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/composite/advisoryHistory/AdvisoryHistory.css
src/admin/src/components/composite/advisoryHistory/AdvisoryHistory.js
src/admin/src/components/composite/advisoryHistory/AdvisoryHistory.stories.js
src/admin/src/components/composite/advisoryHistory/AdvisoryHistory.test.js
src/admin/src/components/composite/advisorySummaryView/AdvisorySummaryView.js
src/admin/src/components/composite/advisorySummaryView/AdvisorySummaryView.stories.js
src/admin/src/components/composite/advisorySummaryView/AdvisorySummaryView.test.js
src/admin/src/components/composite/header/Header.css
src/admin/src/components/page/advisory/Advisory.js
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
src/admin/src/components/page/advisorySummary/AdvisorySummary.css
src/admin/src/components/page/advisorySummary/AdvisorySummary.js
src/admin/src/components/page/parkAccessStatus/ParkAccessStatus.js
src/admin/src/components/page/parkInfo/ParkInfo.js
src/admin/src/components/page/parkSearch/ParkSearch.js
src/admin/src/utils/CmsDataUtil.js
src/cms/api/public-advisory-audit/config/routes.json
src/cms/api/public-advisory-audit/controllers/public-advisory-audit.js
src/cms/api/public-advisory/config/routes.json
src/cms/api/public-advisory/controllers/public-advisory.js
src/cms/api/public-advisory/documentation/1.0.0/public-advisory.json
src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json
src/middleware/Controllers/ApiController.cs

Advisory audit updates

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/page/advisory/Advisory.js
src/cms/api/public-advisory-audit/models/public-advisory-audit.settings.json
src/cms/api/public-advisory/documentation/1.0.0/public-advisory.json
src/cms/api/public-advisory/models/public-advisory.settings.json
src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json

- BC 301 - revisions to standard message

revisions standard message

---

src/cms/api/public-advisory/controllers/public-advisory.js

- BC 301 - append standard message to description on the public advisory api

add standard message to api

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/composite/advisoryHistory/AdvisoryHistory.js
src/cms/api/public-advisory-audit/controllers/public-advisory-audit.js

Audit history ui changes

---

src/cms/api/public-advisory-audit/models/public-advisory-audit.js
src/cms/api/public-advisory/controllers/public-advisory.js
src/cms/config/functions/cron.js

- BC-293 - advisory audit trail

advisory audit trail

---

src/admin/src/components/page/advisory/Advisory.js
src/cms/api/public-advisory-audit/controllers/public-advisory-audit.js

Fixed sort order

---

src/admin/src/components/composite/advisoryHistory/AdvisoryHistory.js

Duplicate key fix

---

src/admin/src/components/composite/advisoryHistory/AdvisoryHistory.js
src/admin/src/utils/AppUtil.js
src/cms/api/public-advisory-audit/controllers/public-advisory-audit.js

Date sort compare

---

src/cms/api/management-area/documentation/1.0.0/management-area.json
src/cms/api/protected-area/documentation/1.0.0/protected-area.json
src/cms/api/protected-area/models/protected-area.settings.json
src/cms/api/public-advisory/documentation/1.0.0/public-advisory.json
src/cms/api/site/documentation/1.0.0/site.json
src/cms/config/functions/cron.js
src/cms/data/functions/loadPar.js
src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json

- BC-337 Load park details and par model changes

model change and load park details

---

src/admin/src/components/composite/advisorySummaryView/AdvisorySummaryView.js
src/admin/src/components/page/advisorySummary/AdvisorySummary.js

Add standard message to summary

---

src/admin/src/index.js

Added bootstrap theme

---

src/staging/src/components/mainSearch.js
src/staging/src/styles/search.scss

Fixed select options

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/composite/advisorySummaryView/AdvisorySummaryView.js
src/admin/src/components/page/advisory/Advisory.js
src/admin/src/components/page/advisorySummary/AdvisorySummary.js

Code clean up and fixes

---

src/staging/gatsby-config.js

- Test if removing the business-hours will fix the gatsby load issue

remove business hours

---

src/admin/src/index.js
src/cms/data/functions/loadPar.js
src/cms/data/functions/loadParkPhoto.js
src/staging/gatsby-config.js
src/staging/src/components/park/about.js
src/staging/src/components/park/accessibilityDetails.js
src/staging/src/components/park/advisory.js
src/staging/src/components/park/advisoryDetails.js
src/staging/src/components/park/campfireBan.js
src/staging/src/components/park/campingDetails.js
src/staging/src/components/park/heading.js
src/staging/src/components/park/htmlContent.js
src/staging/src/components/park/mapLocation.js
src/staging/src/components/park/menu.js
src/staging/src/components/park/parkAccessStatus.js
src/staging/src/components/park/parkActivity.js
src/staging/src/components/park/parkFacility.js
src/staging/src/components/park/parkHeader.js
src/staging/src/components/park/parkInfo.js
src/staging/src/components/park/parkMapDetails.js
src/staging/src/components/park/parkMenu.js
src/staging/src/components/park/parkOverview.js
src/staging/src/components/park/parkPhoto.js
src/staging/src/components/park/parkStatus.js
src/staging/src/components/park/reconciliation.js
src/staging/src/components/park/showLessText.js
src/staging/src/components/park/showMoreText.js
src/staging/src/pages/parks.js
src/staging/src/templates/parkTemplate.css
src/staging/src/templates/parkTemplate.js

- BC 341 Parks Page - more layout changes

Ab gatsby park page v2

---

src/staging/Dockerfile

Updated the "setfacl -dRm u:default:rwx /opt/app-root/src/public" command to include future files and folders

Updated ACL

---

src/cms/data/functions/initialDataLoad.js

Adding missed reference for media load.

---

src/staging/package.json

Updated gatsby sass plugin version

---

infrastructure/airflow-openshift/.gitignore
infrastructure/airflow-openshift/AirflowTemplate.yml
infrastructure/airflow-openshift/README.md
infrastructure/airflow-openshift/sample_dags/Branched_S3.py
infrastructure/airflow-openshift/sample_dags/collect_hourly_data_from_api.py
infrastructure/airflow-openshift/sample_dags/email_on_failure.py

Adding Airflow Infra and reducing resource limits

---

src/cms/api/activity-type/models/activity-type.settings.json
src/cms/api/facility-type/models/facility-type.settings.json
src/cms/api/management-area/documentation/1.0.0/management-area.json
src/cms/api/protected-area/documentation/1.0.0/protected-area.json
src/cms/api/protected-area/models/protected-area.settings.json
src/cms/api/public-advisory/documentation/1.0.0/public-advisory.json
src/cms/api/site/documentation/1.0.0/site.json
src/cms/data/functions/loadPar.js
src/cms/data/functions/loadParkPhoto.js
src/cms/extensions/documentation/documentation/1.0.0/full_documentation.json

- BC 413 load park details
- add isCamping field to activity and facility types

Ab load park details

---

infrastructure/bcparks-app.yml

cms-pvc-automation

---

src/staging/src/components/park/parkOverview.js
src/staging/src/pages/park-search.js

Updated case sensitive references

---

src/staging/src/components/park/campingDetails.js
src/staging/src/components/park/parkActivity.js
src/staging/src/components/park/parkFacility.js
src/staging/src/pages/publicAdvisory.js
src/staging/src/templates/parkTemplate.css
src/staging/src/templates/parkTemplate.js

layout changes

---

src/staging/package.json

- add react-material-ui-carousel

missing package

---

src/cms/data/functions/loadPar.js
src/staging/src/pages/publicAdvisory.js
src/staging/src/templates/parkTemplate.js

- bootstrap parks url and some default values
- public advisory layout changes

Ab more layout

---

src/staging/src/components/search/main-search.js
src/staging/src/pages/park-search.js
src/staging/src/styles/search.scss

Revert "Elastic search integration and layout of search results - Waiting for elastic search in OS"

---

src/cms/config/plugins.js
src/staging/src/components/park/advisory.js
src/staging/src/components/park/advisoryDetails.js
src/staging/src/components/park/campingDetails.js
src/staging/src/components/park/parkAccessStatus.js
src/staging/src/components/park/parkActivity.js
src/staging/src/components/park/parkFacility.js
src/staging/src/components/park/parkHeader.js
src/staging/src/components/park/parkMenu.js
src/staging/src/components/park/parkOverview.js
src/staging/src/components/park/parkPhotoGallery.js
src/staging/src/components/search/main-search.js
src/staging/src/pages/park-search.js
src/staging/src/styles/search.scss
src/staging/src/templates/parkTemplate.css
src/staging/src/templates/parkTemplate.js

Park page layout updates

---

src/staging/gatsby-node.js

NOBUG: Adding back no limit

---

src/cms/api/activity-type/models/activity-type.settings.json
src/cms/api/facility-type/models/facility-type.settings.json
src/cms/api/protected-area/models/protected-area.settings.json

This PR reverts some bad model changes that were caused by a bad merge.  The missing fields are preventing proper data loads.

NOBUG: Revert bad model changes resulted from a bad merge

---

src/staging/gatsby-node.js

- BC-496 additional fix for build issue caused by arcgis module inclusion
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] No

BC-496 Gatsby Build error fix for arcgis module

---

src/cms/extensions/users-permissions/config/policies/permissions.js
src/cms/extensions/users-permissions/services/jwt.js
src/cms/package.json

- BC-497 https://bcdevex.atlassian.net/jira/software/projects/BC/boards/6/backlog?selectedIssue=BC-489 "Protect Data in Strapi"
- [x ] New feature (non-breaking change which adds functionality)

Keycloak strapi

---

infrastructure/helm/bcparks/values-test.yaml

Just updating Helm values file for test environment.

NOBUG: Update TEST deployment image tags

---

src/cms/data/park-urls.json

Added three park URLs and fixed some character errors

---

infrastructure/helm/bcparks/templates/cms/cms-deployment.yaml
infrastructure/helm/bcparks/values.yaml
src/cms/config/plugins.js
src/cms/package.json

- Added working email config to Strapi
- Note you'll need to be on VPN to test this locally

NOBUG: Add Strapi email config using nodemailer

---

.github/workflows/deploy-prod.yaml
.github/workflows/deploy-test.yaml

https://bcdevex.atlassian.net/browse/BC-487
This PR adds Github workflows for performing Test and Prod image promotions.
- Test environment will be triggered when a git tag in the form of `v[0-9].[0-9].[0-9]-rc` is pushed
- Prod environment will be triggered when a git tag in the form of `v[0-9].[0-9].[0-9]` is pushed

BC-487 Add Test and Prod promotion workflow

---

src/staging/package.json
src/staging/src/components/search/searchFilter.js
src/staging/src/pages/explore.js
src/staging/src/styles/search.scss

Set width for search filter dialog

---

.github/workflows/README.md
infrastructure/helm/README.md

https://bcdevex.atlassian.net/browse/BC-487
Quick documentation for Helm and pipeline

BC-487 Quick documentation for Helm and pipeline

---

src/kong/public-documentation.json
src/kong/public-prod.yaml
src/kong/public-test.yaml

Kong was referring to an old service name that appears to have been renamed.
- [x ] Bug fix (non-breaking change which fixes an issue)

Updated the bcparks-cms service name

---

infrastructure/helm/bcparks/templates/_helpers.tpl
infrastructure/helm/bcparks/templates/backup/backup-configmap.yaml
infrastructure/helm/bcparks/templates/backup/backup-cronjob.yaml
infrastructure/helm/bcparks/templates/backup/backup-pvc.yaml
infrastructure/helm/bcparks/templates/cms/cms-deployment.yaml
infrastructure/helm/bcparks/templates/cms/cms-pvc.yaml
infrastructure/helm/bcparks/templates/patroni/patroni-role.yaml
infrastructure/helm/bcparks/templates/patroni/patroni-rolebinding.yaml
infrastructure/helm/bcparks/templates/patroni/patroni-service-account.yaml
infrastructure/helm/bcparks/templates/patroni/patroni-service.yaml
infrastructure/helm/bcparks/templates/patroni/patroni-statefulset.yaml
infrastructure/helm/bcparks/templates/pgbouncer/pgbouncer-deployment.yaml
infrastructure/helm/bcparks/templates/pgbouncer/pgbouncer-service.yaml
infrastructure/helm/bcparks/templates/secrets/mariadb-secrets.yaml
infrastructure/helm/bcparks/templates/secrets/patroni-secret.yaml
infrastructure/helm/bcparks/templates/secrets/postgres-secret.yaml
infrastructure/helm/bcparks/values-prod.yaml
infrastructure/helm/bcparks/values-test.yaml
infrastructure/helm/bcparks/values.yaml

https://bcparksdigital.atlassian.net/browse/BRS-174
https://bcparksdigital.atlassian.net/browse/BRS-231
- Added HA Patroni cluster
- Added Postgres backup container

BRS-174, BRS-231 Add Patroni and Backup Container

---

src/cms/api/protected-area/custom/protected-area-status.js

Fixes dev setup with current data returned by the API

NOBUG: handle null in protected area

---

src/staging/src/styles/parks.scss

Flex is not appropriate for all anchors

BRS-282: fix linebreaks in html content

---

.github/pull_request_template.md

Most sections of the old template aren't really useful anymore.

NOBUG: simplify PR template

---

README.md

Update README links. Also remove outdated instructions that don't work anymore. We
should add dev setup instructions at some point.
Documentation

NOBUG: update readme links

---

infrastructure/helm/README.md
infrastructure/helm/bcparks/templates/sysdig/sysdig-team.yml
infrastructure/helm/bcparks/values.yaml

BRS-202
https://bcparksdigital.atlassian.net/browse/BRS-202
Initial sysdig setup as per https://developer.gov.bc.ca/OpenShift-User-Guide-to-Creating-and-Using-a-Sysdig-Team-for-Monitoring

BRS-202: initial sysdig setup

---

src/cms/data/functions/loadPar.js
src/cms/data/park-details.json

BRS-182
https://bcparksdigital.atlassian.net/browse/BRS-182
Fix orcs import errors by correcting bad data and creating new rows for areas that aren't present in PAR. All of these cases are parks that are no longer BC Parks (now administered by a different body), but we will need a placeholder page on the site.

BRS-182: fix orcs import errors

---

src/staging/src/pages/explore.js

BRS-368
https://bcparksdigital.atlassian.net/browse/BRS-368
* fix search sort order
* use id from strapi instead of stripping text out of generated id

BRS-368: fix search sort order

---

src/static-landing/index.html

BRS-327 
https://bcparksdigital.atlassian.net/browse/BRS-327 
Landing page minor text change

BRS-327 Landing page minor text change

---

src/static-landing/css/style.css

Fix small for right side padding issue for certain screen sizes

NOBUG: Fix content right side padding

---

.github/workflows/deploy-prod.yaml
.github/workflows/deploy-test.yaml

BRS-342 
https://bcparksdigital.atlassian.net/browse/BRS-342 
Add image tagging to test and prod for beta landing page

BRS-342 Update landing test and prod deploys

---

src/staging/Caddyfile
src/staging/src/pages/404.js
src/staging/src/styles/404.scss

BRS-320
https://bcparksdigital.atlassian.net/browse/BRS-320
Adding 404 catch-all page to bcparks-staging.

BRS-320 add 404 page

---

src/static-landing/index.html

Jira Ticket:
BRS-327 
Jira Ticket URL:
https://bcparksdigital.atlassian.net/browse/BRS-327?focusedCommentId=10634 
Description:
Minor content update

BRS-327 Minor content update for static beta landing page

---

src/staging/src/components/search/mainSearch.js
src/staging/src/pages/alerts.js
src/staging/src/pages/explore.js

BRS-304 
https://bcparksdigital.atlassian.net/browse/BRS-304 
- Add message to indicate there are limited parks in beta
- See Jira for DML to disable all parks except top 10

BRS-304 Add message to indicate there are limited parks in beta

---

src/static-landing/css/style.css
src/static-landing/index.html

BRS-327 
https://bcparksdigital.atlassian.net/browse/BRS-327?focusedCommentId=10670
More beta landing content update

BRS-327 More beta landing content update

---

src/static-landing/index.html

BRS-327
https://bcparksdigital.atlassian.net/browse/BRS-327
Content updates

BRS-327: content updates

---

src/static-landing/index.html

BRS-327
https://bcparksdigital.atlassian.net/browse/BRS-327
Updated button wording

BRS-327: updated learn more wording

---

src/static-landing/index.html

BRS-327
https://bcparksdigital.atlassian.net/browse/BRS-327
Fix typo

BRS-327: fix typo

---

src/staging/src/pages/explore.js

BRS-315
https://bcparksdigital.atlassian.net/browse/BRS-315
This ticket includes changes to the parks filtering UI per BRS-315. To lessen delivery time of this ticket, recently-obsolete material-ui components were re-used (links, icons). These can be easily replaced by bootstrap components in a future ticket once such bootstrap components are created. 
The remaining BRS-315 UI updates will come in a future ticket.

BRS-315 part I: filter UI updates

---

src/admin/README.md
src/cms/README.md
src/staging/README.md

Updating readmes for cms and staging.

NOBUG: Updating readmes for cms and staging

---

README.md
src/staging/src/styles/cmsSnippets/advisoryLink.scss

BRS-123
https://bcparksdigital.atlassian.net/browse/BRS-123
Updated root README to include guidelines for styling

BRS-316 draft of styling readme

---

src/staging/src/components/search/searchFilter.js
src/staging/src/pages/explore.js
src/staging/src/styles/search.scss

BRS-315
https://bcparksdigital.atlassian.net/browse/BRS-315
Buttons, fonts, spacing and colours updated to match Figma designs. Popular filter is currently hidden on mobile due to issues with code duplication. 
BRS-315: Minor updates to spacing and colours to match Figma designs
BRS-315: Sort dropdown removed and filter column aligned with top of search results
BRS-315: Sort dropdown removed from mobile popup to match desktop version
BRS-315: Mobile Popular filter populated with filters, general file cleanup
BRS-315: Popular filters hidden on mobile, functionality partially built out but not 100% completed
BRS-315: Minor css update to reflect new Figma design for mobile.

BRS-315: UI changes to Park Search

---

src/staging/src/components/header.js

BRS-366
https://bcparksdigital.atlassian.net/browse/BRS-366
Add link for beta page in header.

BRS-366: Adding link for beta page.

---

src/staging/src/components/header.js

BRS-366
https://bcparksdigital.atlassian.net/browse/BRS-366
Update wording.

BRS-366: Update wording

---

src/staging/src/components/header.js

BRS-366
https://bcparksdigital.atlassian.net/browse/BRS-366
Update link.

BRS-366: Update beta link.

---

src/staging/src/components/pageContent/linkCard.js
src/staging/src/pages/index.js
src/staging/src/styles/pageContent/linkCard.scss

BRS-409
https://bcparksdigital.atlassian.net/browse/BRS-409
Implement footer variation of LinkCard component
Implemented for Reconciliation page, content updates are detailed in ticket
Line break changes in linkCard.scss and index.js are unintentional but harmless

BRS-409 footer link cards implemented

---

.github/workflows/build-public.yaml

Fixed an issue where the public build workflow isn't accepting `prod` as input

NOBUG: Fix public build workflow

---

src/staging/src/components/search/noSearchResults.js
src/staging/src/pages/explore.js
src/staging/src/styles/search.scss

BRS-315
https://bcparksdigital.atlassian.net/browse/BRS-315
filter and search buttons swapped on mobile, filter design updated, headers edited to reflect figma designs, text bolded to reflect figma designs, not-found text and design edited
BRS-315: no results found message moved into its own component
BRS-315: now shows 0 results found instead of blank text for header
BRS-315: minor styling update and filters set to be open by default

BRS-315: Revisions

---

src/staging/src/pages/intro.js

Prevent build fail when intro page data is missing in CMS or unpublished

NOBUG: Prevent build fail when intro page data is missing

---

src/staging/src/components/park/parkHeader.js

BRS-414
https://bcparksdigital.atlassian.net/browse/BRS-414
This ticket changes the 'Book a Campsite' button link on parks with `hasReservation=true` to navigate to `http://camping.bcparks.ca` where they are currently being redirected to `bcparks.ca/reserve`. 
A link starting with `https` will not currently work as it appears https forwarding has not yet been set up.

BRS-414 Book a Campsite links out to new URL

---

src/staging/src/pages/explore.js

BRS-441
https://bcparksdigital.atlassian.net/browse/BRS-441
Minor bug where previously the user was unable to select multiple facility filters on the Find a Park page.

BRS-441 select multiple facilities on find a park

---

src/cms/data/functions/loadParkPhoto.js

Fields were removed in #279, so we don't need to download all the photos anymore

NOBUG: remove photo upload from initial data seed

---

src/staging/src/components/megaMenu/desktopMenu.js
src/staging/src/components/megaMenu/mobileMenu.js
src/staging/src/components/park/campingDetails.js

BRS-446
https://bcparksdigital.atlassian.net/browse/BRS-446
Update book a campsite button.
I don't understand why there are 3 mobile buttons, but this doesn't seem like the place to update that layout.

BRS-446: update campsite booking URL

---

src/staging/src/components/advisories/advisoryCard.js
src/staging/src/pages/alerts.js

BRS-410
https://bcparksdigital.atlassian.net/browse/BRS-410
Only show advisories for published parks on the alerts page. There was an existing strapi filter, so API behaviour hasn't changed.

BRS-410: filter out published alerts

---

src/static-landing/index.html

BRS-454
https://bcparksdigital.atlassian.net/browse/BRS-454
Text update on beta landing page.

BRS-454: Text update on beta landing page.

---

src/staging/src/components/search/mainSearch.js

BRS-456
https://bcparksdigital.atlassian.net/browse/BRS-456
Text on homepage updated to "Find a park"

BRS-456: text on homepage updated to Find a park

---

src/staging/src/templates/park.js

BRS-431
https://bcparksdigital.atlassian.net/browse/BRS-431
Added missing reference for floating menu

BRS-431 Floating park menu, added missing ref

---

src/staging/src/components/betaBanner.js
src/staging/src/components/header.js
src/staging/src/pages/404.js

BRS-458
https://bcparksdigital.atlassian.net/browse/BRS-458
Updated text and links to match ticket. Changed Beta Banner into a component to remove duplicate code on 404 page.

BRS-458: updated text on beta banner and componentized banner

---

src/staging/src/components/betaBanner.js

…. Unused style removed.
BRS-458
https://bcparksdigital.atlassian.net/browse/BRS-458
Old link colour didn't meet contrast standards. Links updated to be underlined and the same colour as the rest of the text.

BRS-458-2: Update to link text colour

---

src/staging/package.json
src/staging/src/components/advisories/advisoryCard.js
src/staging/src/components/advisories/advisoryFilter.js
src/staging/src/components/advisories/advisoryList.js
src/staging/src/styles/cmsSnippets/advisoryCard.scss

BRS-395
https://bcparksdigital.atlassian.net/browse/BRS-395
This change is part of a series of updates to replace MUI Accordion components with bootstrap equivalents.
NOTE: this change adds the `react-bootstrap` package. There is a chance this package could conflict with the existing MUI package in unexpected ways.

BRS-395-1: replacing advisory page accordions with bootstrap

---

src/staging/src/components/advisories/advisoryCard.js
src/staging/src/components/park/advisoryDetails.js
src/staging/src/styles/cmsSnippets/advisoryDetails.scss

BRS-395
https://bcparksdigital.atlassian.net/browse/BRS-395
This change is part of a series of updates to replace MUI Accordion components with bootstrap equivalents.

BRS-395-2 replacing advisory details component with bootstrap

---

tools/syncdb/README.md
tools/syncdb/export-db.ps1
tools/syncdb/import-db.ps1

BRS-448
https://bcparksdigital.atlassian.net/browse/BRS-448
Copy db exports between envs using Postgresql and OpenShift rsync.
Written as PowerShell scripts for cross platform compatibility (hopefully 🤞). These are intended to be run locally by someone with access to all the required OpenShift projects.
Tested by copying test to dev using the following commands:
```
pwsh tools/syncdb/export-db.ps1 -Project 61d198-test -OutputPath ./
pwsh tools/syncdb/import-db.ps1 -Project 61d198-dev -InputPath ./db-export/
```

BRS-448: db import/export scripts

---

src/staging/src/components/megaMenu.js
src/staging/src/styles/megaMenu/megaMenu.scss

BRS-439 megamenu
BRS-392 sitemap
https://bcparksdigital.atlassian.net/browse/BRS-392
Fixing defect from branch BRS-439 and hiding page header for sitemap mode

BRS-439-2 hide header banner for sitemap

---

src/staging/src/styles/megaMenu/megaMenu.scss

BRS-470
https://bcparksdigital.atlassian.net/browse/BRS-470
Importing all of bootstrap resets some modified styles (e.g. link colour, buttons)

BRS-470: only import bootstrap mixins

---

src/cms/data/functions/initialDataLoad.js
src/cms/data/functions/loadActivityIcon.js
src/cms/data/functions/loadOtherData.js
src/cms/data/functions/loadPar.js
src/cms/data/functions/loadPermissions.js
src/cms/data/functions/loadPublicAdvisoryAudit.js
src/cms/data/functions/loadUtils.js

BRS-461
https://bcparksdigital.atlassian.net/browse/BRS-461
BRS-461: Fix promise handling.

BRS-461: Fix promise handling

---

src/staging/src/pages/404.js

BRS-467
https://bcparksdigital.atlassian.net/browse/BRS-467
It appears the BC Parks icon on the 404 page got blown up, possibly when bootstrap was introduced. This change restricts the max size of the icon.

BRS-467 404 page icon size

---

src/staging/src/components/megaMenu.js
src/staging/src/pages/sitemap.js
src/staging/src/styles/megaMenu/megaMenu.scss

BRS-439, BRS-392
https://bcparksdigital.atlassian.net/browse/BRS-392
- reduce font size for sitemap for desktop
- add breadcrumb (using MUI, breadcrumbs will be updated by another ticket)
- fix import of bootstrap mixins

BRS 439-2 site map font size

---

src/staging/__tests__/components/__snapshots__/footer.test.js.snap
src/staging/src/components/footer.js
src/staging/src/styles/_layout.scss
src/staging/src/styles/footer.scss
src/staging/src/styles/global.scss
src/staging/src/styles/staticContent1.scss

BRS-361
https://bcparksdigital.atlassian.net/browse/BRS-361
- Update footer links with correct text and urls (note that some links dead outside of prod)
- Convert MUI to Bootstrap, moved footer styles to own sheet, removed unused rules
- Updated jest screenshot

BRS-361 update footer

---

src/staging/src/styles/megaMenu/megaMenu.scss

BRS-474
https://bcparksdigital.atlassian.net/browse/BRS-474
-Update z index of megamenu to be higher than intro content (1000)
-Updated sitemap lowest level link color
-Note that prettier formatting changed many indents etc., only 3 lines substantially changed

BRS-474 megamenu z-index

---

src/cms/api/protected-area/services/protected-area.js
src/cms/config/functions/dbsetup.js

BRS-459
https://bcparksdigital.atlassian.net/browse/BRS-459
Add support for partial text matches (e.g. "Rath" for "Rathtrevor")
Also removes `isOpenToPublic` from API results as that has been replaced by displaying the access status text directly.

BRS-459: partial match on park name searches

---

src/staging/src/components/park/quickView.js
src/staging/src/pages/explore.js
src/staging/src/styles/search.scss

BRS-424: all sections added to QuickView component
BRS-424: styling and clean-up
BRS-424
https://bcparksdigital.atlassian.net/browse/BRS-424
Quick View on Mobile

BRS-424: Quick View component created

---

src/staging/src/components/park/advisoryDetails.js
src/staging/src/components/park/quickView.js
src/staging/src/pages/explore.js
src/staging/src/templates/park.js

BRS-466: Park page template updated to include id for advisories, id removed from advisory details component
BRS-466
https://bcparksdigital.atlassian.net/browse/BRS-466

BRS-466: Link to advisory details added.

---

src/staging/src/styles/global.scss

BRS-460
https://bcparksdigital.atlassian.net/browse/BRS-460
- added cms classes to wrap youtube embed tags to fill avail space
- see ticket for example for testing

BRS-460 add cms class for fullwidth youtube

---

src/cms/api/protected-area/services/protected-area.js

BRS-505
https://bcparksdigital.atlassian.net/browse/BRS-505
Matched on the wrong id previously, which was resulting in advisories being shown, but not the correct ones.

BRS-505: fix advisory lookup in search

---

src/staging/src/components/park/parkHeader.js
src/staging/src/templates/park.js

BRS-415
https://bcparksdigital.atlassian.net/browse/BRS-415
This change makes the 'book a daypass' button that appears on parks that have `hasDayUsePass = true` link out to https://reserve.bcparks.ca/dayuse/.

BRS-415 add get dayuse pass button if dayuse is available on a park

---

src/staging/Caddyfile
src/staging/src/components/park/mapLocation.js
src/staging/src/templates/park.js

BRS-473
https://bcparksdigital.atlassian.net/browse/BRS-473
This is a description.

BRS-473: redirect added to Caddyfile for /map, map on park pages now links to BC Parks Map

---

src/staging/Caddyfile
src/staging/src/components/park/mapLocation.js
src/staging/src/templates/park.js

Reverts bcgov/bcparks.ca#338
Issue with map not displaying.

Revert "BRS-473: redirect added to Caddyfile for /map, map on park pages now links to BC Parks Map"

---

src/staging/Caddyfile
src/staging/src/components/park/mapLocation.js
src/staging/src/templates/park.js

Reverts bcgov/bcparks.ca#341
Code is working for link and removal of map UI. Issue with map not displaying is unrelated.

Revert "Revert "BRS-473: redirect added to Caddyfile for /map, map on park pages now links to BC Parks Map""

---

src/staging/src/pages/explore.js

BRS-481
https://bcparksdigital.atlassian.net/browse/BRS-481
Updating the search box placeholder text from "Alice Park" to "Alice Lake Park"

BRS-481: update search placeholder text

---

src/staging/src/components/search/advisorySummary.js
src/staging/src/pages/explore.js

BRS-333
https://bcparksdigital.atlassian.net/browse/BRS-333
Update advisory text on search results with a generic counter for number of advisories active.
e.g.
The only thing that changes based on advisory details is now the icon, which changes colour based on the highest urgency advisory.

BRS-333: advisory summary text

---

src/kong/README.md

Update Kong README to help ease future updates. Hopefully a bit clearer.

NOBUG: update kong readme

---

src/cms/api/public-advisory/models/public-advisory.settings.json
src/cms/api/public-advisory/services/public-advisory.js
src/cms/config/functions/dbsetup.js
src/staging/src/components/advisories/advisoryFilter.js
src/staging/src/pages/alerts.js

BRS-338
https://bcparksdigital.atlassian.net/browse/BRS-338
Add fuzzy search & full text search to advisories.
Adds indexes and generated `search_text` column to the db, and update the public advisory services to handle search. Note that those methods only handle the filters we've manually implemented now - I tried to do it more generically but couldn't figure out how to make it work without re-implementing a lot of strapi.

BRS-338: improve advisory search

---

src/staging/package.json

BRS-547
https://bcparksdigital.atlassian.net/browse/BRS-547
Still can't repro the map load failure locally, but just want to test it out and see if it works on dev. The broken build is using 4.23.

BRS-547: try v4.22 of arcgis

---

src/cms/api/public-advisory/services/public-advisory.js

BRS-364
https://bcparksdigital.atlassian.net/browse/BRS-364
(this has been moved to https://bcparksdigital.atlassian.net/browse/BWT-192 but the branch name has not changed)
Fix for issue of not excluding parks with isDisplayed=false for "all" mode

BRS-364 fixed advisories api call

---

src/cms/api/menu/models/menu.settings.json
src/staging/src/components/megaMenu.js
src/staging/src/pages/alerts.js
src/staging/src/pages/explore.js
src/staging/src/pages/index.js
src/staging/src/pages/intro.js
src/staging/src/pages/sitemap.js
src/staging/src/styles/megaMenu/megaMenu.scss
src/staging/src/templates/park.js
src/staging/src/templates/staticContent1.js
src/staging/src/templates/staticLanding1.js

BRS-444 (BWT-166)
https://bcparksdigital.atlassian.net/browse/BWT-166
- Added ability to add image to each section for megamenu in desktop
- See ticket for details on adding images for testing purposes
- Note prettier formatting shows more edits than necessary

BRS-444 added image to megamenu

---

src/staging/gatsby-node.js

BRS-476
https://bcparksdigital.atlassian.net/browse/BRS-476
Adds new field in node def'n to deal with empty fields issue

BRS-476-fix fix for deploy

---

src/staging/gatsby-node.js

BRS-444
https://bcparksdigital.atlassian.net/browse/BRS-444
Missing an "s", apparently

BRS-444-fix

---

src/staging/src/components/park/quickView.js

BWT-175
https://bcparksdigital.atlassian.net/browse/BWT-175
Fix generic advisories text for quick view mode

BWT-175 fix generic advisories text for quick view mode

---

src/staging/src/components/park/parkDates.js

BWT-206
https://bcparksdigital.atlassian.net/browse/BWT-206
Include more notes and capacity counts to operations section, including in each subarea

BWT-206 update operation notes and dates

---

src/staging/src/components/pageContent/pageMenu.js
src/staging/src/components/park/advisoryDetails.js
src/staging/src/components/park/parkMapDetails.js
src/staging/src/components/park/parkOverview.js
src/staging/src/templates/park.js

BWT-188
https://bcparksdigital.atlassian.net/browse/BWT-188
Fix quick link menu item functionality

BWT-188 fix quick link menu item functionality

---

src/staging/src/styles/footer.scss
src/staging/src/styles/home.scss

BWT-190
https://bcparksdigital.atlassian.net/browse/BWT-190
Fix css spacing in footer menu links

BWT-190: fix css spacing in footer menu links

---

src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

BWT-130
https://bcparksdigital.atlassian.net/browse/BWT-130
Update advisories list count to fetch upto 1500 instead of 500 on staff portal

BWT-130: update advisories list count to fetch upto 1500 on staff portal

---

src/admin/src/components/page/advisory/Advisory.js
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

BWT-129
https://bcparksdigital.atlassian.net/browse/BWT-129
Fix delay in loading the advisories data on grid after update by updating "isLoading" flag to "isFetching" flag for useQuery.

BWT-129: fix delay in loading the advisories data on grid after update

---

src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

BWT-229
https://bcparksdigital.atlassian.net/browse/BWT-229
Preserve filters state on local storage for advisory dashboard

BWT-229: preserve filters state on localstorage for advisory dashboard

---

src/staging/src/components/advisories/advisoryFilter.js

BWT-134
https://bcparksdigital.atlassian.net/browse/BWT-134
Update advisory event types dropdown into autocomplete select

BWT-134: update advisory event types dropdown into autocomplete select

---

src/staging/src/components/park/reconciliation.js

BWT-235
https://bcparksdigital.atlassian.net/browse/BWT-235
Fix content rendering on parks page section about indigenous people.

BWT-235: fix content rendering on parks page section

---

src/cms/extensions/users-permissions/config/policies/permissions.js

BRS-679
https://bcparksdigital.atlassian.net/browse/BRS-679
This changes the KeyCloak token checking from realm roles => client roles.

BRS-674: BCParks Admin portal: client role implementation

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/composite/advisorySummaryView/AdvisorySummaryView.js
src/cms/extensions/users-permissions/config/policies/permissions.js
src/staging/src/components/advisories/advisoryFilter.js
src/staging/src/pages/alerts.js
src/staging/src/templates/park.js
src/staging/src/utils/advisoryHelper.js

BWT-134
https://bcparksdigital.atlassian.net/browse/BWT-134
List all advisory types in pulldown and make pulldown searchable

BWT-134: List all advisory types in pulldown and make pulldown searchable

---

src/admin/src/components/composite/advisorySummaryView/AdvisorySummaryView.js
src/staging/src/pages/alerts.js
src/staging/src/utils/advisoryHelper.js

BWT-259
https://bcparksdigital.atlassian.net/browse/BWT-259
Fix description and headline for html rendering
Fix promise all indexed response
Fix import error

BWT-259: fix description and headline for html rendering

---

src/staging/src/components/pageContent/pageMenu.js
src/staging/src/templates/staticContent1.js

BWT-244
https://bcparksdigital.atlassian.net/browse/BWT-244
Fix left menu visibility in mobile/desktop view

BWT-244: fix left menu visibility in mobile/desktop view

---

src/cms/api/park-access-status-cache/controllers/park-access-status-cache.js
src/cms/config/functions/cron.js

Adding limit to strapi call.

---

src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

BWT-292
https://bcparksdigital.atlassian.net/browse/BWT-292
Optimize performance of advisory dashboard on staff portal
- Load data once
- Fix data fetching due to react re-rendering

BWT-292: optimize performance of advisory dashboard on staff portal

---

src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

BWT-292
https://bcparksdigital.atlassian.net/browse/BWT-292
Addressed warnings

BWT-292: refactor by fixing warnings of dependency on useeffect

---

src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

BWT-252
https://bcparksdigital.atlassian.net/browse/BWT-252
Add regional filter on advisory dashboard to filter by region

BWT-252: add regional filter on advisory dashboard to filter by region

---

src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

BWT-285
https://bcparksdigital.atlassian.net/browse/BWT-285
Preserve filters on table and page level for advisory dashboard

BWT-285: preserve filters on table and page level for advisory dashboard

---

src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

BWT-285
https://bcparksdigital.atlassian.net/browse/BWT-285
Disable lint warning

BWT-285: disable lint warning

---

src/cms/config/functions/responses/404.js

None
None
This is a fix to address Strapi tests failing each time.

CM-00: hotfix to fix tests failing

---

README.md
src/cms/README.md
src/cms/plugins/wysiwyg/admin/src/components/CKEditor/README.md
src/staging/README.md

CM-105
https://bcparksdigital.atlassian.net/browse/CM-105
Updated readme files for the site to reflect changes since created, and to add more detail.

CM-105: updated readme files for the site

---

src/cms/api/page/models/page.settings.json
src/staging/gatsby-node.js
src/staging/src/templates/staticContent1.js
src/staging/src/templates/staticLanding1.js

CM-30
https://bcparksdigital.atlassian.net/browse/CM-30
Added a new field called Title at the Pages.

CM-30: added title field to page

---

src/staging/gatsby-node.js
src/staging/src/templates/staticContent1.js
src/staging/src/templates/staticLanding1.js

CM-30
https://bcparksdigital.atlassian.net/browse/CM-30
Roll back the gatsby change of [this PR](https://github.com/bcgov/bcparks.ca/pull/408) to fix the build error.

CM-30: added Title field on Strapi

---

src/cms/api/protected-area/controllers/protected-area.js
src/cms/api/protected-area/custom/protected-area-status.js

Jira Ticket:
Bwt 349
Jira Ticket URL:
https://bcparksdigital.atlassian.net/jira/software/projects/BWT/boards/5?assignee=633db6bb61dbef2805c1f25c&selectedIssue=BWT-349

Bwt 349: park-access-statuses API endpoint filter for accessStatus field

---

tools/json-data-cleanup/Converters/ConverterBase.cs
tools/json-data-cleanup/Deserialization/ParkActivityXRef.cs
tools/json-data-cleanup/Deserialization/ParkFacilityXRef.cs

CM-130
https://bcparksdigital.atlassian.net/browse/CM-130
Updated the data scrape cleanup  tool because some object names were changed in the JSON text.

CM-130: Updated scrape cleanup tool due to some changes in json

---

src/cms/scripts/publish-all.js

CM-127
https://bcparksdigital.atlassian.net/browse/CM-127
Created a node script to publish all parks on the dev environment.  This has already been copied to the CMS pod on OpenShift and run on dev, but I am keeping a copy as an example of how to bulk update parks in Strapi.

CM-127: publish all parks on the dev env to test performance

---

src/cms/data/functions/loadOtherData.js

CM-171
https://bcparksdigital.atlassian.net/browse/CM-171
Fixed import script to fix double-linking of ParkActivities and ParkFacilities

CM-171: Fix duplicated facilities and activities for parks with sites

---

src/cms/api/park-sub-page/config/routes.json
src/cms/api/park-sub-page/controllers/park-sub-page.js
src/cms/api/park-sub-page/models/park-sub-page.js
src/cms/api/park-sub-page/models/park-sub-page.settings.json
src/cms/api/park-sub-page/services/park-sub-page.js
src/cms/api/protected-area/models/protected-area.settings.json

CM-154
https://bcparksdigital.atlassian.net/browse/CM-154
Create park sub page collection in Strapi

CM-154: Create park sub page collection

---

src/staging/gatsby-config.js

CM-154
https://bcparksdigital.atlassian.net/browse/CM-154
Attempting to fix this build error: https://github.com/bcgov/bcparks.ca/actions/runs/3641878629

CM-154: Add park-sub-page in Gatsby

---

src/staging/gatsby-config.js
src/staging/gatsby-node.js
src/staging/package.json

None
None
Added node polyfill plugin to fix the build error
Ref: https://github.com/Richienb/node-polyfill-webpack-plugin

NOBUG: Add node polyfill plugin to fix the build error

---

src/cms/api/park-activity/models/park-activity.settings.json
src/cms/api/park-facility/models/park-facility.settings.json
src/cms/api/protected-area/models/protected-area.settings.json

CM-110
https://bcparksdigital.atlassian.net/browse/CM-110
Certain fields in the protectedArea collection type should be converted from plain text to rich text.

CM-110: changed certain protectedArea fields from text to richtext

---

src/cms/data/functions/loadParkSubpages.js
src/cms/data/functions/reimportData.js
src/cms/data/functions/seedData.js

CM-157
https://bcparksdigital.atlassian.net/browse/CM-157
Added code to import subpages into Strapi.

CM-157: Sub-page import

---

src/cms/data/functions/loadOtherData.js

CM-205
https://bcparksdigital.atlassian.net/browse/CM-205
Fixed a logic error that was causing many ParkActivity and ParkFacility records to not be associated with any ProtectedArea or Site.

CM-205: Fix missing activities and facilities in imported parks

---

src/staging/src/components/park/mapLocation.js
src/staging/src/templates/park.js

CM-186
https://bcparksdigital.atlassian.net/browse/CM-186
This ticket will restore basic functionality to the embedded arcgis maps on parks pages (scroll, zoom...) and should include a link below the map to the BC Gov ARCGIC instance, with the current map centred.

CM-186: restored arcgis UI features

---

src/cms/scripts/publish-all.js

CM-205
https://bcparksdigital.atlassian.net/browse/CM-205
Import the current Indigenous Reconciliation content block from legacy prod for all parks

CM-205: Bulk-update Indigenous Reconciliation content

---

src/cms/api/park-activity/models/park-activity.js
src/cms/api/park-facility/models/park-facility.js
src/cms/data/functions/loadOtherData.js
src/cms/data/functions/reimportData.js
src/cms/data/functions/seedData.js

CM-207
https://bcparksdigital.atlassian.net/browse/CM-207
Fixed errors in the import script that were causing activities and facilities for sites to be incorrectly linked.

CM-207: Some park pages missing the "Activities" & "Facilities" sections

---

src/cms/data/park-activity-xref.json
tools/legacy-scrape/scrape-tools/BCParks.ScrapeTools.JsonDataCleanup/Converters/ConverterBase.cs
tools/legacy-scrape/scrape-tools/BCParks.ScrapeTools.JsonDataCleanup/Converters/ParkActivityXRefConverter.cs

CM-232
https://bcparksdigital.atlassian.net/browse/CM-232
Append eBiking content to cycling content before import, to replicate the logic in https://bcparks.ca/_shared/scripts/park-info.js?v=?v=1670559869861

CM-232: e-biking information missing

---

src/cms/scripts/publish-all.js

CM-205
https://bcparksdigital.atlassian.net/browse/CM-205
Reverted an update to the indigenous reconciliation content based on comments from Rob in the ticket.  The text I was replacing was actually the newer copy.

CM-205: Revert the update to indigenous reconciliation content

---

src/staging/gatsby-node.js
src/staging/src/templates/site.js

CM-162
https://bcparksdigital.atlassian.net/browse/CM-162
Fix build error

CM-162: Fix build error

---

src/cms/data/park-activity-xref.json
tools/legacy-scrape/scrape-tools/BCParks.ScrapeTools.JsonDataCleanup/Converters/ParkActivityXRefConverter.cs

CM-241
https://bcparksdigital.atlassian.net/browse/CM-241
Updated the e-Biking content so there is now copy in both the e-Biking section and the Cycling section
Also added two CSS classes to cycling content so the automatically appended content can be easily recognized later by automated tools:
- cycling-ebike-allowed
- cycling-ebike-banned
There may also be other changes in the JSON file do to re-scraping and indigenous character enhancements.

CM-241: Updates to e-Biking content

---

src/cms/data/park-operation-sub-area-dates.json
src/cms/data/park-operation.json
tools/legacy-scrape/scrape-tools/BCParks.ScrapeTools.JsonDataCleanup/Converters/ParkOperationConverter.cs

CM-214
https://bcparksdigital.atlassian.net/browse/CM-214
As instructed by UX, I removed the generalNote from parkOperation records.  It contained a reference to a heading on the legacy site that no longer exisits.

CM-214: Don't import the generalNote for parkOperation records

---

src/cms/api/legacy-redirect/config/routes.json
src/cms/api/legacy-redirect/controllers/legacy-redirect.js
src/cms/api/legacy-redirect/models/legacy-redirect.js
src/cms/api/legacy-redirect/models/legacy-redirect.settings.json
src/cms/api/legacy-redirect/services/legacy-redirect.js
src/staging/gatsby-config.js

https://bcparksdigital.atlassian.net/jira/software/projects/CM/boards/11?assignee=633db6bb61dbef2805c1f25c&selectedIssue=CM-134

CM-134: Redirect and 404 handling

---

.github/workflows/build-public.yaml

NOBUG: get PROD content directly from Strapi (workaround for Kong)

---

src/staging/src/components/park/parkFacility.js

CM-213
https://bcparksdigital.atlassian.net/browse/CM-213
Changed the accordion open/close logic to the same as the one in `parkActivity.js`

CM-213: Display accessibility info in accordion

---

src/staging/src/components/park/parkDates.js

CM-242
https://bcparksdigital.atlassian.net/browse/CM-242
Striped out links from `subArea.facilityName` in `parkDates.js`

CM-242: Striped out links from parkDates

---

src/staging/gatsby-node.js

https://bcparksdigital.atlassian.net/jira/software/projects/CM/boards/11?assignee=633db6bb61dbef2805c1f25c&selectedIssue=CM-134

CM-134: Redirect and 404 handling, wrapped by try/catch 

---

src/staging/gatsby-node.js
src/staging/src/templates/parkSubPage.js

CM-266
https://bcparksdigital.atlassian.net/browse/CM-266
Added another query parameter `$protectedAreaSlug` for the `parkSubPage`

CM-266: Add protectedAreaSlug as a query parameter

---

src/cms/api/park-sub-page/models/park-sub-page.settings.json

CM-270
https://bcparksdigital.atlassian.net/browse/CM-270
Make a relation with `protectedArea` as a required field.

CM-270: Add required to a relation with protectedArea

---

src/staging/src/components/park/parkOverview.js

CM-202
https://bcparksdigital.atlassian.net/browse/CM-202
- Made the "Read more/less" link displayed when `parkOverview` element's height is more than 260px. 
- If it's less than 260px, the link won't be displayed.

CM-202: Fix read more toggle

---

src/cms/api/protected-area/services/protected-area.js

CM-200
https://bcparksdigital.atlassian.net/browse/CM-200
Made the search SQL query faster 
- don't search on all text anymore (just search on park names)
- reduced the number of columns being returned 
- eliminated some redundant search sorting columns

CMS-200: Made the search query faster

---

src/staging/src/components/park/about.js
src/staging/src/templates/park.js

CM-163
https://bcparksdigital.atlassian.net/browse/CM-163
- Added a fallback in case that `park.type` is null
- Added a visible condition for the Overview, the Operation, the Safety Info, and the Learn About section

CM-163: Add conditions for visible toggles

---

src/staging/src/templates/park.js

NOBUG: Fix type build error

---

src/cms/plugins/wysiwyg/admin/src/components/CKEditor/index.js

CM-285
https://bcparksdigital.atlassian.net/browse/CM-285
CKeditor was throwing an error if there was null content in a field from import. Added null check.

CM-285: null check for ckeditor component

---

src/staging/src/templates/park.js

No
No
Fixed a build error: https://github.com/bcgov/bcparks.ca/actions/runs/3849907473/jobs/6559443824

NOBUG: Fix build error - cannot read property 'Footer' of undefined

---

src/cms/api/page/models/page.settings.json
src/cms/api/park-sub-page/models/park-sub-page.settings.json
src/cms/api/protected-area/models/protected-area.settings.json
src/cms/api/site/models/site.settings.json

No
No
- Deleted the regex validation as it happens on PROD
- TODO: investigate the validation later

NOBUG: Fix validation error

---

src/cms/api/site/models/site.settings.json
src/staging/gatsby-node.js
src/staging/src/templates/site.js

CM-286
https://bcparksdigital.atlassian.net/browse/CM-286
- Added new field `isDisplayed` to `site`
- Added a filter condition to the query

CM-286: Add isDisplayed field to site

---

src/staging/src/components/park/parkAccessStatus.js
src/staging/src/components/park/parkHeader.js
src/staging/src/components/park/parkOverview.js
src/staging/src/pages/active-advisories.js

https://bcparksdigital.atlassian.net/browse/CM-224
1) useEffect should have a correct dependency 
2) we don't need to use Promise.all for one API request, for all side effects useEffect will take care of it, even if we need to chain them

CM-224: Resolve console errors on Park pages

---

src/staging/src/styles/parks.scss

CM-293
https://bcparksdigital.atlassian.net/browse/CM-293
- Added styling to make text left-aligned when it wraps 2 lines of text

CM-293: Update advisory text styling

---

src/staging/src/templates/park.js
src/staging/src/templates/parkSubPage.js
src/staging/src/templates/site.js

CM-291
https://bcparksdigital.atlassian.net/browse/CM-291
- Changed "Find a Park" to "Find a park" in the breadcrumb

CM-291: Update breadcrumb

---

src/staging/src/pages/index.js

CM-322
https://bcparksdigital.atlassian.net/browse/CM-322
Change title of homepage from 'Homepage' to 'Home'.

CM-322: change home page title to home

---

src/cms/api/public-advisory/services/public-advisory.js

CM-280
https://bcparksdigital.atlassian.net/browse/CM-280
- Updated the search/filter logic for the public advisories based on Mike's comment 👏

CM-280: Update search logic

---

src/staging/src/components/search/mainSearch.js
src/staging/src/pages/find-a-park.js
src/staging/src/styles/search.scss

CM-225
https://bcparksdigital.atlassian.net/browse/CM-225
- Removed "Park search is limited during beta" under the search bar
- Updated `find-a-park` page styling since the text is no longer there

CM-225: Remove during beta text

---

src/staging/src/components/park/specialNote.js
src/staging/src/templates/park.js

CM-282
https://bcparksdigital.atlassian.net/browse/CM-282
- Added a new component `specialNote.js` for `park.js`
- Updated `safetyInfo.js` as it doesn't have `park.specialNotes` anymore

CM-282: Add special notes section

---

src/staging/src/components/search/mainSearch.js

CM-330
https://bcparksdigital.atlassian.net/browse/CM-330
Removed "or campsite" from the search bar text

CM-330: Remove campsite from search bar

---

src/staging/src/pages/index.js
src/staging/src/pages/intro.js

CM-190
https://bcparksdigital.atlassian.net/browse/CM-190
- Removed navigation to the intro page
- Removed `useState`,`useEffect`, and conditional render

CM-190: Remove navigation to intro page

---

src/staging/src/pages/find-a-park.js

CM-226
https://bcparksdigital.atlassian.net/browse/CM-226
- Changed filter name "Wheelchair Access" to "Accessibility Information"
- Changed some filter names to title case from sentence case since it was mixed

CM-226: Change wheelchair access to accessibility information

---

src/staging/src/components/park/about.js
src/staging/src/components/park/heading.js
src/staging/src/styles/parks.scss

CM-206
https://bcparksdigital.atlassian.net/browse/CM-206
- Changed page h2 colour from black to blue
- Added space between the park details and the park contact
- Added the park details header (it can be changed later) to make each section consistent
- Made all bullets aligned
- Updated hex code to variables based on `variables.scss`

CM-206: Update park page styling

---

src/admin/src/components/page/advisory/Advisory.js
src/staging/src/components/advisories/advisoryCard.js
src/staging/src/components/park/advisoryDetails.js

CM-316, 317
https://bcparksdigital.atlassian.net/jira/software/projects/CM/boards/11?assignee=633db6bb61dbef2805c1f25c&selectedIssue=CM-316
https://bcparksdigital.atlassian.net/jira/software/projects/CM/boards/11?assignee=633db6bb61dbef2805c1f25c&selectedIssue=CM-317
.

Cm 316 Links prepending when attaching link to advisory

---

src/staging/src/components/park/parkDates.js

CM-244
https://bcparksdigital.atlassian.net/browse/CM-244
Format the "Dates of operation" section on Parks pages according to wireframes in the ticket

CM-244: Format the park operations section

---

src/staging/src/components/park/parkDates.js

CM-244
https://bcparksdigital.atlassian.net/browse/CM-244
Forgot to push my last commit before I merged the branch

CM-244: Change class to className

---

src/staging/gatsby-node.js
src/staging/src/components/park/campingDetails.js
src/staging/src/components/park/parkHeader.js
src/staging/src/templates/park.js
src/staging/src/templates/site.js

CM-336
https://bcparksdigital.atlassian.net/browse/CM-336
- Added `activityType` to the camping section
- Changed camping data function using `isCamping`, instead of `includes("camping")`
- Applied a new camping data logic to `park.js` and `site.js`
- Fixed minor bug (console warning on `site` page): added another `propType` to `parkName`

CM-336: Use isCamping for filter activityType and facilityType

---

src/staging/src/pages/find-a-park.js

None
None
This is related to the work Jane was doing to change the FacilityType and ActivityType labels from title case to sentence case

NOBUG: Fixed casing of search quick filters

---

src/staging/src/components/park/parkHeader.js

CM-361
https://bcparksdigital.atlassian.net/browse/CM-361
- Changed a button wording from `Get a daypass` to `Get a day-use pass`

CM-361: Change daypass button wording

---

src/staging/src/styles/home.scss

CM-301
https://bcparksdigital.atlassian.net/browse/CM-301
- Changed font size to `16px` (`1rem`) to avoid auto zoom on Chrome

CM-301: Change search input font size

---

src/staging/src/pages/find-a-park.js

CM-373
https://bcparksdigital.atlassian.net/browse/CM-373
- Changed `e.g` to `e.g.`

CM-373: Fix e.g to e.g.

---

infrastructure/helm/bcparks/values-prod.yaml

CM-160
https://bcparksdigital.atlassian.net/browse/CM-160
Committing changes that were made to the OpenShift pod resources to the helm config templates.

NOBUG: Add manual changes to the OpenShift PROD resources to helm config

---

src/admin/.env.example
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

CM-374
https://bcparksdigital.atlassian.net/browse/CM-374
Fixed an issue on prod that is currently preventing some users from loading the staff portal

CM-374: Fix for saved advisory filters that no longer exist

---

src/staging/src/components/thumbLink.js
src/staging/src/pages/404.js

CM-311
https://bcparksdigital.atlassian.net/browse/CM-311
- Fixed 404 page spacing issue

CM-311: Fix 404 page spacing issue

---

src/staging/__tests__/components/__snapshots__/footer.test.js.snap
src/staging/src/components/footer.js
src/staging/src/styles/footer.scss

CM-315
https://bcparksdigital.atlassian.net/browse/CM-315
- Increased logo size on mobile
- Added more space between section headings and items
- Moved social media icons to under the "Stay connected" section
- Added space between link items at the bottom

CM-315: Update footer ui

---

src/staging/src/templates/park.js
src/staging/src/templates/site.js

CM-371
https://bcparksdigital.atlassian.net/browse/CM-371
- Update an alphabetical sort function for the camping
- Added a comparison of different keys (`activityType.activityName`, `facilityType.facilityName`) since `activeCampings` is a mixed array of two different objects

CM-371: Update alphabetical sort for camping

---

src/staging/src/components/megaMenu.js

CM-300
https://bcparksdigital.atlassian.net/browse/CM-300
- Closed the navigation panel after the nav link is clicked
- Videos are available on the ticket page

CM-300: Close panel after navigate to the page

---

src/staging/src/components/park/about.js
src/staging/src/components/park/advisoryDetails.js

CM-380
https://bcparksdigital.atlassian.net/browse/CM-380
- Changed established date and advisory details posted date format `dd` to `d`

CM-380: Update date established format

---

src/staging/src/components/park/about.js

CM-385
https://bcparksdigital.atlassian.net/browse/CM-385
- Changed `Nature & culture` to `Nature and culture`

CM-385: Change & to and

---

src/staging/src/components/park/campingDetails.js
src/staging/src/components/park/parkActivity.js
src/staging/src/components/park/parkFacility.js
src/staging/src/styles/cmsSnippets/parkInfoPage.scss

No
No
- Reverted empty accordion changes - https://github.com/bcgov/bcparks.ca/pull/539
- Kept other refactor changes

NOBUG: Revert empty accordion changes

---

src/staging/src/pages/find-a-park.js

CM-386
https://bcparksdigital.atlassian.net/browse/CM-386
Use facilityCode/activityCode not facilityName/activityName for special search filter logic and update the hard-coded word "hook-ups" to have a hyphen.

CM-386: Use facilityCode/activityCode not facilityName/activityName

---

src/staging/src/pages/find-a-park.js

CM-345
https://bcparksdigital.atlassian.net/browse/CM-345
Fixed incorrect criteria for determining when to show the search result count on the Find-a-park page

CM-345: Find-a-park missing the results count when filter applied

---

src/staging/Caddyfile

CM-360
https://bcparksdigital.atlassian.net/browse/CM-360
Fix broken build.  The Openshift pod is failing due to my previous commit.

CM-360: caddy fmt

---

src/staging/src/styles/parks.scss
src/staging/src/templates/park.js
src/staging/src/templates/site.js

CM-90
https://bcparksdigital.atlassian.net/browse/CM-90
- Added height to the last section of the park page/site page to apply the active link style to the last side nav link
- Changed `offsetPx` to apply the active link style to the section that has a minimum height
- Deleted unused refs

CM-90: Update side nav behaviour

---

src/staging/src/components/park/reconciliation.js
src/staging/src/templates/park.js

CM-391
https://bcparksdigital.atlassian.net/browse/CM-391
Wording change.

CM-391: wording change

---

src/staging/src/components/betaBanner.js

CM-277
https://bcparksdigital.atlassian.net/browse/CM-277
- Updated banner content based on [Figma](https://www.figma.com/file/CoXGPkDLN7HKkt0kPuqWhv/BC-Parks-Website?node-id=4365%3A41978)

CM-277: Update banner content

---

src/staging/src/styles/search.scss

CM-405
https://bcparksdigital.atlassian.net/browse/CM-405
- Changed map link font-size `1.25rem` to `1rem`

CM-405: Update map link font size

---

src/staging/Caddyfile

None
None
Redirect beta.bcparks.ca to bcparks.ca

NOBUG: Redirect beta.bcparks.ca to bcparks.ca

---

src/staging/gatsby-config.js
src/staging/package.json

CM-447
https://bcparksdigital.atlassian.net/browse/CM-447
- Downgraded `gatsby-plugin-sitemap` for Gatsby v3
- Changed the sitemap setting to change the sitemap folder structure

CM-447: Change sitemap output

---

.github/workflows/build-public.yaml
README.md

CM-452
https://bcparksdigital.atlassian.net/browse/CM-452
Remove "beta" from dev and test urls

CM-452: Dev & Test url updates

---

src/staging/gatsby-config.js

CM-451
https://bcparksdigital.atlassian.net/browse/CM-451
- Added `https://bcparks.ca` as a siteUrl to the canonical URL
- Added conditions to the generate `robots.txt` based on the environment

CM-451: Add prod domain to canonical

---

.github/workflows/build-public.yaml

CM-456
https://bcparksdigital.atlassian.net/browse/CM-456
Fixed an issue causing the prod URL to appear in the test robots.txt and sitemap.xml files (and potentially vice-versa).  
Also changed the order of the build file conditions from **test/prod/dev** to **prod/test/dev** to hopefully prevent this from happening again.

CM-456: Fix for criss-crossed REACT_APP_SITE_URL variable

---

src/staging/gatsby-config.js
src/staging/src/styles/parks.scss

BWT-565
https://bcparksdigital.atlassian.net/browse/BWT-565
Override css to avoid page overflowing in mobile when gallery is present.

BWT-565: fixed mobile overflow on parks pages

---

src/staging/gatsby-ssr.js

BWT-565
https://bcparksdigital.atlassian.net/browse/BWT-565
Added basic styles to header in order to try to avoid google mobile-friendly test failing pages.

BWT-565: added default styles to header

---

src/cms/api/page/models/page.settings.json

CM-146
https://bcparksdigital.atlassian.net/browse/CM-146
- Deleted unused components, `image` and `fancy-link` from the page component list

CM-146: Delete unnecesarry components from page

---

src/staging/src/components/park/parkDates.js

CM-403
https://bcparksdigital.atlassian.net/browse/CM-403
- Changed `group sites` to `groupsites`

CM-403: Change wording

---

src/staging/src/pages/find-a-park.js

CM-377
https://bcparksdigital.atlassian.net/browse/CM-377
- Added `orderBy` to sort `activityName` by alphabet case insensitive order

CM-377: Sort activity names

---

src/staging/src/components/park/advisoryDetails.js

CM-444
https://bcparksdigital.atlassian.net/browse/CM-444
- Displayed `updatedDate` of `publicAdvisories` when `isUpdatedDateDisplayed` is ON

CM-444: Add updated date to park and site page

---

src/staging/src/components/park/parkDates.js
src/staging/src/templates/park.js

CM-411
https://bcparksdigital.atlassian.net/browse/CM-411
For facilities like picnic shelters that are not "camping", use the label "Main operating season dates" instead of "Main camping season dates"

CM-411: use label "Main operating season dates" for non-camping dates

---

src/cms/api/activity-type/models/activity-type.settings.json
src/cms/api/facility-type/models/facility-type.settings.json
src/staging/gatsby-node.js
src/staging/src/components/park/campingDetails.js
src/staging/src/components/park/parkActivity.js
src/staging/src/components/park/parkFacility.js
src/staging/src/templates/park.js
src/staging/src/templates/site.js

CM-389
https://bcparksdigital.atlassian.net/browse/CM-389
- Added new field `defaultDescription` to `activityTypes` and `facilityTypes`
- Displayed `defaultDescription` on the park and site pages if there's no `description` of `parkActivities` and `parkFacilities`

CM-389: Add defaultDescription

---

src/staging/src/styles/parks.scss

CM-457
https://bcparksdigital.atlassian.net/browse/CM-457
Kept the old css because I wasn't clear why it was there, instead put in an override for embedded videos.

CM-457: css tweak to ensure videos are visible on mobile

---

src/staging/src/components/megaMenu.js
src/staging/src/components/park/campingDetails.js
src/staging/src/components/park/parkHeader.js

CM-430
https://bcparksdigital.atlassian.net/browse/CM-430
See last comment in JIRA for acceptance criteria. In the end, just a label change.

CM-430: changed text

---

src/staging/package.json
src/staging/src/pages/find-a-park.js

CM-410
https://bcparksdigital.atlassian.net/browse/CM-410
- Made the find-a-park page scroll to the top every time the pagination clicked

CM-410: Add page scroll useEffect

---

src/staging/src/pages/find-a-park.js
src/staging/src/styles/search.scss

CM-116
https://bcparksdigital.atlassian.net/browse/CM-116
- Changed the heading of some of the elements
- Added some stylings to keep their font sizes

CM-116: Fix heading levels warning

---

src/cms/api/page/models/page.js
src/cms/api/park-sub-page/models/park-sub-page.js
src/cms/api/protected-area/models/protected-area.js
src/cms/api/site/models/site.js
src/cms/config/functions/slugValidator.js

CM-455
https://bcparksdigital.atlassian.net/browse/CM-455
- Added new validation for slug fields to prevent having a slug such as `-` or `-/-`

CM-455: Add new validation for slug fields

---

src/staging/src/components/megaMenu.js
src/staging/src/styles/megaMenu/megaMenu.scss

CM-442
https://bcparksdigital.atlassian.net/browse/CM-442
Improvements to meganav to make it more accessible. 
Minor css fix-ups that I spotted while I was there.

Cm 442 meganav accessible

---

src/staging/src/components/pageContent/linkCard.js

CM-116
https://bcparksdigital.atlassian.net/browse/CM-116
- Changed linkCard title heading

CM-116: Change linkCard heading

---

src/staging/__tests__/components/__snapshots__/footer.test.js.snap
src/staging/src/components/footer.js
src/staging/src/components/megaMenu.js
src/staging/src/styles/search.scss
src/staging/src/styles/staticLanding1.scss

CM-117
https://bcparksdigital.atlassian.net/browse/CM-117
Fixed to address issues in sort site accessibility tool review.

CM-117: sortsite fixes

---

src/staging/src/components/megaMenu.js

CM-442
https://bcparksdigital.atlassian.net/browse/CM-442
Fixes an issue where two windows open on a cmd-click if the pop-up blocker is active.

CM-442: behaviour change for double-windows opening

---

src/cms/config/functions/slugValidator.js

CM-518
https://bcparksdigital.atlassian.net/browse/CM-518
- Fix a validation error when the slug is null

CM-518: Fix validation error

---

src/staging/src/components/advisories/advisoryCard.js
src/staging/src/components/advisories/advisoryFilter.js
src/staging/src/components/advisories/advisoryLegend.js
src/staging/src/components/megaMenu.js
src/staging/src/components/pageContent/pageMenu.js
src/staging/src/pages/find-a-park.js
src/staging/src/styles/advisories/advisoryCard.scss
src/staging/src/styles/advisories/advisoryFilter.scss
src/staging/src/styles/parks.scss
src/staging/src/styles/search.scss
src/staging/src/styles/staticContent1.scss
src/staging/src/styles/staticLanding1.scss

CM-117
https://bcparksdigital.atlassian.net/browse/CM-117
Changes to fix sortsite tickets relating to accessibility.

CM-117: sortsite changes

---

src/staging/src/pages/find-a-park.js

CM-490
https://bcparksdigital.atlassian.net/browse/CM-490
Made the pagination buttons the large size on mobile, and reduced the number of buttons to avoid some overflow issues.

CM-490: large buttons for mobile pagination

---

src/staging/src/components/header.js
src/staging/src/components/park/parkOverview.js
src/staging/src/components/search/mainSearch.js
src/staging/src/components/skipToContent.js
src/staging/src/pages/404.js
src/staging/src/pages/active-advisories.js
src/staging/src/pages/find-a-park.js
src/staging/src/pages/index.js
src/staging/src/pages/sitemap.js
src/staging/src/styles/home.scss
src/staging/src/styles/staticLanding1.scss
src/staging/src/templates/park.js
src/staging/src/templates/parkSubPage.js
src/staging/src/templates/site.js
src/staging/src/templates/staticContent1.js
src/staging/src/templates/staticLanding1.js

CM-526
CM-527
CM-528
https://bcparksdigital.atlassian.net/browse/CM-526
https://bcparksdigital.atlassian.net/browse/CM-527
https://bcparksdigital.atlassian.net/browse/CM-528
Combined a few minor accessibility fixes.

CM-526: accessibility fixes

---

src/cms/data/functions/loadPar.js
src/cms/src/api/protected-area/content-types/protected-area/schema.json
src/cms/src/api/site/content-types/site/schema.json
src/staging/gatsby-node.js
src/staging/src/templates/park.js
src/staging/src/templates/site.js

CM-471
https://bcparksdigital.atlassian.net/browse/CM-471
- Delete `hasDayUsePass` from `protectedArea` and `site`

CM-471: Delete hasDayUsePass

---

.github/workflows/publish-gatsby.yaml

CM-505
https://bcparksdigital.atlassian.net/browse/CM-505
I think I need to add this file to the main branch so it can be triggered from GitHub

Add publish-gatsby github workflow to main branch to make it runnable

---

src/staging/gatsby-config.js

No
No
- Change robots txt to disallow for dev

NOBUG: Fix robots txt for dev

---

src/staging/gatsby-config.js

No
No
- Change robots txt to disallow for dev

NOBUG: Change robots txt to disallow for dev env

---

src/staging/src/pages/find-a-park.js

CM-549
https://bcparksdigital.atlassian.net/browse/CM-549
- Change activities and facilities checkboxes to be focused by tabbing

CM-549: Change tab index for filters

---

src/cms/src/api/public-advisory-audit/content-types/public-advisory-audit/lifecycles.js

CM-596
https://bcparksdigital.atlassian.net/browse/CM-596
- Fix the issue that some relations (e.g. `protectedAreas`, `sites`, `links`) were not saved to `publicAdvisories`

CM-596: Fix public advisories saving issue

---

src/maintenance/index.html

NONE
Updated asset urls on the maintenance page, so they would resolve on subdirectory pages like https://main-maintenance-61d198-dev.apps.silver.devops.gov.bc.ca/golden-ears-park/

NOBUG: Maintenance page assets 404 fix

---

infrastructure/helm/bcparks/templates/cms/cms-deployment.yaml
infrastructure/helm/bcparks/values-alpha-dev.yaml
infrastructure/helm/bcparks/values-alpha-test.yaml
infrastructure/helm/bcparks/values-dev.yaml
infrastructure/helm/bcparks/values-prod.yaml
infrastructure/helm/bcparks/values-test.yaml
src/cms/.env.example

NONE
Updated OpenShift config to add a new environment variable to every environment. 
NOTE: This has already been deployed to 5 environments by following the "Upgrading" instruction on this page:
https://github.com/bcgov/bcparks.ca/tree/develop/infrastructure/helm

NOBUG: Add STRAPI_ADMIN_ENVIRONMENT var for identifying environments

---

.github/workflows/deploy-alpha-test.yaml
.github/workflows/deploy-main-prod.yaml
.github/workflows/deploy-main-test.yaml
README.md
infrastructure/helm/Strapi 4 Upgrade Notes.txt
infrastructure/helm/bcparks/values-prod.yaml
infrastructure/helm/bcparks/values-test.yaml

None
Merging OpenShift config updates from the new (non-alpha) test environments

OpenShift config updates

---

src/staging/src/components/advisories/advisoryCard.js

CM-604
https://bcparksdigital.atlassian.net/browse/CM-604
- Fix protectedArea links are not displayed on the Active Advisories page

CM-604: Fix protectedArea link issue

---

src/staging/src/styles/megaMenu/megaMenu.scss

CM-600
https://bcparksdigital.atlassian.net/browse/CM-600
- Add arrow icon animation when the menu is closing

CM-600: Add arrow icon animation

---

src/cms/src/api/public-advisory/services/public-advisory.js

CM-616
https://bcparksdigital.atlassian.net/browse/CM-616
- Change `eventType` filter from exact matches to contains

CM-616: Fix event type filter

---

src/admin/src/components/page/advisory/Advisory.js
src/admin/src/utils/CmsDataUtil.js
src/admin/src/utils/LocationUtil.js
src/cms/config/plugins.js
src/cms/src/api/public-advisory-audit/content-types/public-advisory-audit/lifecycles.js

CM-609
https://bcparksdigital.atlassian.net/browse/CM-609
When creating or updating an advisory, there was an error if a regional selection has been made (i.e. Region, Section, Management Area, Fire Centre, Fire Zone)

CM-609: Fix Staff Portal advisory regional association error

---

src/admin/src/utils/AdvisoryUtil.js

CM-609
https://bcparksdigital.atlassian.net/browse/CM-609
Fixed another error that happens periodically when updating public advisories from the staff portal.

CM-609: Fix error saving advisories

---

.github/workflows/publish-gatsby.yaml
infrastructure/helm/bcparks/values-dev.yaml
infrastructure/helm/bcparks/values-test.yaml

CM-618
https://bcparksdigital.atlassian.net/browse/CM-618
Updating the dev and test environment to use vanity urls instead of openshift default urls

CM-618: Staff Portal URL changes to the OpenShift URL after login

---

src/gatsby/src/components/megaMenu.js

CM-600
CM-605
CM-622
https://bcparksdigital.atlassian.net/browse/CM-600
https://bcparksdigital.atlassian.net/browse/CM-605
https://bcparksdigital.atlassian.net/browse/CM-622
Button behaviour for buttons with a menu attached
- Hover - underline button text
- Click - open the mega menu (does not open landing page), display selected state
- The second click on the button with the opened menu closes the menu (does not open the landing page)
- If a menu is open and a user clicks another button, close the visible menu and open the new menu

CM-605: Update megamenu click behaviour

---

src/cms/src/plugins/strapi-plugin-ckeditor/admin/src/components/Input/CKEditor/configs/base.js
src/cms/src/plugins/strapi-plugin-ckeditor/admin/src/components/Input/CKEditor/theme/common.js

CM-611, CM-615
https://bcparksdigital.atlassian.net/browse/CM-611
https://bcparksdigital.atlassian.net/browse/CM-615
Turned off extra list styles and the lower-alpha style as they were working properly.
Changed RTE to reflect proper colour for links.

CM-611: removed extra list options, changed link color

---

src/gatsby/src/components/advisories/advisoryCard.js
src/gatsby/src/pages/active-advisories.js

CM-599
https://bcparksdigital.atlassian.net/browse/CM-599
- Fix incorrect result count on the Active Advisories page
- Fix the console warning below
```
React.development.js:220 Warning:
Failed prop type: The prop `to` is marked as required in `b`, but its value is `undefined`.
```

CM-599: Fix incorrect result count

---

src/cms/config/cron-tasks.js

CM-627
https://bcparksdigital.atlassian.net/browse/CM-627
Updated the logic of the cron job to be more consistent with the original.

CM-627: Fix expired advisory bug

---

src/cms/config/cron-tasks.js

CM-576
CM-643
https://bcparksdigital.atlassian.net/browse/CM-576
https://bcparksdigital.atlassian.net/browse/CM-643
- Delete the entry in the Public Advisory collection when expired
- Should the revision number be incremented when its status was changed automatically from "PUB" to "INA"?

CM-576: Delete public-advisory when it expired

---

src/gatsby/src/components/seo.js
src/gatsby/src/templates/park.js
src/gatsby/src/templates/parkSubPage.js
src/gatsby/src/templates/site.js
src/gatsby/src/templates/staticContent1.js

CM-424
https://bcparksdigital.atlassian.net/browse/CM-424
- Add og image fallback to the park/sub park/site/static content page

CM-424: Update meta og image

---

src/gatsby/src/pages/find-a-park.js

CM-549
https://bcparksdigital.atlassian.net/browse/CM-549
- Added `onKeyUp` event to select "Show All/Less" button by space/enter key

CM-549: Add key up to select by space key

---

src/gatsby/src/styles/global.scss
src/gatsby/src/styles/parks.scss
src/gatsby/src/styles/variables.scss

CM-488
https://bcparksdigital.atlassian.net/browse/CM-488
- Changed body font colour to `#1a1a1a` for the consistency

CM-488: Change global font colour

---

src/admin/entrypoint.sh

CM-642
https://bcparksdigital.atlassian.net/browse/CM-642
- Add a new environment variable `REACT_APP_PUBLIC_URL` to entrypoint

CM-642: Update entrypoint

---

infrastructure/helm/bcparks/values-test.yaml

None
None
Reverted a helm config change that was preventing `helm upgrade` from working on `main-test`

Nobug helm revert

---

src/cms/src/api/public-advisory-audit/content-types/public-advisory-audit/lifecycles.js

CM-656
https://bcparksdigital.atlassian.net/browse/CM-656
- Delete inactive advisory

CM-656: Delete inactive advisory

---

src/cms/src/api/public-advisory-audit/controllers/public-advisory-audit.js

CM-657
https://bcparksdigital.atlassian.net/browse/CM-657
Fix error clearing cache for uncached collection type

CM-657: Fix error clearing cache for uncached collection type

---

src/cms/src/api/fire-ban-prohibition/services/fire-ban-prohibition.js

CM-555
https://bcparksdigital.atlassian.net/browse/CM-555
Fix a bug discovered in QA

CM-555: Clear campfilreBanRescindedDate when setting hasCampfireBan=true

---

src/cms/src/api/protected-area/content-types/protected-area/lifecycles.js

CM-664
https://bcparksdigital.atlassian.net/browse/CM-664
Added a try/catch to make the code more closely match the old Strapi 3 code

CM-664: Add try/catch

---

.github/workflows/build-dev.yaml

CM-557
https://bcparksdigital.atlassian.net/browse/CM-557
I accidentally added an extra line to the end of the file that I didn't need

CM-557: Fix error in build script

---

.github/workflows/build-dev.yaml
src/admin/package.json

CM-663
https://bcparksdigital.atlassian.net/browse/CM-663
Update the Staff Portal to work from PowerShell with Node.js 18 instead of requiring Node.js 14.

CM-663: Update the staff portal to Node.js 18

---

src/gatsby/src/templates/park.js

CM-661
https://bcparksdigital.atlassian.net/browse/CM-661
- Add another API call to the park page to get `hasCampfireBan` data that allows us to have the latest data without the Gatsby build

CM-661: Add api call to get hasCampfireBan data

---

src/cms/src/api/fire-ban-prohibition/controllers/fire-ban-prohibition.js
src/cms/src/api/fire-ban-prohibition/services/fire-ban-prohibition.js

CM-555
https://bcparksdigital.atlassian.net/browse/CM-555
Add an additional check for "category 1" when filtering which fire bans are considers campfire bans based on the data presented on this page. https://www2.gov.bc.ca/gov/content/safety/wildfire-status/prevention/fire-bans-and-restrictions

CM-555: Add additional check for "category 1" to campfire bans

---

src/cms/src/api/activity-type/content-types/activity-type/schema.json
src/cms/src/api/business-hour/content-types/business-hour/schema.json
src/cms/src/api/facility-type/content-types/facility-type/schema.json
src/cms/src/api/page/content-types/page/schema.json
src/cms/src/api/park-photo/content-types/park-photo/schema.json
src/cms/src/api/park-sub-page/content-types/park-sub-page/schema.json
src/cms/src/api/protected-area/content-types/protected-area/schema.json
src/cms/src/api/site/content-types/site/schema.json
src/gatsby/gatsby-node.js

CM-99
https://bcparksdigital.atlassian.net/browse/CM-99
- Make some fields required
- Business-hour | tuesday: The only not-required field in this collection
- Page | Slug, Template: Necessary to create static pages
```
result.data.allStrapiPage.nodes.forEach(page => {
actions.createPage({
path: page.Slug.replace(/\/$|$/, `/`),
component: require.resolve(`./src/templates/${page.Template}.js`),
context: { page },
})
})
```
- Park-photo | caption: Must have from the accessibility point of view, based on Manuji's comment
- Park-sub-page | protectedArea: Necessary to create park sub pages
```
result.data.allStrapiParkSubPage.nodes.forEach(parkSubPage => {
const parkPath = parkSubPage.protectedArea.slug
const parkSubPagePath = `${parkPath}/${parkSubPage.slug}`
actions.createPage({
path: …
```

CM-99: Add required fields

---

src/cms/config/middlewares.js

CM-690
https://bcparksdigital.atlassian.net/browse/CM-690
Fixed content security policies

CM-690: Fix error previewing video in CKEditor

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/page/advisory/Advisory.js
src/cms/database/migrations/2023.05.23T00.00.00.listing-rank-not-null.js

CM-653
Fixed a bug where the listingRank was blank instead of `0` when editing from the staff portal.

CM-653: Fix for blank listingRank on staff-portal edit form

---

src/cms/src/api/park-sub-page/content-types/park-sub-page/schema.json
src/cms/src/api/site/content-types/site/schema.json
src/gatsby/gatsby-node.js

CM-99
https://bcparksdigital.atlassian.net/browse/CM-99
- Revert required relational fields as it did not work

CM-99: Revert required relational fields

---

src/kong/public-prod.yaml
src/kong/public-test.yaml

CM-653
Added the /public-advisories/items endpoint to kong

CM-653: Add items endpoint to Kong

---

src/gatsby/src/utils/usePreRenderVideo.js

None
None
- Fix slugify error when it could not get the title

NOBUG: Fix slugify error when it could not get title

---

src/admin/src/validators/AdvisoryValidator.js

CM-708
https://bcparksdigital.atlassian.net/browse/CM-708
Fixed validation error

CM-708: ListingRank throws false validation error when value is zero

---

src/cms/src/api/biogeoclimatic-zone/content-types/biogeoclimatic-zone/schema.json
src/cms/src/api/biogeoclimatic-zone/controllers/biogeoclimatic-zone.js
src/cms/src/api/biogeoclimatic-zone/routes/biogeoclimatic-zone.js
src/cms/src/api/biogeoclimatic-zone/services/biogeoclimatic-zone.js
src/cms/src/api/marine-ecosection/content-types/marine-ecosection/schema.json
src/cms/src/api/marine-ecosection/controllers/marine-ecosection.js
src/cms/src/api/marine-ecosection/routes/marine-ecosection.js
src/cms/src/api/marine-ecosection/services/marine-ecosection.js
src/cms/src/api/protected-area/content-types/protected-area/schema.json
src/cms/src/api/terrestrial-ecosection/content-types/terrestrial-ecosection/schema.json
src/cms/src/api/terrestrial-ecosection/controllers/terrestrial-ecosection.js
src/cms/src/api/terrestrial-ecosection/routes/terrestrial-ecosection.js
src/cms/src/api/terrestrial-ecosection/services/terrestrial-ecosection.js
src/gatsby/gatsby-config.js
src/gatsby/gatsby-node.js
src/gatsby/src/components/park/about.js
src/gatsby/src/styles/parks.scss
src/gatsby/src/templates/park.js

CM-441
https://bcparksdigital.atlassian.net/browse/CM-441
- Add new collections `biogeoclimaticZone`  `marineEcosection` `terrestrialEcosection`
- Add a bullet point for each new collection in the Ecological reserve details on Park pages if data exists

CM-441: Add biogeoclimaticZone, marineEcosection, terrestrialEcosection

---

src/gatsby/src/components/advisories/advisoryFilter.js
src/gatsby/src/components/advisories/advisoryLegend.js
src/gatsby/src/pages/active-advisories.js
src/gatsby/src/styles/advisories/advisoryLegend.scss

CM-633
https://bcparksdigital.atlassian.net/browse/CM-633
- Change some wordings on the active advisories page

CM-633: Update active advisory page wording

---

src/cms/src/api/activity-type/content-types/activity-type/schema.json
src/cms/src/api/facility-type/content-types/facility-type/schema.json
src/cms/src/api/park-activity/content-types/park-activity/schema.json
src/cms/src/api/park-facility/content-types/park-facility/schema.json
src/gatsby/gatsby-node.js
src/gatsby/src/components/park/parkActivity.js
src/gatsby/src/components/park/parkFacility.js
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CM-637
https://bcparksdigital.atlassian.net/browse/CM-637
- Add `appendStandardCalloutText` field to `activity-type` and `facility-type`
- Add `appendStandardCalloutOverride` field to `park-activity` and `park-facility`
- Park/Site page will have a callout in each activity/facility accordion if there's data in  `appendStandardCalloutText` or `appendStandardCalloutOverride`

CM-637: Add callout field to park activity and park facility

---

src/cms/src/components/parks/page-section.json
src/gatsby/src/components/pageContent/pageContent.js
src/gatsby/src/components/pageContent/pageSection.js
src/gatsby/src/styles/staticContent1.scss
src/gatsby/src/templates/parkSubPage.js
src/gatsby/src/templates/staticContent1.js

CM-682
https://bcparksdigital.atlassian.net/browse/CM-682
- Change pageSection content id from section id to section title on StaticContent page and ParkSub page

CM-682: Change pageSection content id from section id to section title

---

src/cms/src/api/page/content-types/page/lifecycles.js
src/cms/src/api/park-sub-page/content-types/park-sub-page/lifecycles.js
src/cms/src/api/park-sub-page/content-types/park-sub-page/schema.json
src/cms/src/api/protected-area/content-types/protected-area/lifecycles.js
src/cms/src/api/site/content-types/site/lifecycles.js
src/cms/src/api/site/content-types/site/schema.json
src/cms/src/helpers/validator.js

CM-700
https://bcparksdigital.atlassian.net/browse/CM-700
- Add custom validation to the sites/park-sub-pages to check if it has a relation with the protectedAreas
- The error message will be displayed with these conditions:
- When an editor creates a new entry and tries to save it without a relation
- When an editor removes a relation and tries to save an entry

CM-700: Add custom validation to sites

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js

CM-625
CM-672
https://bcparksdigital.atlassian.net/browse/CM-625
https://bcparksdigital.atlassian.net/browse/CM-672
- Make the standard message field as NOT required
- Add validations to the link title field and the link URL field
- The validations check if the title/url is empty when the url/title is entered

CM-625: Remove required from standard message field

---

src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/components/park/campingDetails.js
src/gatsby/src/components/park/mapLocation.js
src/gatsby/src/components/park/parkActivity.js
src/gatsby/src/components/park/parkDates.js
src/gatsby/src/components/park/parkFacility.js
src/gatsby/src/styles/home.scss
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CM-362
CM-395
CM-397
https://bcparksdigital.atlassian.net/browse/CM-362
https://bcparksdigital.atlassian.net/browse/CM-395
https://bcparksdigital.atlassian.net/browse/CM-397
- CM-362, CM-397: Add spacer to each page section
- CM-395: Fix button text line height

CM-362: Add spacer to each page section

---

src/gatsby/gatsby-node.js
src/gatsby/src/components/pageContent/pageContent.js
src/gatsby/src/components/pageContent/pageSection.js

CM-723
https://bcparksdigital.atlassian.net/browse/CM-723
Fixes a bug from the Strapi 4 / Gatsby 4 update that caused broken anchor links

CM-723: Bugfix for page section ID's changed from int to guid

---

src/cms/package-lock.json
src/gatsby/package-lock.json

CM-715
https://bcparksdigital.atlassian.net/browse/CM-715
Forgot to update package lock file

NOBUG: Updated lock files

---

src/gatsby/src/pages/find-a-park.js
src/gatsby/src/styles/search.scss

CM-651
https://bcparksdigital.atlassian.net/browse/CM-651
- Users can tab chip filters and delete them with enter key

CM-651: Update chip filter more accessible

---

src/gatsby/src/components/betaBanner.js

CM-724
https://bcparksdigital.atlassian.net/browse/CM-724
- Remove the survey link from the banner

CM-724: Remove survey link from banner

---

.github/workflows/deploy-alpha-test.yaml

None
None
Fixes an error in the alpha-test deployment script that was causing the etl pod to be deployed for the maintenance site.

NOBUG: Fix error in alpha-test deployment script

---

src/gatsby/src/styles/search.scss

CM-396
https://bcparksdigital.atlassian.net/browse/CM-396
- Changed the MUI Link underline default colour to match the font colour when it's hovered and focused

CM-396: Change link underline colour

---

.github/workflows/on-pr.yaml

None
None
Run tests when a PR is created on the develop branch

NOBUG: Run tests when a PR is created on the develop branch

---

src/gatsby/gatsby-config.js
src/gatsby/src/components/betaBanner.js
src/gatsby/src/components/header.js

CM-724
https://bcparksdigital.atlassian.net/browse/CM-724
- Revert the previous change
- Remove the welcome banner
- Change the default background colour from Gatsby purple to BC dark blue

CM-724: Remove banner and update background colour

---

src/cms/src/api/event-type/content-types/event-type/schema.json
src/gatsby/src/components/park/advisory.js

CM-667
https://bcparksdigital.atlassian.net/browse/CM-667
Add a precedence field to eventType that will be used to determine which events appear in the summary in the park page header.  A lower value equals a higher priority.

CM-667: Add precedence to eventType

---

src/gatsby/gatsby-node.js
src/gatsby/src/templates/park.js

CM-725
https://bcparksdigital.atlassian.net/browse/CM-725
- Update typedefs to fix build a build error

CM-725: Update typedefs for park activity and park facility

---

src/gatsby/src/pages/about/park-management-plans/approved.js

CM-732
https://bcparksdigital.atlassian.net/browse/CM-732
- Update alphabet filtering to match the uppercase/lowercase title

CM-732: Update alphabet filtering to match lowercase title

---

src/cms/src/components/parks/page-header.json
src/gatsby/gatsby-node.js
src/gatsby/src/components/pageContent/pageHeader.js
src/gatsby/src/templates/parkSubPage.js
src/gatsby/src/templates/staticContent1.js

CM-93
https://bcparksdigital.atlassian.net/browse/CM-93
- Remove imageAlt and imageCaption from pageHeader component

CM-93: Remove imageAlt and imageCaption

---

README.md
infrastructure/helm/bcparks/values.yaml
src/admin/README.md
src/cms/.env.example
src/cms/README.md
src/cms/src/api/protected-area/content-types/protected-area/lifecycles.js
src/cms/src/helpers/validator.js
src/gatsby/README.md

CM-592
https://bcparksdigital.atlassian.net/browse/CM-592
Update the local dev setup instructions to use Strapi export/import instead of seed

CM-592: Update the local dev setup instructions with Strapi 4 changes

---

src/gatsby/src/components/advisories/advisoryCard.js
src/gatsby/src/styles/advisories/advisoryCard.scss

CM-719
https://bcparksdigital.atlassian.net/browse/CM-719
- Add fireCentres to each advisory
- Hide all affected parks
- Add a button to display all affected parks
- Remove the accordion function

CM-719: Add fireCentres to active advisories page

---

src/gatsby/src/styles/search.scss

CM-651
https://bcparksdigital.atlassian.net/browse/CM-651
- Add a focus visible border to filter chips when users do tab over

CM-651: Add focus visible border to filter chips

---

src/gatsby/gatsby-node.js
src/gatsby/src/pages/about/management-plans/approved.js

CM-437
https://bcparksdigital.atlassian.net/browse/CM-437
- Change the path name from `/about/park-management-plans/approved` to `/about/management-plans/approved`
- Display protectedAreaName as a management document plan link

CM-437: Update management document plan links logic

---

src/gatsby/src/templates/parkSubPage.js

CM-744
https://bcparksdigital.atlassian.net/browse/CM-744
- Fix a build error in the case park-sub-page does not have any content

CM-744: Fix build error in the case park-sub-page does not have any content

---

src/gatsby/src/pages/active-advisories.js
src/gatsby/src/pages/find-a-park.js

CM-742
https://bcparksdigital.atlassian.net/browse/CM-742
Remove trailing slashes from REST calls as a work-around for a bug in strapi-plugin-rest-cache

CM-742: Remove trailing slashes from REST calls to fix cache issue

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.css
src/admin/src/components/composite/advisoryForm/AdvisoryForm.js

CM-586
https://bcparksdigital.atlassian.net/browse/CM-586
- Add tooltip text to advisory form fields

CM-586: Add tooltip text to advisory form fields

---

src/gatsby/src/styles/advisories/advisoryCard.scss

CM-123
https://bcparksdigital.atlassian.net/browse/CM-123
- Badge text can be wrapped on the mobile screen

CM-748: Add pre-line to the badge

---

src/gatsby/src/pages/about/management-plans/approved.js

CM-750
https://bcparksdigital.atlassian.net/browse/CM-750
- Merge to main
- If there's no relation between protectedArea and site, the link itself won't be displayed

CM-750: Fix protectedArea and site relation issue

---

src/gatsby/src/pages/about/management-plans/approved.js

CM-751
https://bcparksdigital.atlassian.net/browse/CM-751
- Merge to main
- Add sorting order based on protectedAreaName

CM-751: Add sorting order based on protectedAreaName

---

src/admin/src/components/page/parkAccessStatus/ParkAccessStatus.js

CM-754
https://bcparksdigital.atlassian.net/browse/CM-754
Fixed a bug where a blank page was being displayed when the links were opened in a new tab.

CM-754: Fixed link to invalid route

---

src/cms/src/api/activity-type/content-types/activity-type/schema.json
src/cms/src/api/facility-type/content-types/facility-type/schema.json
src/cms/src/api/park-activity/content-types/park-activity/schema.json
src/cms/src/api/park-facility/content-types/park-facility/schema.json
src/gatsby/gatsby-node.js
src/gatsby/src/components/park/parkActivity.js
src/gatsby/src/components/park/parkFacility.js
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CM-637
Revert standard callouts & hold back until next release, pending possible re-design of the feature.

CM-637: Revert standard callouts & hold back until next release

---

src/cms/src/api/activity-type/content-types/activity-type/schema.json
src/cms/src/api/facility-type/content-types/facility-type/schema.json
src/cms/src/api/park-activity/content-types/park-activity/schema.json
src/cms/src/api/park-facility/content-types/park-facility/schema.json
src/gatsby/gatsby-node.js
src/gatsby/src/components/park/parkActivity.js
src/gatsby/src/components/park/parkFacility.js
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CM-637
Reverted standard callouts & held back until next release, pending possible re-design of the feature.

CM-637: Move standard callouts back to develop branch

---

src/gatsby/src/components/advisories/advisoryCard.js

CM-755
- Merge to main
- Display affected parks buttons if there are fewer than 5 parks
- Display show/hide link if there are more than 6 parks

CM-755: Update show/hide affected parks link logic

---

src/gatsby/gatsby-config.js
src/gatsby/gatsby-node.js
src/gatsby/src/pages/about/management-plans/approved.js

CM-751
- Change query to `protectedArea.managementDocuments` from `managementDocument` to sort based on park name

CM-751: Change management plan page query

---

src/gatsby/gatsby-node.js

None
- Fix gatsby build error: https://github.com/bcgov/bcparks.ca/actions/runs/5294694851

NOBUG: Fix gatsby build error

---

src/gatsby/src/pages/about/management-plans/approved.js

None
- Fix the build error
https://github.com/bcgov/bcparks.ca/actions/runs/5316149228/jobs/9625360263#step:11:183

NOBUG: Fix the build error

---

src/cms/database/migrations/2023.06.13T00.00.04.link-marine-ecosections.js
src/cms/database/migrations/2023.06.13T00.00.06.link-terrestrial-ecosections.js

CM-698
Removed a duplicate record that was imported twice

CM-698: Remove duplicate marine_ecosections record

---

src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
src/admin/src/components/page/parkSearch/ParkSearch.js

CM-761
Improved error handling for management-areas with no section or region assigned

CM-761: Add handling for invalid management areas

---

src/gatsby/src/pages/about/management-plans/approved.js

CM-751
- Add sorting based on the full link text

CM-751: Add sorting based on full link text

---

src/gatsby/src/pages/about/management-plans/approved.js

CM-760
- Fix breadcrumb link to `/about/management-plans`

CM-760: Fix breadcrumb link

---

src/cms/src/api/park-activity/content-types/park-activity/schema.json
src/cms/src/api/park-facility/content-types/park-facility/schema.json
src/gatsby/gatsby-node.js
src/gatsby/src/components/park/parkActivity.js
src/gatsby/src/components/park/parkFacility.js
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CM-637
- Delete `appendStandardCalloutOverride`
- Add `hideStandardCallout`
- Display `appendStandardCalloutText` if `appendStandardCalloutText` is not null
- Hide `appendStandardCalloutText` if `hideStandardCallout` is TRUE

CM-637: Add hideStandardCallout to park-activity and park-facility

---

src/gatsby/src/styles/listPage.scss
src/gatsby/src/styles/variables.scss

CM-758
- A-Z lettering not bolded when not selected/hovered
- On hover, the background fill will be #ECF6FF

CM-758: Update hover state for alphabet filter

---

src/gatsby/src/components/megaMenu.js

CM-692
- If users click outside of the menu, the menu will close

CM-692: Update megamenu behaviour

---

src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
src/admin/src/utils/AdvisoryDataUtil.js

CM-588
Changed the definition of "archived" to exclude these statuses:
- Draft
- Approval requested
- Approved

CM-588: Change the definition of archived

---

src/gatsby/src/components/advisories/advisoryCard.js

CM-756
- Add site name to the park button to display [park name] – [site name] on active advisories page

CM-756: Add site name to the park button on active advisories page

---

src/gatsby/src/pages/active-advisories.js
src/gatsby/src/pages/find-a-park.js
src/gatsby/src/styles/home.scss
src/gatsby/src/styles/staticContent1.scss
src/gatsby/src/templates/parkSubPage.js

CM-701
- Add breadcrumbs to the active advisories page
- Fix the breadcrumbs layout issue that Amanda mentioned in the ticket

CM-701: Fix breadcrumbs issues

---

src/gatsby/src/components/park/about.js

CM-364
- Hide park size if there is no data

CM-364: Hide park size if there is no data

---

src/gatsby/src/styles/megaMenu/megaMenu.scss

CM-753
- Change megamenu height

CM-753: Change megamenu height

---

src/gatsby/src/styles/global.scss

CM-746
Fix the spacing issue under the standard callout text

CM-746: Fix spacing issue under the standard callout text

---

src/gatsby/src/styles/advisories/advisoryCard.scss

CM-747
- Fix the spacing issues on active advisories page

CM-747: Fix spacing issues on active advisories page

---

src/gatsby/src/pages/about/management-plans/approved.js

CM-772
- Change hyphen to en dash between park name and site name on approved page

CM-772: Change hyphen to en dash between park name and site name on approved page

---

src/gatsby/src/templates/parkSubPage.js

CM-774
- Add more useref to parksubpage sections

CM-774: Add more useref to parksubpage sections

---

src/gatsby/src/components/megaMenu.js
src/gatsby/src/styles/megaMenu/megaMenu.scss

CM-776
- Update megamenu styling based on the new mockup

CM-776: Update megamenu styling

---

src/gatsby/src/components/park/campingDetails.js

CM-367
- Replace the word "rv-accessible" with "RV-accessible"
- Could not use the word just "rv" as it will replace randomly (e.g. reseRVable)

CM-367: Change rv in uppercase

---

src/gatsby/src/pages/about/management-plans/approved.js

CM-731
- Remove underline from breadcrumbs when it's not hovered

CM-731: Remove underline from breadcrumbs

---

.github/workflows/build-dev.yaml
.github/workflows/publish-gatsby.yaml

None
Added cancel-in-progess flags to builds to reduce overall impact on the bcgov GitHub organization

NOBUG: Add concurrency checks to GitHub actions

---

src/cms/database/migrations/2023.06.26T00.00.06.access-status.js

CM-652
Updates to access statuses

CM-652: Access status updates

---

src/gatsby/src/templates/parkSubPage.js
src/gatsby/src/templates/staticContent1.js

CM-774
- Change scroll spy offset

CM-774: Change scroll spy offset

---

src/gatsby/src/styles/global.scss
src/gatsby/src/styles/parks.scss
src/gatsby/src/styles/staticLanding1.scss

CM-731
- Update breadcrumbs styling

CM-731: Update breadcrumbs styling

---

src/cms/database/migrations/2023.06.26T00.00.06.access-status.js

CM-652
Updates to access status to match manually entered data.  Changed the "where" clause to use `id` so it wouldn't conflict with manual changes.

CM-652: Update access statuses

---

src/gatsby/src/pages/find-a-park.js

CM-796
- Change the "see all" anchor link based on camping/facility/activity icons

CM-796: Change anchor link based on camping/facility/activity icons

---

src/cms/src/api/public-advisory/controllers/public-advisory.js
src/gatsby/src/archived/intro.js

CM-801
Removed fields from this API call that are never used on the website.  The lists grow very large when a public advisory is associated with many parks.

CM-801: Remove unused fields from public-advisories/items

---

src/gatsby/src/components/advisories/advisoryFilter.js

CM-802
Fixed an issue where the value was being lost when the input lost focus

CM-802: Fixed issue with event type dropdown

---

src/gatsby/src/pages/find-a-park.js
src/gatsby/src/styles/search.scss

CM-812
- Update the pagination text based on the new design

CM-812: Update pagination text

---

src/cms/database/migrations/2023.06.26T00.00.06.access-status.js

CM-652, CM-810
Reverted changes to AccessStatuses where it would conflict with manual changes made on PROD

CM-652: Revert changes to AccessStatus.id 5 & 9

---

src/cms/src/api/public-advisory/services/public-advisory.js
src/gatsby/src/components/advisories/advisoryCard.js

None
- Fix active advisory error

NOBUG: Fix active advisory error

---

src/gatsby/src/styles/parks.scss

CM-826
- Changed photo gallery caption alignment to center

CM-826: Changed photo gallery caption alignment

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js

CM-798
- Add max length to headline text field

CM-798: Add max length to headline text field

---

src/gatsby/src/components/search/parkLinksModal.js
src/gatsby/src/pages/find-a-park.js
src/gatsby/src/pages/parks.js
src/gatsby/src/styles/search.scss
src/gatsby/src/styles/variables.scss

CM-198
- Update the parks listing page based on the new design
- Update the find a park page based on the new design
- Add "more ways to find a park" button/modal to find a park page on mobile

CM-198: Update parks listing page

---

src/gatsby/src/styles/parks.scss
src/gatsby/src/styles/search.scss

CM-652
- Fix icon size and alignment on mobile

CM-652: Fix icon size issue

---

src/gatsby/src/components/park/parkPhotoGallery.js
src/gatsby/src/styles/parks.scss

CM-826
- Update park photo gallery functions (zoom, full screen, and slideshow)
- Fix the caption alignment issue

CM-826: Update park photo gallery functions

---

src/gatsby/src/components/park/parkPhotoGallery.js
src/gatsby/src/styles/parks.scss

CM-826
- Change the photo gallery image height shorter based on Amanda's comment

CM-826: Change photo gallery image height

---

src/gatsby/src/styles/staticContent1.scss

CM-650
- Update card border styling based on Amanda's comment

CM-650: Update card styling

---

src/gatsby/src/components/park/parkPhotoGallery.js
src/gatsby/src/styles/parks.scss

CM-826
- Update photo gallery arrow icon styling
- Fix the show photo button function on mobile

CM-826: Update photo gallery arrow icon styling

---

src/gatsby/src/pages/about/management-plans/approved.js
src/gatsby/src/pages/parks.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
src/gatsby/src/styles/listPage.scss

CM-832
- Fix spacing issue on A–Z park listing/Approved management plans/Park operating dates page
- Change the wording "No (first come, first served)" to "N/A"

CM-832: Fix spacing issue on parks page

---

src/gatsby/src/components/search/parkLinksModal.js
src/gatsby/src/pages/find-a-park.js

CM-833
- Change the map link to open in a new tab

CM-833: Change map link to open in new tab

---

src/gatsby/src/pages/about/management-plans/approved.js
src/gatsby/src/styles/listPage.scss

CM-834
- Add focus-visible state to filter buttons so tabbing them looks more visible

CM-834: Add focus-visible state to filter buttons

---

src/gatsby/src/pages/find-a-park.js
src/gatsby/src/styles/search.scss

CM-838
- Add 40 px of padding to the bottom of the Find a Park page

CM-838: Add space to the bottom of find a park page

---

src/gatsby/src/styles/search.scss

CM-840
- Change the font size of find a park filter buttons on mobile

CM-840: Change font size of find a park filter buttons on mobile

---

src/gatsby/src/pages/about/management-plans/approved.js
src/gatsby/src/pages/parks.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
src/gatsby/src/styles/staticContent1.scss

CM-841
- Update breadcrumbs spacing on unique pages on mobile

CM-841: Update breadcrumbs spacing on unique pages on mobile

---

src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CM-845
- Add a new line to n/a on mobile

CM-845: Add a new line to n/a on mobile

---

src/gatsby/src/styles/listPage.scss

CM-842
- Remove bullet points from list on the park operating dates page

CM-842: Remove bullet points from list

---

src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CM-843
- Change to to dash at operating dates range

CM-843: Change to to dash at operating dates range

---

src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CM-846
- Remove the alphabet heading
- Change some wordings
- Display "first come, first served" if the facilityType.isCamping is true

CM-846: Change wording on park operating dates page

---

src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CM-846
- Changed hyphen to "to" when used in a sentence on the dates page
- Fixed logic error that was preventing 'year round' from appearing.

CM-846: Change hyphen to "to" when used in a sentence

---

src/elastic/scripts/indexParks.js
src/elastic/scripts/queueAllParks.js
src/elastic/transformers/park.js

CM-851
Fixed some errors causing the elasticmanager to fail

CM-851: Fixed errors in elasticmanager

---

src/elastic/index.js
src/elastic/transformers/park.js

CM-851
Fixed some date-related indexing errors on the alpha-dev environment

CM-851: Fixed indexing errors on OpenShift

---

infrastructure/helm/bcparks/templates/elasticmanager/elasticmanager-deployment.yaml
src/cms/README.md
src/elastic/index.js
src/elastic/scripts/indexParks.js

CM-851
Fixed failing health checks on the elasticmanager pod

CM-851: Fixed health checks

---

infrastructure/helm/bcparks/templates/elasticmanager/elasticmanager-deployment.yaml
src/elastic/index.js

CM-851
Fixed OpenShift health checks for elasticmanager

CM-851: Fixed health checks #2

---

infrastructure/helm/bcparks/templates/elasticmanager/elasticmanager-deployment.yaml
src/elastic/livenessProbe.sh

CM-851: Fixed health checks #3

---

infrastructure/helm/bcparks/templates/elasticmanager/elasticmanager-deployment.yaml
src/elastic/index.js
src/elastic/livenessProbe.sh

CM-851: Fixed health checks #4

---

src/elastic/scripts/indexParks.js
src/elastic/server.js
src/elastic/utils/taskQueue.js

CM-851
- Fix error where linux behaved different than powershell when quoting strings
- Added better logging for errors
- Made cron logging less verbose

CM-851: Fixed health checks & better logging

---

src/elastic/scripts/createParkIndex.js
src/elastic/scripts/deleteParkIndex.js
src/elastic/scripts/indexParks.js
src/elastic/utils/elasticClient.js

CM-851
- Removed process.exit() calls to prevent pods from restarting
- Cleaned up logging

CM-851: Removed process.exit() calls to prevent pods restarting

---

src/cms/src/api/search/services/search.js
src/elastic/health.sh
src/elastic/index.js
src/elastic/scripts/indexParks.js
src/elastic/server.js

CM-851
Converted health check from node to bash to fix timeout issues when starting node (bash should be much faster)

CM-851: Converted health check from node to bash

---

infrastructure/helm/bcparks/templates/elasticmanager/elasticmanager-deployment.yaml
infrastructure/helm/bcparks/values.yaml
src/cms/src/api/search/controllers/search.js
src/cms/src/api/search/routes/search.js
src/cms/src/api/search/services/search.js
src/elasticmanager/.env.example
src/elasticmanager/index.js
src/elasticmanager/scripts/indexParks.js
src/elasticmanager/server.js
src/elasticmanager/utils/taskQueue.js

CM-851
- Made the batch size configurable
- Reversed the order of the task queue for maintenance script calls
- Renamed some API calls
- Made new API calls private / require auth

CM-851: Refactored indexing code

---

infrastructure/helm/bcparks/values-alpha-test.yaml
infrastructure/helm/bcparks/values-prod.yaml
infrastructure/helm/bcparks/values-test.yaml
infrastructure/helm/bcparks/values.yaml
src/cms/src/api/search/services/search.js

CM-851
Openshift tuning and search optimization

CM-851: Openshift tuning and search optimization

---

src/cms/src/api/search/controllers/search.js
src/cms/src/api/search/services/search.js
src/elasticmanager/transformers/park.js

CM-854
Add Elasticsearch terms aggregations to search results

CM-854: Add aggregations to search results

---

src/cms/src/api/search/controllers/search.js
src/cms/src/api/search/services/search.js
src/elasticmanager/transformers/park.js
src/gatsby/src/pages/find-a-park.js

CM-851
Fixed missing icons on the find a park page

CM-851: Fixed missing icons

---

src/cms/src/api/search/controllers/search.js
src/cms/src/api/search/services/search.js
src/elasticmanager/transformers/park.js
src/gatsby/src/pages/find-a-park.js

CM-851
Use facilityNumber and activityNumber for filters instead of using id's

CM-851: Use facilityNumber and activityNumber for filters instead of ids

---

src/gatsby/src/pages/about/management-plans/approved.js
src/gatsby/src/pages/parks.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
src/gatsby/src/styles/listPage.scss

CM-864
Added extra CSS scoping to fix missing link cards. This is a hotfix, and a permanent solution will be found later.

CM-864: Fix missing link cards

---

src/gatsby/src/components/park/campingDetails.js

CM-379
- Add a dynamic id to the camping accordion
- Add an id "reservation" to the reservation accordion

CM-379: Add id to camping accordions

---

src/gatsby/src/pages/find-a-park.js
src/gatsby/src/styles/search.scss

CM-869
- Update find a park card styling to wrap icons

CM-869: Update find a park card styling

---

src/cms/src/api/protected-area/services/search.js

None
Accidentally removed park photos in #910

NOBUG: Add missing park photos

---

src/gatsby/src/utils/helpers.js

None
- Prevent infinite console errors when the park image is broken

NOBUG: Update handleImgError function

---

src/gatsby/src/components/park/parkPhotoGallery.js

CM-877
- Stop the photo slides infinite looping

CM-877: Stop photo slides loop

---

src/gatsby/gatsby-config.js
src/gatsby/src/components/search/mainSearch.js
src/gatsby/src/components/search/noSearchResults.js
src/gatsby/src/components/search/parkCard.js
src/gatsby/src/components/search/searchFilter.js
src/gatsby/src/pages/find-a-park.js
src/gatsby/src/styles/search.scss

CM-675
CM-792
CM-793
CM-821
CM-822
CM-875
- Update popular filter
- Add region filter
- Add camping filter
- Add filter count
- Remove pagination and add Load more button
- Update the Find a Park page UI

CM-792: Add region filter and camping filter for search

---

src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/components/park/campingDetails.js
src/gatsby/src/components/park/parkActivity.js
src/gatsby/src/components/park/parkDates.js
src/gatsby/src/components/park/parkFacility.js
src/gatsby/src/styles/cmsSnippets/parkInfoPage.scss

CM-673
- Add expand/collapse all button to activity/facility/camping/dates of operation section
- Update expand/collapse all button for advisories section

CM-673: Add expand/collapse all button to accordions

---

src/cms/src/plugins/strapi-plugin-ckeditor/admin/src/components/Input/CKEditor/configs/base.js

https://bcparksdigital.atlassian.net/browse/CM-554
Added a decorator to the link widget that adds the button classes. Neat!

CM-554: add button option to link button

---

src/gatsby/src/templates/park.js

CM-858
- It works the same as before on my local, but I'm not sure the back button issue will be fixed on the live site
- Testing it on Alpha-dev after merging

CM-858: Fix back button issue on park page

---

src/gatsby/src/components/search/desktopFilters.js
src/gatsby/src/components/search/filter.js
src/gatsby/src/components/search/mobileFilters.js
src/gatsby/src/pages/find-a-park.js

CM-792
- Renamed searchFilter to mobileFilters
- Split desktopFilters into a separate file and reduced duplication with mobileFilters.

CM-792: Refactor filters

---

src/cms/src/api/protected-area/custom/protected-area-search.js
src/cms/src/api/protected-area/services/search.js
src/elasticmanager/transformers/park.js
src/gatsby/src/pages/find-a-park.js

CM-888
Note: You will need to rebuild your search index after merging this change.

CM-888: Use OR filters for camping

---

src/gatsby/src/components/search/noSearchResults.js
src/gatsby/src/pages/find-a-park.js
src/gatsby/src/styles/search.scss

CM-886
- Add an external link icon to the map link on noSearchResults
- Changed the position of filters on a laptop screen
- Make the clear text icon in the search bar tabbable
- Set focus on the search bar when the page loads

CM-886: Changed layout of find a park page

---

src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/components/park/campingDetails.js
src/gatsby/src/components/park/parkActivity.js
src/gatsby/src/components/park/parkDates.js
src/gatsby/src/components/park/parkFacility.js
src/gatsby/src/styles/cmsSnippets/parkInfoPage.scss

CM-673
- Hide the expand/collapse all button if there is one accordion
- Change an arrow icon size and position

CM-673: Hide expand/collapse all button if there is one accordion

---

src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/components/park/parkAccessStatus.js
src/gatsby/src/components/search/desktopFilters.js

None
- Access status was missing from search results due to properties being renamed
- Fixed some console warnings

NOBUG: Fix missing access statuses and console warnings

---

src/gatsby/package-lock.json
src/gatsby/package.json
src/gatsby/src/pages/find-a-park.js

CM-861
Implemented bookmarkable search URLs

CM-861: Bookmarkable search URLs
