src/gatsby/src/pages/find-a-park.js

CM-861
Added back the location state check for the search text field

CM-861: Fix broken search from main page

---

src/gatsby/src/pages/find-a-park.js

CM-891
- Refresh results by clicking the clear icon
- Search function will work every time the clear icon is clicked

CM-891: Refresh results by clicking clear icon

---

src/gatsby/src/styles/search.scss

CM-889
- Update disabled checkbox colour

CM-889: Update disabled checkbox colour

---

src/gatsby/src/pages/find-a-park.js

CM-861
Made pagination bookmarkable

CM-861: Bookmarkable pagination

---

src/gatsby/src/pages/find-a-park.js
src/gatsby/src/styles/search.scss

CM-886
- Add autofocus to the search bar when the Find a park page is loaded (Annotation #B on Figma)

CM-886: Add autofocus to search bar when find a park page is loaded

---

src/gatsby/gatsby-browser.js
src/gatsby/src/components/search/parkCard.js
src/gatsby/src/styles/global.scss
src/gatsby/src/templates/park.js

CM-887
Use simulated back button for navigating back to the find-a-park page from park pages

CM-887: Find-a-park breadcrumb navigation behaviour

---

.github/workflows/build-dev.yaml
.github/workflows/on-pr.yaml
.github/workflows/publish-gatsby.yaml

None
Update GitHub actions to fix deprecation warnings

NOBUG: Bump Github actions to node16 versions

---

src/gatsby/src/components/search/filter.js

CM-899
- Make filter label wrapped if there is no much space

CM-899: Make filter label wrapped if there is no much space

---

src/gatsby/src/components/search/filter.js
src/gatsby/src/pages/find-a-park.js

CM-900
- Add onKeyDown to the clear filters button

CM-900: Add onKeyDown to clear filters button

---

src/gatsby/src/styles/search.scss

CM-899
- Make the checkbox and filter label aligned to the top

CM-899: Make checkbox and filter label aligned to top

---

src/gatsby/src/components/pageContent/pageMenu.js
src/gatsby/src/styles/pageContent/pageMenu.scss

CM-703
- To change the position of the select field dropdown icon, another `<div>` was needed as I can't use `after` to `<select>`
- Hid the default select field dropdown icon and added another icon to the parent `<div>`

CM-703: Change select field dropdown icon

---

src/gatsby/src/components/park/parkDates.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CM-855
CM-894
- CM-855: Display off season dates information  on mobile even if its data is limited
- CM-894: Change the order of reservable dates and off season dates

CM-894: Change order of reservable dates and off season dates

---

src/gatsby/src/components/park/parkDates.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
src/gatsby/src/templates/park.js

CM-893
- Update park operation dates wording/logic on the park page

CM-893: Update park operation dates wording on park page

---

src/gatsby/src/styles/pageContent/pageMenu.scss

CM-703
- Update select field dropdown icon size

CM-703: Update select field dropdown icon size

---

src/elasticmanager/package-lock.json
src/elasticmanager/package.json
src/elasticmanager/transformers/park.js
src/gatsby/src/components/search/parkCard.js
src/gatsby/src/pages/find-a-park.js

CM-906
Removed the wilderness camping filter, and converted all wilderness camping facilities to backcountry camping.  
Also fixed a bug where the backcountry camping and vehicle-accessible camping icons were missing.

CM-906: Combine backcountry camping and wilderness camping

---

src/gatsby/src/styles/search.scss

CM-890
- Display carousel nav icons without hovering on tablet and mobile

CM-890: Display carousel nav icons on tablet and mobile

---

src/gatsby/src/styles/search.scss

CM-872
- Add text wrap to the park card heading

CM-872: Add text wrap to the park card heading

---

src/gatsby/src/pages/about/management-plans/approved.js

None
Fix failing build on alpha-test

NOBUG: Fix a data-related issue causing alpha-test Gatsby build to fail

---

src/gatsby/src/styles/parks.scss

CM-911
- Update the focus visible state for park access status link on the park page

CM-911: Update focus visible state for park access status on park page

---

src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/components/park/campingDetails.js
src/gatsby/src/components/park/parkActivity.js
src/gatsby/src/components/park/parkDates.js
src/gatsby/src/components/park/parkFacility.js

CM-912
- Add onKeyDown to collapse/expand all button for accordions

CM-912: Add onKeyDown to collapse/expand all button for accordions

---

src/elasticmanager/transformers/park.js

CM-906
Fixed a coding error that was causing lodash uniqBy to behave incorrectly.  Re-indexing is required after this change.

CM-906: Fix bug combining wilderness camping with backcountry camping

---

src/gatsby/gatsby-browser.js

CM-774
Disable manual scroll restoration on urls with an anchor hash

CM-774: Disable manual scroll restoration on urls with a hash

---

src/gatsby/src/pages/find-a-park.js

CM-934
Fix for bug "Refreshing the reset the filter logic but leave the pills displayed"

CM-934: Fix for race condition loading bookmarkable URLs

---

src/gatsby/src/components/search/filter.js
src/gatsby/src/components/search/mobileFilters.js
src/gatsby/src/styles/search.scss

CM-791
- Change material ui checkbox styling
- Update checkbox size bigger
- Update checkbox border width thinner
- Change expand/collapse arrow icon colour

CM-791: Change material ui checkbox styling

---

src/gatsby/src/components/park/about.js
src/gatsby/src/templates/park.js

CM-808
- Add park size details (`uplandArea` and `marineArea`) to the marine park page

CM-808: Add park size details to marine park page

---

src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CM-863
- Update preamble text on the park operating dates page
- Update the park operating dates page meta description

CM-863: Update preamble text on park operating dates page

---

src/gatsby/src/templates/park.js

CM-941
Added missing `preventDefault()`

CM-941: Fix bug navigating with breadcrumb

---

src/gatsby/src/components/park/about.js

CM-808
- Add a fallback to park size text on marine park page

CM-808: Add a fallback to park size text

---

src/gatsby/src/components/search/mobileFilters.js
src/gatsby/src/pages/find-a-park.js
src/gatsby/src/styles/search.scss

CM-909
- Add a clear filters button to filter modal on mobile
- Add a close button to filter modal on mobile

CM-909: Add clear filters button to filter modal on mobile

---

src/gatsby/src/components/search/filter.js
src/gatsby/src/styles/search.scss

CM-945
CM-946
- Make each filter checkbox tab-able
- Update checkbox styling

CM-946: Make each filter checkbox tab-able

---

src/gatsby/src/components/footer.js
src/gatsby/src/components/megaMenu.js
src/gatsby/src/pages/index.js

CM-686
- Remove blurred effect from Gatsby Static Image when images are loading
https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/#placeholder

CM-686: Fix blurred logo images

---

infrastructure/aws-opensearch/README.md
infrastructure/kong/clean.js

CM-856
Documentation updates for Elasticsearch deployment

CM-856: Elasticsearch documentation updates

---

src/gatsby/src/components/park/about.js

CM-808
-  Format area size number with a thousands separator

CM-808: Format area size number with a thousands separator

---

src/gatsby/src/components/search/desktopFilters.js

CM-946
- Add keyDown event to filters show all button

CM-946: Add keyDown event to filters show all button

---

src/gatsby/src/styles/global.scss

CM-950
- Add global styling to the primary button

CM-950: Add global styling to primary button

---

src/gatsby/gatsby-config.js

CM-782
CM-782: Fix failing build caused by gatsby-source-strapi config

CM-782: Fix failing build caused by gatsby-source-strapi config

---

src/gatsby/gatsby-config.js

None
Minor changes to GraphQL to make gatsby builds faster

NOBUG: Performance tuning Gatsby builds

---

src/elasticmanager/transformers/park.js
src/elasticmanager/utils/taskQueue.js

None
- Reverted code accidentally deleted for CM-495
- Don't call bulk-delete with an empty list of ids

NOBUG: Elasticmanager fixes

---

src/gatsby/src/components/park/parkDates.js

CM-927
- Change wording from Main operating season dates to Main operating season

CM-927: Change wording from Main operating season dates to Main operating season

---

src/cms/src/api/protected-area/controllers/protected-area.js
src/cms/src/api/protected-area/services/protected-area.js

None
Undelete the old search code so find-a-park still works while we are completing manual deployment steps

NOBUG: add back old search code so find-a-park works during deployment

---

src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
src/gatsby/src/styles/listPage.scss

CM-863
- Update intro text styling with a update request by Amanda
- 8px between list items
- Reduce width of paragraph to 900px
- Indent list items by 40px

CM-863: Update intro text styling

---

src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CM-863
- Change the order of description on the park operating dates page

CM-863: Change order of description on park operating dates page

---

src/elasticmanager/scripts/indexParks.js

CM-966
This fixes a bug introduced by #972

CM-966: Hotfix for error removing parks from Elasticsearch

---

src/gatsby/src/components/scrollToTop.js

CM-513
- Add a white outline to scroll to the top button

CM-513: Add white outline to scroll to top button

---

src/gatsby/src/components/search/filter.js
src/gatsby/src/pages/find-a-park.js

CM-915
- Shorten filter checkbox label and chip label

CM-915: Shorten filter label

---

src/gatsby/src/pages/active-advisories.js
src/gatsby/src/pages/index.js

CM-800
- Add scroll to top button to active advisories page and home page

CM-800: Add scroll to top button to active advisories page and home page

---

src/gatsby/src/templates/staticContent1.js

CM-91
- Add more useRef to section on staticContent page

CM-91: Add more useRef to section on staticContent page

---

src/gatsby/src/components/campfireBan.js
src/gatsby/src/components/park/advisory.js
src/gatsby/src/components/park/parkAccessStatus.js
src/gatsby/src/templates/park.js

None
- Fix react warning by changing class to className

NOBUG: Fix react warning by changing class to className

---

src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CM-951
- Add campfire icon to the site page

CM-951: Add campfire icon to site page

---

src/gatsby/src/components/park/parkDates.js

CM-942
- Update wording in the dates of operation section on the park page
- Update winter season information as the same as the park operation dates page

CM-942: Update wording in dates of operation section on park page

---

src/cms/src/plugins/strapi-plugin-ckeditor/admin/src/components/Input/CKEditor/theme/common.js

CM-961
- Update list styling CSS for ck editor

CM-961: Update list styling CSS for ck editor

---

src/gatsby/__tests__/components/__snapshots__/footer.test.js.snap
src/gatsby/src/components/footer.js
src/gatsby/src/styles/footer.scss
src/gatsby/src/styles/megaMenu/megaMenu.scss

CM-687
- Update header and footer layout, spacing
- Update the Book Camping button size

CM-687: Update header and footer layout

---

src/cms/src/api/site/content-types/site/schema.json
src/gatsby/src/templates/site.js

CM-564
- Add safety info to the site page
- Create safetyInfo field in the site collection

CM-564: Add safety info to site page

---

src/gatsby/src/styles/parks.scss
src/gatsby/src/styles/search.scss

CM-953
CM-954
CM-955
CM-956
- Update the park access status link colour on the Find a Park page
- Update show all link underline colour on the Find a Park page
- Update book camping button hover style
- Update heading underline colour

CM-953: Update park access status link colour

---

src/gatsby/src/templates/park.js
src/gatsby/src/templates/parkSubPage.js
src/gatsby/src/templates/site.js

CM-962
- Keep search query on site page and park sub page

CM-962: Keep search query on site page and park sub page

---

src/elasticmanager/scripts/indexParks.js
src/elasticmanager/scripts/populateGeoShapes.js

CM-963
This fixes some issues discovered after deploying to alpha-dev.

CM-963: Fix Elastic indexer cron errors & increase openmaps timeout

---

infrastructure/kong/clean.js
src/elasticmanager/scripts/populateGeoShapes.js
src/elasticmanager/server.js

CM-963
- Populate geo-shapes with the cron scheduler
- Exclude geo-shapes from Kong API

CM-963: More updates to geo-shapes

---

src/gatsby/src/styles/parks.scss

CM-955
- Change the book camping button background colour to transparent

CM-955: Change book camping button background colour to transparent

---

src/gatsby/src/styles/footer.scss

CM-687
- Change footer item spacing

CM-687: Change footer item spacing

---

src/gatsby/src/components/search/desktopFilters.js
src/gatsby/src/components/search/filter.js
src/gatsby/src/components/search/mobileFilters.js
src/gatsby/src/pages/find-a-park.js

CM-915
- In the Popular filter, “Backcountry camping” will be “Backcountry camping” 
- In the Popular filter, “Vehicle-accessible camping” will be “Vehicle camping” 
- In the Camping filter, “Backcountry camping” will be “Backcountry”
- In the Camping filter, “Vehicle-accessible camping” will be “Vehicle”

CM-915: Add camping to filter label in popular filter

---

src/gatsby/src/components/advisories/advisoryCard.js
src/gatsby/src/styles/advisories/advisoryCard.scss

CM-985
- Update park/additional park pills layout on the active advisories page

CM-985: Update park pills layout on active advisories page

---

src/gatsby/src/styles/megaMenu/megaMenu.scss

CM-981
- Update megamenu item spacing

CM-981: Update megamenu item spacing

---

src/gatsby/gatsby-node.js

CM-564
- Fix graphql type def error for safetyInfo so that data is rendered on the Site page

CM-564: Fix graphql type def for safetyInfo

---

src/gatsby/src/styles/global.scss
src/gatsby/src/styles/pageContent/pageSection.scss

CM-961
- Move nested list style to global.scss

CM-961: Move nested list style to global

---

src/cms/src/api/protected-area/custom/protected-area-search.js
src/cms/src/api/protected-area/services/search.js

CM-965
Implemented more features after a discussion with UX about how pagination will work.
1. Ability to set `_limit=0` for getting a count with no results or aggregations
2. Ability to pass a `radius` parameter which acts as a filter for distance away (in kilometres)
3. Added distance to the park results for all searches with a `near` parameter
4. Changed the meta pagination style to match the way Strapi normally returns pagination for start/limit ([pagination by offset](https://docs.strapi.io/dev-docs/api/rest/sort-pagination#pagination-by-offset)). It was previously using Strapi's convention for page/pageSize ([pagination by page](https://docs.strapi.io/dev-docs/api/rest/sort-pagination#pagination-by-page))
API usage examples:
Get the number of results within 50km of Cloverdale, but …

CM-965: Back-end for radius search part 2

---

src/gatsby/src/styles/global.scss

CM-133
- Add mobile table styling

CM-133: Add mobile table styling

---

src/gatsby/src/components/park/about.js
src/gatsby/src/components/park/accessibilityDetails.js
src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/components/park/campingDetails.js
src/gatsby/src/components/park/mapLocation.js
src/gatsby/src/components/park/natureAndCulture.js
src/gatsby/src/components/park/parkActivity.js
src/gatsby/src/components/park/parkDates.js
src/gatsby/src/components/park/parkFacility.js
src/gatsby/src/components/park/parkMapDetails.js
src/gatsby/src/components/park/parkOverview.js
src/gatsby/src/components/park/reconciliation.js
src/gatsby/src/components/park/safetyInfo.js
src/gatsby/src/components/park/spacer.js
src/gatsby/src/components/park/specialNote.js
src/gatsby/src/styles/pageContent/pageMenu.scss
src/gatsby/src/styles/pageContent/pageSection.scss
src/gatsby/src/styles/parks.scss
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CM-239
- Add spacing to the top of each page section so that users can see some space on top of the section when they click the side menu

CM-239: Add spacing to top of each page section

---

src/gatsby/src/components/megaMenu.js
src/gatsby/src/styles/megaMenu/megaMenu.scss
src/gatsby/src/templates/site.js

CM-853
- Change megamenu HTML structure so that users can tab through sub-menu items when they click one of the main menu items
- Code cleanup at site.js

CM-853: Change megamenu HTML structure

---

infrastructure/helm/bcparks/values-prod.yaml

None
Decrease memory limits to reduce limits.cpu overutilization on PROD _(already applied changes to prod, just adding them to source control now)_

NOBUG: decrease memory limits to reduce limits.cpu overutilization

---

src/elasticmanager/scripts/indexParks.js
src/elasticmanager/scripts/populateGeoShapes.js
src/elasticmanager/scripts/queueAllParks.js
src/elasticmanager/server.js
src/elasticmanager/transformers/park.js
src/elasticmanager/utils/axiosConfig.js
src/elasticmanager/utils/taskQueue.js

CM-1022
- Fix elasticmanager cron concurrency issue by checking the count of running jobs before starting a new job
- Fix elasticmanger SSL errors by setting `rejectUnauthorized: false` in the axios config
NOTE: I set this to merge into main in case we end up doing a hotfix release.

CM-1022: Fix elasticmanager SSL and cron concurrency errors

---

src/gatsby/src/components/park/parkDates.js
src/gatsby/src/templates/park.js

CM-947
- Update wording and the order of text for the dates of operation on the park page

CM-947: Update wording for dates of operation on park page

---

src/gatsby/src/components/search/parkCard.js
src/gatsby/src/pages/find-a-park.js
src/gatsby/src/styles/search.scss

CM-919
When paginating with the keyboard, automatically set focus to the first item on the next results page.

CM-919: Find-a-park accessibility - focus 1st park on next result page

---

src/gatsby/src/pages/about/management-plans/approved.js

CM-1024
- Add preamble and meta description to approved management plan page

CM-1024: Add preamble to approved management plan page

---

src/gatsby/src/components/search/parkLinksModal.js
src/gatsby/src/pages/find-a-park.js
src/gatsby/src/pages/find-a-park/a-z-list.js

CM-1001
- Change A-Z list page URL from `/parks` to `/find-a-park/a-z-list`
- Change A-Z list page title from "A-Z park listing" to "A-Z park list"

CM-1001: Change A-Z list page URL and title

---

src/gatsby/src/components/park/advisory.js

CM-1002
- Update advisory text on the park page when there are no advisories

CM-1002: Update advisory text on park page when there are no advisories

---

src/gatsby/src/styles/cmsSnippets/parkInfoPage.scss
src/gatsby/src/styles/parks.scss
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CM-1031
- Update link styling on the park page

CM-1031: Update link styling on park page

---

src/gatsby/src/components/park/parkDates.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CM-947
- Update park operating dates wording

CM-947: Update park operating dates wording

---

src/gatsby/src/components/search/noSearchResults.js
src/gatsby/src/components/search/parkLinksModal.js
src/gatsby/src/pages/find-a-park.js

CM-1001
- Fix the A-Z park list page link from `/parks` to `/find-a-park/a-z-list`

CM-1001: Fix A-Z park list page link

---

src/cms/src/api/park-photo/content-types/park-photo/schema.json
src/gatsby/src/components/park/parkPhotoGallery.js
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CM-881
Use CKEditor for photo gallery captions

CM-881: Change photogallery captions to rich text

---

src/gatsby/src/components/park/parkDates.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CM-943
- Update winter season information when there is no subArea.operationDates

CM-943: Update winter season information when there is no subArea.operationDates

---

src/admin/src/components/composite/advisoryAreaPicker/AdvisoryAreaPicker.js
src/admin/src/components/composite/advisoryAreaPicker/AdvisoryAreaPicker.test.js
src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/composite/advisorySummaryView/AdvisorySummaryView.js
src/admin/src/components/page/advisory/Advisory.js
src/admin/src/utils/AdvisoryUtil.js
src/admin/src/utils/CmsDataUtil.js
src/admin/src/utils/LocationUtil.js
src/admin/src/validators/AdvisoryValidator.js

CM-647
CM-747: Update the advisory form function/layout based on the new design: https://www.figma.com/file/Bjcwiimk6UElI2yAucmXiU/BC-Parks---Staff-portal?type=design&node-id=1%3A1508&mode=design&t=WVL19BeW1Obky7jd-1
Note: I had to create a new PR because GitHub wouldn't let me add @ayumi-oxd as a reviewer for #841

CM-647: Update advisory form

---

src/gatsby/package-lock.json
src/gatsby/package.json
src/gatsby/src/components/search/cityNameSearch.js
src/gatsby/src/components/search/mainSearch.js
src/gatsby/src/components/search/noSearchResults.js
src/gatsby/src/components/search/parkNameSearch.js
src/gatsby/src/components/search/permissionToast.js
src/gatsby/src/pages/find-a-park.js
src/gatsby/src/styles/home.scss
src/gatsby/src/styles/search.scss
src/gatsby/src/styles/variables.scss
src/gatsby/src/utils/helpers.js

- CM-1004
- CM-1005
- CM-1006
- CM-1007
- CM-1008
- CM-1009
- CM-1010
- CM-1036
- CM-1039
- CM-1004: Update error page
- CM-1005: Add autocomplete near a city field to find a park page
- CM-1006: Add autocomplete near a city field to home page
- CM-1007: Add end of results text to find a park page
- CM-1008: Add current location functionality to near a city field
- CM-1009: Update search results text on find a park page
- CM-1010: Update search text field styling
- CM-1036: Fix responsive layout issue on find a park page
- CM-1039: Update by park name field
- Searching from the Home page, the search result is correct but the park name field do not change

CM-1005: Add autocomplete near a city field

---

src/gatsby/src/components/search/noSearchResults.js
src/gatsby/src/styles/search.scss

CM-1058
- Fix a spacing issue on the error page
- Add text "Change your search term" when there is no result with park/city name

CM-1058: Fix spacing issue on error page

---

src/gatsby/__tests__/components/__snapshots__/footer.test.js.snap
src/gatsby/src/components/footer.js
src/gatsby/src/pages/site-map.js

CM-446
- Change sitemap to site map
- Change site map URL to `/site-map`

CM-446: Change sitemap to site map

---

src/gatsby/src/styles/pageContent/pageMenu.scss
src/gatsby/src/styles/parks.scss
src/gatsby/src/styles/staticContent1.scss

CM-1033
- Update link styling on content page

CM-1033: Update link styling on content page

---

src/gatsby/src/templates/parkSubPage.js

CM-939
- Change the parent container max-width to 1000px from 1140px
- Change the parent container side padding to 20px from 40px
- Change to 4 and 8 columns rather than the 3 and 9

CM-939: Update park sub page width

---

src/gatsby/src/styles/pageContent/pageMenu.scss
src/gatsby/src/styles/staticContent1.scss
src/gatsby/src/templates/staticContent1.js

CM-936
- Change the parent container max-width to 1000px from 1140px
- Change the parent container side padding to 20px from 40px
- Change to 4 and 8 columns rather than the 3 and 9

CM-936: Update static content page width

---

src/gatsby/src/styles/parks.scss
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CM-938
- Change the parent container max-width to 1000px from 1140px
- Change the parent container side padding to 20px from 40px
- Change to 4 and 8 columns rather than the 3 and 9

CM-938: Update park page and site page width

---

src/gatsby/src/components/search/parkNameSearch.js
src/gatsby/src/pages/find-a-park.js

CM-1067
- Fix the park name search issue with space and update the highlight text function for multiple search words

CM-1067: Fix park name search issue with space

---

src/gatsby/src/pages/find-a-park.js

CM-1069
- Update end results wording

CM-1069: Update end results wording

---

src/gatsby/src/components/search/mainSearch.js
src/gatsby/src/pages/index.js
src/gatsby/src/templates/staticLanding1.js

CM-1066
- Remove near a city field from the static landing page

CM-1066: Remove near a city field from static landing page

---

src/gatsby/__tests__/components/__snapshots__/footer.test.js.snap
src/gatsby/src/components/footer.js

CM-1070
- Change park use permits to park-use permits

CM-1070: Change park use permits to park-use permits

---

src/gatsby/src/components/search/cityNameSearch.js
src/gatsby/src/components/search/parkNameSearch.js
src/gatsby/src/components/search/permissionToast.js
src/gatsby/src/pages/find-a-park.js
src/gatsby/src/styles/search.scss

CM-1055
CM-1060
- Fix current location function issues
- If users deny sharing their current location, the city name search field will be cleared
- If users deny sharing their current location and they click the current location again, the toast message will change
- If users enter a city name that does not exist in the options, the city name search field will be cleared
- If users tab after the search, the city name search field will not be cleared
- If users hit the clear button, the dropdown will be closed
- If users hit the tab key, it will not select the first option automatically
- Some UI changes

CM-1055: Fix current location function issues

---

src/gatsby/src/components/search/parkNameSearch.js

None
- Change lowercase park options to camel-case

NOBUG: Fix lowercase park options issue

---

src/gatsby/src/components/search/cityNameSearch.js
src/gatsby/src/components/search/mainSearch.js
src/gatsby/src/components/search/parkNameSearch.js
src/gatsby/src/pages/find-a-park.js

None
- Users can select an option with the arrow keys and search parks with the enter key
- User can move to the next element with the tab key
- Reference: https://github.com/ericgio/react-bootstrap-typeahead/issues/461

NOBUG: Fix tabbing issue on find a park page

---

src/gatsby/src/components/park/parkDates.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CM-943
- Change winter season information wording when there is no subArea.operationDates

CM-943: Change winter season information wording when there is no subArea.operationDates

---

src/gatsby/src/styles/pageContent/pageMenu.scss
src/gatsby/src/styles/parks.scss
src/gatsby/src/styles/staticContent1.scss

CM-936, 938, 939
- Update static content page, park page, park sub page, and site page container width

CM-936: Update static content page, park page, park sub page, and site page container width

---

src/gatsby/src/styles/search.scss

CM-1068
- Fix label spacing issue

CM-1068: Fix label spacing issue

---

src/gatsby/src/components/park/parkDates.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

None
- Change of https://github.com/bcgov/bcparks.ca/pull/1081
- Sorry it wasn’t "No (first come, first served)", it should've been "Not known"

NOBUG: Change winter season information wording

---

src/gatsby/src/templates/park.js
src/gatsby/src/templates/parkSubPage.js
src/gatsby/src/templates/site.js
src/gatsby/src/templates/staticContent1.js

CM-936
- Change 2 column layout breakpoint on the park/park sub/site/static content page

CM-936: Change 2 column layout breakpoint

---

src/gatsby/src/components/search/parkNameSearch.js

CM-1104
- Fix the auto-suggest issue while a user is typing

CM-1104: Fix auto suggest issue while user is typing

---

src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CM-943
- Change wording from "N/A" to "first come first serve" under the booking required on the Park operating dates page

CM-943: Change wording from N/A to first come first serve under booking required

---

src/gatsby/src/pages/find-a-park.js

CM-1105
- Fix showing the error page before the search results
- Combine two requests because the bug happened since there were two axios requests and two `finally()`

CM-1105: Fix showing error page before search results

---

src/gatsby/src/components/search/parkCard.js
src/gatsby/src/utils/helpers.js

CM-1064
- Add fallback if the park card image URL is broken
- Display the BC Parks Logo image if a park image is not available

CM-1064: Add fallback if park card image URL is broken

---

src/gatsby/src/components/search/cityNameSearch.js

CM-1106
- Fix the issue when searching with a city when the access to the current location is on

CM-1106: Fix issue when searching with a city when the access to current location is on

---

src/gatsby/src/styles/search.scss

CM-1010
- Change search fields height from 48px to 50px

CM-1010: Change search fields height

---

src/gatsby/src/styles/parks.scss
src/gatsby/src/styles/staticContent1.scss

CM-936
- Narrow static content page, park page, park sub page, and site page container width

CM-936: Narrow static content page, park page, park sub page, and site page container width

---

src/gatsby/src/components/search/cityNameSearch.js
src/gatsby/src/components/search/mainSearch.js
src/gatsby/src/components/search/parkNameSearch.js
src/gatsby/src/pages/find-a-park.js

CM-1060
- Previously the auto-search function worked if the search term matched one of the options
- New change - a user will need to press the Enter key or the search button to search the results even if the search term matches one of the options

CM-1060: Remove auto search function if search term matches one of the options

---

src/gatsby/src/components/search/cityNameSearch.js
src/gatsby/src/components/search/mainSearch.js
src/gatsby/src/pages/find-a-park.js

CM-1124
- Fix issue when user enters park name and city name using keyboard

CM-1124: Fix issue when user enters park name and city name using keyboard

---

src/gatsby/src/components/search/cityNameSearch.js
src/gatsby/src/components/search/mainSearch.js
src/gatsby/src/pages/find-a-park.js

CM-1123
- Fix clear the city name issue

CM-1123: Fix clear the city name issue

---

src/gatsby/src/components/search/cityNameSearch.js
src/gatsby/src/components/search/mainSearch.js
src/gatsby/src/components/search/permissionToast.js
src/gatsby/src/pages/find-a-park.js

CM-1055
- Fix current location permission toast function

CM-1055: Fix current location permission toast function

---

src/gatsby/src/pages/find-a-park.js
src/gatsby/src/styles/home.scss
src/gatsby/src/styles/search.scss

CM-1126
- Fix the search fields layout on the home page

CM-1126: Fix the search fields layout on home page

---

src/gatsby/src/components/search/parkNameSearch.js
src/gatsby/src/pages/find-a-park.js

CM-1119
- Fix the park name search issue
- If there's no input text the search term will be cleared
- If there's no search term the dropdown will close

CM-1119: Fix park name search issue

---

src/gatsby/src/components/search/cityNameSearch.js
src/gatsby/src/components/search/mainSearch.js
src/gatsby/src/pages/find-a-park.js
src/gatsby/src/styles/megaMenu/megaMenu.scss

CM-1121
- Fix the spinning loading icon issue when a user selects "Current location" without permission
- Fix the toast overlapping issue
- Fix the Firefox permission issue

CM-1121: Fix current location spinning issue

---

src/gatsby/src/styles/search.scss

CM-1010
- Add focus outline to search fields

CM-1010: Add focus outline to search fields

---

src/gatsby/src/components/search/cityNameSearch.js

CM-1128
Removed the `useState` for hasResult and handled it on-the-fly instead.  I'm not 100% sure why this fixed the issue, and it would be a good idea to do a regression check on the issue that was being fixed when this useState was originally added.

CM-1128: Fix for infinite loop on city name search

---

src/gatsby/src/components/search/cityNameSearch.js
src/gatsby/src/components/search/parkNameSearch.js

CM-1129
- Change mobile device keyboard return button to search button
-  https://stackoverflow.com/questions/4864167/show-search-button-in-iphone-ipad-safari-keyboard

CM-1129: Change mobile device keyboard return button to search button

---

src/gatsby/src/components/search/cityNameSearch.js
src/gatsby/src/components/search/parkNameSearch.js
src/gatsby/src/pages/find-a-park.js

CM-1130
- Fix both search park field and search city field are being cleared

CM-1130: Fix both search park field and search city field are being cleared

---

src/gatsby/src/components/search/cityNameSearch.js

CM-1124
- Fix search park field being cleared issue

CM-1124: Fix search park field being cleared issue

---

src/gatsby/src/pages/find-a-park.js

CM-1125
- I'm not sure if it'll work since I couldn't recreate the bug on my local but tried to organize the conditions for the park cards

CM-1125: Organize park cards display conditions

---

src/gatsby/src/components/search/cityNameSearch.js

CM-1132
- Fix current location searching issue when field is empty

CM-1132: Fix current location searching issue when field is empty

---

src/gatsby/src/pages/find-a-park.js

CM-1125
Fix issue with selected city getting cleared when loading a bookmarkable URL or searching from the homepage

CM-1125: Fix issue with selected city getting cleared

---

src/gatsby/__tests__/components/__snapshots__/footer.test.js.snap
src/gatsby/src/components/footer.js
src/gatsby/src/styles/cmsSnippets/parkInfoPage.scss
src/gatsby/src/styles/footer.scss
src/gatsby/src/styles/pageContent/pageMenu.scss
src/gatsby/src/styles/parks.scss
src/gatsby/src/styles/staticContent1.scss

CM-1033
- Update link focus style on content pages

CM-1033: Update link focus style on content pages

---

src/gatsby/src/styles/parks.scss
src/gatsby/src/styles/staticContent1.scss

CM-1087
- Add max-width to container on tablet size

CM-1087: Add max-width to container on tablet size

---

src/cms/database/migrations/2023.12.05T00.00.09.park-operations-dates.js

CM-1134
Fix for failing migration

CM-1134: Fix for failing migration on alpha-dev

---

src/cms/src/api/emergency-alert/content-types/emergency-alert/lifecycles.js
src/cms/src/api/emergency-alert/content-types/emergency-alert/schema.json
src/gatsby/gatsby-config.js
src/gatsby/gatsby-node.js

CM-1026
- Add activeDate and inactiveDate

CM-1026: Add activeDate and inactiveDate

---

src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CM-1134
Hide the gate sentence on the park dates page if no 2024 dates exist

CM-1134: Hide gate sentence on the park dates page if no dates exist

---

src/cms/database/migrations/2023.12.05T00.00.09.park-operations-dates.js

CM-1134
Fix error evaluating the value of `is_date_range_annual` and publishing 2024 records

CM-1134: Fix error publishing 2024 records

---

infrastructure/helm/bcparks/templates/etl/etl-cronjob.yaml
infrastructure/helm/bcparks/values-alpha-test.yaml
infrastructure/helm/bcparks/values.yaml
src/etl/scripts/park-names.js

CM-970
- Updated helm scripts to support disabling individual tasks
- Fixed error in park names task when saving searchTerms

CM-970: Updated helm scripts for etl & fixed for saving searchTerms

---

src/gatsby/src/styles/megaMenu/megaMenu.scss

CM-1141
- Fix the content was missing on the site map page
- Update sitemap page styling

CM-1141: Update sitemap page styling

---

src/gatsby/src/components/search/cityNameSearch.js
src/gatsby/src/components/search/mainSearch.js

CM-1142
- Fix current location search issue on the home page

CM-1142: Fix current location search issue on home page

---

src/gatsby/src/components/search/cityNameSearch.js
src/gatsby/src/components/search/mainSearch.js
src/gatsby/src/pages/find-a-park.js

CM-1145
- renamed isCityNameLoading to acquiringGeolocation
- fixed a condition where location 0 was loaded from the querystring with geolocation blocked causing an infinite loading indicator

CM-1145: Fix for infinite loading indicator when geoloction is blocked

---

src/gatsby/src/components/pageContent/linkCard.js

CM-1135
- Change the cards component layout on tablet

CM-1135: Change cards layout on tablet

---

src/gatsby/src/pages/find-a-park.js

CM-1145
- Fix the bookmarkable url issue when there is no current location permission

CM-1145: Fix the bookmarkable url issue when there is no current location permission

---

src/gatsby/src/pages/find-a-park.js

None
- One line was missing in https://github.com/bcgov/bcparks.ca/pull/1135

NOBUG: Revert current location fix

---

src/gatsby/src/pages/find-a-park.js

CM-1145
Use the callback of getCurrentPosition to handle errors

CM-1145:  Fix issue with blocked location

---

src/gatsby/src/pages/find-a-park.js

CM-1152
There are two useEffect() blocks in find-a-park.js to sync the page object state with the bookmarkable URL querystring state.  One of the blocks was being used incorrectly, which may have been causing the state sync to take longer and the queries to appear as slow.

CM-1152: Fix inconsistencies in bookmarkable URL state sync code

---

src/gatsby/src/components/search/cityNameSearch.js
src/gatsby/src/pages/find-a-park.js

CM-1152
- Add maximumAge 10 minutes to getCurrentPosition (default is 0)
- Refactored selectedCity useEffect()
- Show a different message when waiting for location -- "Getting location..." instead of "Searching..."

CM-1152: Add maximumAge 10 minutes to getCurrentPosition

---

src/cms/src/api/park-operation-sub-area/content-types/park-operation-sub-area/schema.json

CM-804
Add offSeasonUse field to parkOperationSubAreas

CM-804: Add offSeasonUse field to parkOperationSubAreas

---

src/cms/src/api/public-advisory/controllers/public-advisory.js
src/cms/src/api/public-advisory/routes/custom.js
src/gatsby/src/components/park/parkAccessStatus.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
src/gatsby/src/styles/listPage.scss

CM-990
Add park access status to the park operating dates page.
- This change requires public permissions to be set on a new Strapi endpoint: _"public-advisory.getAccessStatusesByProtectedArea"_
- Layout has been roughly implemented, but needs a design review

CM-990: Add Park Access Status to Operating Dates page

---

src/gatsby/src/components/megaMenu.js

CM-1158
- Change megamenu logic using url

CM-1158: Change megamenu logic using url

---

src/gatsby/src/styles/megaMenu/megaMenu.scss

CM-1158
- Fix megamenu transition delay

CM-1158: Fix megamenu transition

---

src/gatsby/src/components/emergencyAlert.js

CM-1160
- The alert flash happens only on DEV/TEST, not on local, so not 100% sure if it'll fix the issue

CM-1160: Fix the alert flash

---

src/gatsby/src/components/emergencyAlert.js

CM-1160
- Change the default value of alert state

CM-1160: Change the default value of alert state

---

src/etl/scripts/park-names.js

CM-1183
This fixed a bug in the park name data register sync that was introduced when the dev and test environments were refreshed from prod using `strapi import`

CM-1183: Look up park name type id's instead of hard-coding

---

src/admin/src/components/composite/advisoryAreaPicker/AdvisoryAreaPicker.js
src/admin/src/components/composite/advisoryForm/AdvisoryForm.css
src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/page.css
src/admin/src/components/page/advisory/Advisory.js
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.css
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
src/admin/src/components/shared/button/Button.css
src/admin/src/index.css

CM-1088
CM-1090
CM-1099
CM-1100
CM-1109
CM-1101
CM-1111
- CM-1088: Update advisory form layout
- CM-1090: Add affected area show/hide function
- CM-1099: Update advisory form button
- CM-1100: Update after-hours advisory warning
- CM-1101: Remove info from edit form
- CM-1109: Update advisory table colour
- CM-1111: Update page header

CM-1109: Update staff portal frontend

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/page/advisory/Advisory.js

None
- Fixed the build error temporarily: https://github.com/bcgov/bcparks.ca/actions/runs/7427219400/job/20212781385

NOBUG: Comment out unused variables

---

src/cms/src/api/park-operation/content-types/park-operation/schema.json

CM-1157
These fields were moved to parkOperationDates

CM-1157: Remove gate dates from parkOperation

---

src/gatsby/src/components/park/parkDates.js

CM-1149
Remove access status from park page dates section

CM-1149: Remove access status from park page dates section

---

src/gatsby/src/components/park/parkAccessStatus.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
src/gatsby/src/styles/listPage.scss

CM-1198
- Update the park group label on the park operating dates page

CM-1198: Update park group label on park operating dates page

---

src/gatsby/src/components/park/parkAccessStatus.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
src/gatsby/src/styles/listPage.scss

CM-990, CM-1198
Revert all front-end changes until the next release.  This change had larger repercussions than anticipated.

CM-990: Remove access status from the operating dates page

---

src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/templates/park.js

CM-1151
Added special public advisories to park pages for gate closures.

CM-1151: Seasonal advisory - front-end display

---

src/gatsby/src/components/park/parkDates.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CM-1154
- Hide dates of operation text if hasParkGate is false

CM-1154: Hide dates of operation text if hasParkGate is false

---

src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/components/park/parkAccessStatus.js
src/gatsby/src/templates/park.js
src/gatsby/src/utils/advisoryHelper.js

CM-1151
Fixed react console error and added eventType to advisories

CM-1151: Fixed react console error and added eventType to advisories

---

src/gatsby/src/components/park/parkAccessStatus.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
src/gatsby/src/styles/listPage.scss
src/gatsby/src/styles/parks.scss
src/gatsby/src/styles/search.scss
src/gatsby/src/templates/site.js

CM-1147
CM-1201
- Park access status - update to include ", check advisories" when it is not "Open"
- Add Park Access Status to Operating Dates page

CM-1201: Add Park Access Status to Operating Dates page

---

src/gatsby/src/components/park/parkAccessStatus.js

CM-1147
Removed a null check which was no longer needed because the code was moved into a useEffect() to fix another issue

CM-1147: Fixed access status on park-operationg-dates page

---

src/gatsby/src/styles/parks.scss
src/gatsby/src/styles/staticContent1.scss
src/gatsby/src/utils/constants.js

CM-1200
- Change the last section height on park page and static content page to enable scrolling
- Remove unnecessary code

CM-1200: Change the last section height on park page to enable scrolling

---

src/gatsby/src/components/park/parkAccessStatus.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
src/gatsby/src/styles/listPage.scss

CM-1201
- Update park access status styling on operating dates page
- Styling for each status: https://bcparksdigital.atlassian.net/browse/CM-1201?focusedCommentId=21084

CM-1201: Update park access status styling on operating dates page

---

src/admin/src/validators/AdvisoryValidator.js

CM-1215
- Fix an advisory saving issue
- Delete an unnecessary validator (comment out as all SP changes are still in WIP)

CM-1215: Fix advisory saving issue

---

src/gatsby/src/styles/search.scss

CM-1133
- Change the clear button opacity when it is on hover

CM-1133: Change the clear button opacity when it is on hover

---

src/gatsby/src/styles/footer.scss
src/gatsby/src/styles/pageContent/pageMenu.scss
src/gatsby/src/styles/parks.scss
src/gatsby/src/styles/staticContent1.scss

CM-1214
- Update link focus style on the park operating page

CM-1214: Update link focus style on park operating page

---

src/etl/scripts/park-names.js

CM-1199
End the process with error code 1 whenever there are errors caught

CM-1199: ETL cron job failures should exit with an error code

---

src/gatsby/src/components/park/parkAccessStatus.js
src/gatsby/src/utils/advisoryHelper.js

CM-1222
CM-1151
The wrong keyword was used to exit the for loop. 
Also updated a copy error.

CM-1222: Fix bug in seasonal access status for subareas

---

src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CM-1222
Added a missing field to GraphQL query

CM-1222: Fix subarea seasonal restrictions on park-operating-date page

---

src/gatsby/src/styles/alert.scss
src/gatsby/src/styles/search.scss

CM-1136
- Apply focus visible outline on Firefox

CM-1136: Apply focus visible outline on Firefox

---

src/gatsby/src/components/search/cityNameSearch.js
src/gatsby/src/components/search/parkNameSearch.js

CM-1203
- Fix typo in the park search options

CM-1203: Fix typo in the park search options

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js

CM-1100
- Update after-hours advisory warning

CM-1100: Update after-hours advisory warning

---

src/admin/src/utils/AdvisoryUtil.js

CM-1062
This has probably been broken since the Strapi 4 upgrade.

CM-1062: Fix the broken auto update for statutory holidays

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/composite/advisorySummaryView/AdvisorySummaryView.js
src/admin/src/components/page.css
src/admin/src/components/page/advisory/Advisory.js
src/admin/src/components/page/advisorySummary/AdvisorySummary.js

CM-1225
- Fix copy all button
- Update the CSS class for the urgency-level buttons

CM-1225: Fix copy all button

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js

CM-1100
- Change after-hours advisory warning
- The fix was missing because I might've overridden the change when I fixed the merge conflict for the staff portal PR ...

CM-1100: Change after-hours advisory warning

---

src/gatsby/src/templates/park.js

CM-1227
- Fix the anchor link scroll issue on Firefox
- Not sure why the previous one didn't work on Firefox, the new code works on any browsers

CM-1227: Fix anchor link scroll issue on firefox

---

src/admin/src/components/composite/advisoryHistory/AdvisoryHistory.js

CM-1166
- Fix alignment of the revision details

CM-1166: Fix alignment of the revision details

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/page/advisory/Advisory.js

None
- Fix error below
```
message: "1 relation(s) of type api::urgency.urgency associated with this entity do not exist"
name: "ValidationError"
status: 400
```
- Looks urgency.value has to be urgency.id. partially reverted this change: https://github.com/bcgov/bcparks.ca/pull/1190

NOBUG: Fix error when advisory was created

---

src/admin/src/components/page/advisory/Advisory.js
src/admin/src/utils/AppUtil.js

CM-997
- Change the advisory status from camel case to sentence case

CM-997: Change the advisory status from camel case to sentence case

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

CM-825
- Update advisory dashboard
- Update advisory dashboard columns and reorganize
- Add help text to the end date field and the expiry date field

CM-825: Update advisory dashboard

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.css
src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/composite/advisorySummaryView/AdvisorySummaryView.js
src/admin/src/components/page.css

CM-1234
CM-1238
CM-1239
- CM-1234: Update supporting info UI
- CM-1238: Add a clear button to the URL field
- CM-1239: Fix speling

CM-1234: Update supporting info UI

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js

CM-1235
- Remove default value from selectedDisplayedDateOption

CM-1235: Remove default value from selectedDisplayedDateOption

---

src/gatsby/src/pages/index.js
src/gatsby/src/styles/home.scss
src/gatsby/src/styles/search.scss

CM-1244
- Change static image to background image

CM-1244: Change static image to background image

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/composite/advisorySummaryView/AdvisorySummaryView.js
src/admin/src/components/page.css
src/admin/src/components/page/advisorySummary/AdvisorySummary.css
src/admin/src/components/shared/button/Button.css
src/admin/src/index.css

CM-1241
CM-1247
CM-1248
CM-1253
- CM-1241: Add additional displayed date functionality
- CM-1247: UI update and CSS cleanup
- CM-1248: Update link style
- CM-1253: Remove calendar and clock icon

CM-1241: Add additional displayed date functionality

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.css
src/admin/src/components/page.css

CM-1238
- Fix overwrapping input text and clear button

CM-1238: Fix overwrapping input text and clear button

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/page/advisory/Advisory.js

CM-1231
- Fix the link type that was missing when a user edited an advisory

CM-1231: Fix link type was missing when user edits an advisory

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.css
src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/composite/advisorySummaryView/AdvisorySummaryView.js
src/admin/src/components/page.css
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
src/admin/src/components/page/advisorySummary/AdvisorySummary.css
src/admin/src/index.css

CM-1237
CM-1247
CM-1248
CM-1263
- CM-1237: Fix the file field issue when replacing a file
- CM-1247: Update link and button focus/focus-visible style
- CM-1248, CM-1263: Update link style and spacing

CM-1237: Fix the file field issue when replacing a file

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js

CM-1271
- Update validation for start date and end date

CM-1271: Update validation for start date and end date

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/page/advisory/Advisory.js

CM-1232
- Fix link update logic
- Remove the default link type
- Probably the link update function had been broken since the Strapi update

CM-1232: Fix link update logic

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js

CM-1275
- Update validation for posting date and expiry date

CM-1275: Update validation for posting date and expiry date

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.css
src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/composite/advisorySummaryView/AdvisorySummaryView.js
src/admin/src/components/page/advisorySummary/AdvisorySummary.js

CM-1246
CM-1277
CM-1279
- Update advisory preview UI
- Add character max length to short text fields
- Change "Listing Rank" to "Listing rank"

CM-1279: Add character max length to short text fields

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js

CM-1237
- Add browse button to change selected file

CM-1237: Add browse button to change selected file

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/validators/AdvisoryValidator.js

CM-1278
- Update listing rank validation
- The regex `0$|^[1-9]\d{0,3}$`:
- allows single 0, doesn't allow 001
- allows positive numbers, doesn't allow negative numbers
- allows for numbers ranging from 1 to 9999 (can be changed)

CM-1278: Update listing rank validation

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.css
src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/components/page/advisory/Advisory.js

CM-1284
- Remove duration field

CM-1284: Remove duration field

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js

CM-1278
- Prevent mousewheel in input of type number

CM-1278: Prevent mousewheel in input of type number

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/validators/AdvisoryValidator.js

CM-1236
- Update link validation

CM-1236: Update link validation

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/validators/AdvisoryValidator.js

CM-1236
- Fix link validation if there are multiple links

CM-1236: Fix link validation if there are multiple links

---

src/admin/package-lock.json
src/admin/package.json

CM-1291
- I didn't create a ticket for this PR https://github.com/bcgov/bcparks.ca/pull/1155 so this is an updated PR for a new ticket
- Updated a library based on `npm outdated`
- Fixed some vulnerabilities with `npm audit fix`

CM-1291: Update admin libraries

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/validators/AdvisoryValidator.js

CM-1242
- Add displayed date validation

CM-1242: Add displayed date validation

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js

CM-1276
- Change access status to be required

CM-1276: Change access status to be required

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js

CM-1292
- Update the add supporting information form functionality
- When the file URL is deleted, the browse button will be displayed so that users can re-upload a new image

CM-1292: Update the add supporting information form functionality

---

src/scheduler/server.js

CM-1250
Fixed an error in server.js preventing the pod from starting correctly

CM-1250: Fix error

---

src/gatsby/src/components/park/parkActivity.js

CM-1282
- Update discover parks copy
- Remove `noreferrer`

CM-1282: Update discover parks copy

---

src/gatsby/src/components/park/parkOverview.js

CM-1306
Add support for anchor links in the collapsed part of the park overview section

CM-1306: Support anchor links in the park overview

---

infrastructure/helm/bcparks/templates/_helpers.tpl
infrastructure/helm/bcparks/templates/scheduler/scheduler-deployment.yaml
infrastructure/helm/bcparks/values-alpha-dev.yaml
infrastructure/helm/bcparks/values-alpha-test.yaml
infrastructure/helm/bcparks/values-dev.yaml
infrastructure/helm/bcparks/values-prod.yaml
infrastructure/helm/bcparks/values-test.yaml
infrastructure/helm/bcparks/values.yaml
src/cms/README.md
src/scheduler/.env.example
src/scheduler/email-alerts/scripts/sendAdvisoryEmails.js

CM-1259
Add missing helm updates

CM-1259: Helm updates for emails

---

src/admin/src/components/page/advisory/Advisory.js

CM-1304
- Remove autofill the start date and update date fields
- Autofill the start date will remain when users create an advisory

CM-1304: Remove autofill the start date and update date fields

---

src/gatsby/src/components/park/parkOverview.js

CM-1306: Reverted change

---

src/admin/src/components/composite/accountInfo/AccountInfo.js
src/admin/src/components/page/advisoryLink/AdvisoryLink.js
src/admin/src/components/page/advisoryLink/AdvisoryLink.stories.js
src/admin/src/components/page/advisoryLink/AdvisoryLink.test.js
src/admin/src/routes/AppRouter.js
src/scheduler/.env.example
src/scheduler/email-alerts/templates/public-advisory.ejs

CM-1169
Added an alternate path for linking to advisories in the staff portal using the advisoryNumber instead of the publicAdvisoryAuditId

CM-1169: Email link to advisories

---

src/scheduler/email-alerts/scripts/sendAdvisoryEmails.js

CM-1259
Ignored messages weren't being removed from the queue

CM-1259: Fixed bug in queue handling

---

src/admin/src/components/composite/accountInfo/AccountInfo.js

CM-1316
This fixes a bug that causes a white screen to appear when a user's Keycloak token expires

CM-1316: Bug fix for white screen when Keycloak token expires

---

src/scheduler/email-alerts/scripts/sendAdvisoryEmails.js
src/scheduler/email-alerts/templates/public-advisory.ejs
src/scheduler/package-lock.json
src/scheduler/package.json

CM-1259
- Bugfix for time zone display issue.  Timezones needed to be converted to America/Vancouver
- Removed link type from links

CM-1259: Fix for UTC timezone issue in emails

---

src/cms/src/api/public-advisory/services/scheduling.js
src/scheduler/email-alerts/scripts/mailer.js
src/scheduler/email-alerts/scripts/sendAdvisoryEmails.js

CM-1319
- Fixed the filter for advisories expiring within 1 week because it was sending duplicates
- Change the sender name to the environment name (unless it's prod)
- Fixed a bug causing the scheduler to crash

CM-1319: Fix for duplicate emails

---

src/scheduler/email-alerts/scripts/sendAdvisoryEmails.js

CM-1319
fix error:
```
2024-02-29T21:32:00.182Z: [error] Error running cron task: ReferenceError: fromNames is not defined
```

CM-1319: Fix variable name error

---

src/gatsby/src/components/megaMenu.js

CM-1282
- Replace gatsby static image with img

CM-1282: Replace gatsby static image with img

---

src/gatsby/gatsby-node.js
src/gatsby/src/components/footer.js

None
- Fix footer menu build error: https://github.com/bcgov/bcparks.ca/actions/runs/8165438312/job/22322580658
- For the type definition, I needed to create another type for children
- Add sorting to footer-menu children

NOBUG: Fix footer menu build error

---

src/admin/src/App.js

CM-1297
Disable the Keycloak `checkLoginIframe` setting on Firefox
https://github.com/keycloak/keycloak/issues/23872
https://github.com/react-keycloak/react-keycloak/issues/183

CM-1297: Disable Keycloak checkLoginIframe setting on Firefox

---

src/scheduler/email-alerts/templates/public-advisory.ejs

CM-1169
- Update manage advisory button in email

CM-1169: Update manage advisory button in email

---

src/cms/src/plugins/strapi-plugin-ckeditor/admin/src/components/Input/CKEditor/theme/common.js
src/gatsby/src/components/advisories/advisoryFilter.js
src/gatsby/src/pages/find-a-park.js
src/gatsby/src/styles/404.scss
src/gatsby/src/styles/_navbar.scss
src/gatsby/src/styles/advisories/advisoryCard.scss
src/gatsby/src/styles/advisories/advisoryFilter.scss
src/gatsby/src/styles/advisories/advisoryLegend.scss
src/gatsby/src/styles/betaLanding.scss
src/gatsby/src/styles/bootstrapTheme.scss
src/gatsby/src/styles/global.scss
src/gatsby/src/styles/home.scss
src/gatsby/src/styles/listPage.scss
src/gatsby/src/styles/megaMenu/megaMenu.scss
src/gatsby/src/styles/pageContent/linkCard.scss
src/gatsby/src/styles/parks.scss
src/gatsby/src/styles/search.scss
src/gatsby/src/styles/staticContent1.scss
src/gatsby/src/styles/staticLanding1.scss
src/gatsby/src/styles/variables.scss

CM-1043
- Update colours to align with colours in the design library
- Remove unused CSS classes

CM-1043: Update colours to align with colours in design library

---

src/scheduler/email-alerts/scripts/sendAdvisoryEmails.js
src/scheduler/email-alerts/templates/public-advisory.ejs

CM-1324
- Don't add [pdf] to pdf documents
- Change "Notes" to "Internal note"
- Show the date that is selected to be displayed with the advisory

CM-1324: Fix email copy issues

---

src/scheduler/email-alerts/templates/public-advisory.ejs

CM-1324: Change "Internal note" to "Internal notes"

---

src/cms/src/api/public-advisory-audit/content-types/public-advisory-audit/lifecycles.js

CM-1331
The links were being moved to the new version, which was really the old version

CM-1331: Fix for lost links on scheduled advisories

---

src/scheduler/email-alerts/scripts/sendAdvisoryEmails.js

None
This fixes an issue found during dev.  A previous fix was added in the wrong place.

NOBUG: Fix for scheduler recovery from Strapi outage

---

src/scheduler/email-alerts/templates/public-advisory.ejs

CM-1332
Updated the email styling to work in outlook. This is a major degradation to the design in other mail clients like gmail, but it does look better in Outlook now.    See the ticket for a screenshot

CM-1332: Email styling for Outlook

---

src/cms/src/plugins/strapi-plugin-ckeditor/admin/src/components/Input/CKEditor/theme/common.js
src/gatsby/src/components/search/mobileFilters.js
src/gatsby/src/styles/bootstrapTheme.scss
src/gatsby/src/styles/global.scss
src/gatsby/src/styles/home.scss
src/gatsby/src/styles/pageContent/linkCard.scss

CM-524
- Add other button styles in the RTE so the editors can use them

CM-524: Add button styles in the RTE

---

src/gatsby/src/components/park/parkActivity.js
src/gatsby/src/components/search/noSearchResults.js
src/gatsby/src/pages/find-a-park.js

CM-1325
- Change external link to internal link

CM-1325: Change external link to internal link

---

src/admin/package-lock.json
src/admin/package.json
src/admin/src/components/page.css
src/admin/src/index.css
src/admin/src/index.js
src/gatsby/gatsby-browser.js
src/gatsby/package-lock.json
src/gatsby/package.json
src/gatsby/src/styles/variables.scss

CM-1107
- Update BC sans font to v2: https://github.com/bcgov/bc-sans

CM-1107: Update BC sans font

---

src/gatsby/src/components/scrollToTop.js
src/gatsby/src/pages/about/management-plans/approved.js
src/gatsby/src/pages/active-advisories.js
src/gatsby/src/pages/find-a-park.js
src/gatsby/src/pages/find-a-park/a-z-list.js
src/gatsby/src/pages/index.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
src/gatsby/src/pages/site-map.js
src/gatsby/src/styles/listPage.scss
src/gatsby/src/styles/search.scss
src/gatsby/src/templates/park.js
src/gatsby/src/templates/parkSubPage.js
src/gatsby/src/templates/site.js
src/gatsby/src/templates/staticContent1.js
src/gatsby/src/templates/staticLanding1.js

CM-1180
CM-1181
CM-1193
- CM-1180: Fix h2 link focus style
- CM-1181: Fix status link focus style
- CM-1193: Change the scroll to top button position

CM-1193: Change the scroll to top button position

---

src/gatsby/src/styles/listPage.scss

CM-1196
- Update a-z button styling

CM-1196: Update a-z button styling

---

src/gatsby/src/components/footer.js

None
- Fix react warning: "list should have a unique "key" prop."

NOBUG: Fix react warning

---

src/cms/src/api/page/content-types/page/schema.json

CM-177
- Add separated seo and page header components to the page collection

CM-177: Add separated seo component to page collection

---

src/gatsby/src/components/megaMenu.js

CM-1333
- Optimize megamenu useEffect hook so the menu will be displayed slightly faster when the page transition happens

CM-1333: Optimize megamenu useEffect hook

---

src/gatsby/src/components/search/desktopFilters.js
src/gatsby/src/components/search/mobileFilters.js
src/gatsby/src/styles/cmsSnippets/parkInfoPage.scss
src/gatsby/src/styles/search.scss

CM-1184
- Update expand link style

CM-1184: Update expand link style

---

src/etl/index.js
src/etl/scripts/bcwfs-bans.js

None
Changed an `if` condition to delete some duplicate code
The code was duplicated in these 2 files: 
https://github.com/bcgov/bcparks.ca/blob/develop/src/etl/scripts/bcwfs-propagate.js
https://github.com/bcgov/bcparks.ca/blob/develop/src/etl/scripts/bcwfs-bans.js

NOBUG: Refactor fireban propagation to remove some dup code

---

src/etl/scripts/park-names.js
src/scheduler/email-alerts/scripts/sendParkNamesEmails.js
src/scheduler/email-alerts/templates/parkname-change.ejs
src/scheduler/manage.js
src/scheduler/server.js

CM-1283
Send an email notification when the parknames ETL task changes a park name.

CM-1283: Email notification when a name change occurs

---

src/admin/package-lock.json
src/admin/package.json
src/cms/package-lock.json
src/gatsby/package-lock.json
src/gatsby/src/components/search/filter.js

None
- Fix some vulnerabilities with `npm audit fix`
- Update webpack for admin app as it was high severity, but it caused a new vulnerability 😅
- Remove value from filter event for snowplow tracking

NOBUG: Fix some vulnerabilities

---

src/gatsby/src/components/park/parkDates.js

CM-1321
- Change the dates of operation wording when `parkOperation.isActive` is false

CM-1321: Change dates of operation wording

---

src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CM-1120
- Update no advisories statement 
- Display park type

CM-1120: Update no advisories statement

---

src/cms/src/api/access-status/content-types/access-status/schema.json

CM-788
- Add description field to accessStatuses collection
- No FE change

CM-788: Add description field to accessStatuses collection

---

src/gatsby/src/styles/home.scss

CM-1189
- Change the home advisory buttons' font-weight

CM-1189: Change home advisory buttons font weight

---

src/cms/src/api/park-operation-sub-area/content-types/park-operation-sub-area/schema.json
src/cms/src/api/park-operation/content-types/park-operation/schema.json

CM-1078
- Add time fields to park operation and sub-areas

CM-1078: Add time fields to park operation and sub areas

---

src/gatsby/src/styles/global.scss

CM-1043
- Update table border colour

CM-1043: Update table border colour

---

src/admin/src/components/composite/dataTable/DataTable.css
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

CM-1014
- Add dropdown for status and urgency to filter public advisories
- Change the filter type to "date" for the dates columns

CM-1014: Add dropdown for status and urgency to filter public advisories

---

src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
src/gatsby/src/styles/listPage.scss

CM-1027
- Add icons to the park operating dates page

CM-1027: Add icons to park operating dates page

---

src/admin/src/utils/CmsDataUtil.js
src/cms/src/api/standard-message/content-types/standard-message/schema.json

CM-1084
- Add precedence to standard message collection to re-order items

CM-1084: Add precedence to standard message collection to re-order items

---

src/admin/src/components/composite/accountInfo/AccountInfo.js
src/admin/src/components/composite/header/Header.js
src/admin/src/components/composite/responsiveDrawer/responsiveDrawer.js
src/admin/src/components/page/advisory/Advisory.js
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js
src/admin/src/components/page/advisoryLink/AdvisoryLink.js
src/admin/src/components/page/advisorySummary/AdvisorySummary.js
src/admin/src/components/page/appDashboard/AppDashboard.js
src/admin/src/components/page/error/Error.js
src/admin/src/components/page/home/Home.js
src/admin/src/components/page/parkAccessStatus/ParkAccessStatus.js
src/admin/src/components/page/parkInfo/ParkInfo.js
src/admin/src/components/page/parkSearch/ParkSearch.js
src/admin/src/routes/AppRouter.js

CM-1326
- Add tab control to the mobile menu
- Add a unique URL to each tab
- Remove `bcparks/` from all URLs

CM-1326: Add tab control to the mobile menu

---

src/admin/src/components/page/appDashboard/AppDashboard.css

CM-183
- Remove tabs on mobile

CM-183: Remove tabs on mobile

---

src/admin/src/components/composite/dataTable/DataTable.css
src/admin/src/components/page/advisoryDashboard/AdvisoryDashboard.js

CM-184
- Add space to the select field so as not to overwrap text and icon

CM-184: Add space to the select field not to overwrap text and icon

---

src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CM-54
- Remove temporarily closed text on the Park Operating Dates page

CM-54: Remove temporarily closed text on Park Operating Dates page

---

.github/pull_request_template.md

None
- Change PR template ticket number CM to CMS

NOBUG: Change PR template ticket number CM to CMS

---

src/gatsby/gatsby-config.js
src/gatsby/gatsby-node.js
src/gatsby/src/templates/staticContent1.js
src/gatsby/src/templates/staticLanding1.js

CM-143
- Change staticLanding and staticContent templates structure

CM-143: Change staticLanding and staticContent templates structure

---

src/cms/src/plugins/strapi-plugin-ckeditor/admin/src/components/Input/CKEditor/configs/base.js

CMS-181
- Remove some button styling options from RTE

CMS-181: Remove some button styling options from RTE

---

src/gatsby/src/templates/park.js

CMS-188
- Change seo meta image for the park page if it does not have any image

CMS-188: Change seo meta image for the park page if it does not have any image

---

src/gatsby/src/pages/active-advisories.js

None
- Add fallback to buildParkInfoHash

NOBUG: Add fallback to buildParkInfoHash

---

src/gatsby/gatsby-node.js

CMS-151
- Fix graphql issue related to https://github.com/bcgov/bcparks.ca/pull/1310

CMS-151: Fix graphql issue

---

src/admin/src/components/page/advisory/Advisory.js
src/admin/src/components/page/advisorySummary/AdvisorySummary.js
src/admin/src/components/page/error/Error.js
src/admin/src/components/page/parkInfo/ParkInfo.js
src/admin/src/routes/AppRouter.js

CMS-183
- Pass prop to each page header so users can jump to another page (tab) from the mobile menu

CMS-183: Pass prop to each page header

---

src/gatsby/src/styles/global.scss

CMS-210
- Add flex wrap to breadcrumbs

CMS-210: Add flex wrap to breadcrumbs

---

src/gatsby/src/components/advisories/advisoryFilter.js

CM-191
- Fix layout issue on the active advisory page

CMS-191: Fix layout issue on active advisory page

---

src/cms/src/api/park-operation-sub-area-date/content-types/park-operation-sub-area-date/lifecycles.js

None
Fixed an import error that was preventing copying data from prod to new dev environments.

NOBUG: Fix strapi import error

---

src/cms/database/migrations/2024.05.29T00.00.13.link-photos.js

CMS-220
This migration will link the park photos to sites and protected areas based on existing keys

CMS-220: Migration for CMS-62

---

src/gatsby/src/styles/search.scss

CMS-192
- Fix park name search placeholder colour

CMS-192: Fix park name search placeholder colour

---

src/gatsby/src/components/pageContent/linkCard.js
src/gatsby/src/styles/pageContent/linkCard.scss
src/gatsby/src/styles/staticContent1.scss

CMS-218
- Fix link card styling

CMS-218: Fix link card styling

---

src/gatsby/src/templates/staticLanding1.js

CMS-151
- Change space around breadcrumbs on staticLanding page

CMS-151: Change space around breadcrumbs on staticLanding page

---

src/cms/src/plugins/strapi-plugin-ckeditor/admin/src/components/Input/CKEditor/configs/base.js

CMS-181
- Remove duplicated feature (adding primary button style to text) from RTE

CMS-181: Remove duplicated feature from RTE

---

src/gatsby/src/pages/about/management-plans/approved.js
src/gatsby/src/pages/active-advisories.js
src/gatsby/src/pages/find-a-park/a-z-list.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
src/gatsby/src/pages/site-map.js
src/gatsby/src/templates/park.js
src/gatsby/src/templates/parkSubPage.js
src/gatsby/src/templates/site.js
src/gatsby/src/templates/staticContent1.js
src/gatsby/src/templates/staticLanding1.js

CM-209
- Fix the tabbing issue on firefox by adding a tab index to the `<div id="main-content">` so that the first element of breadcrumbs won't be skipped

CMS-209: Fix tabbing issue on firefox

---

src/cms/src/api/public-advisory/controllers/public-advisory.js

CMS-123
Wrapped the null check around the entire code block

CMS-225: More encompassing null checks for accessStatus

---

src/gatsby/src/components/park/parkDates.js

CMS-172
- Remove italic font from dates of operation text

CMS-172: Remove italic font from dates of operation text

---

src/cms/src/api/park-photo/content-types/park-photo/lifecycles.js

CMS-62
- Fix park photo lifecycle issue
- When an editor deletes protectedArea/site, orcs/orcsSiteNumber will be cleared

CMS-62: Fix park photo lifecycle issue

---

src/gatsby/src/styles/advisories/advisoryFilter.scss
src/gatsby/src/styles/search.scss

CMS-189
- Update checkbox styling and fix the styling issue on Firefox

CMS-189: Update checkbox styling

---

src/gatsby/src/components/park/parkHeader.js
src/gatsby/src/templates/park.js

CMS-26
- Fix map link error
- Display/Hide the link to the camping/facilities section based on the number of camping/facilities

CMS-26: Fix map link error

---

src/gatsby/src/styles/staticLanding1.scss
src/gatsby/src/templates/staticLanding1.js

CMS-190
- Fix layout issue on static landing page

CMS-190: Fix layout issue on static landing page

---

src/cms/src/api/park-operation-sub-area/content-types/park-operation-sub-area/schema.json
src/cms/src/api/park-operation/content-types/park-operation/schema.json

CMS-169
- Add gateOpensAtDawn and gateClosesAtDusk fields to park-operation and park-operation-sub-area collection

CMS-169: Add gateOpensAtDawn and gateOpensAtDusk fields to park-operation and park-operation-sub-area collection

---

src/gatsby/src/components/advisories/advisoryLegend.js
src/gatsby/src/styles/advisories/advisoryCard.scss
src/gatsby/src/styles/advisories/advisoryLegend.scss
src/gatsby/src/styles/variables.scss

CMS-221
- Update advisory icons on active advisories page

CMS-221: Update advisory icons on active advisories page

---

src/gatsby/src/components/park/parkAccessStatus.js
src/gatsby/src/components/park/parkHeader.js
src/gatsby/src/styles/parks.scss

CMS-26: Fix some ui issues

---

src/cms/src/api/park-operation-sub-area-type/content-types/park-operation-sub-area-type/schema.json
src/cms/src/api/park-operation-sub-area/content-types/park-operation-sub-area/schema.json
src/cms/src/api/park-operation/content-types/park-operation/schema.json

CMS-230
Reverted #1281 (urls will be replaced with CMS-231)

CMS-230: Reverted CM-1307

---

src/cms/src/api/park-operation/content-types/park-operation/schema.json
src/cms/src/components/parks/rte-list.json

CMS-40
Added new fields for "Reservations required" park page section

CMS-40: New fields for "Reservations required" section

---

src/gatsby/src/components/park/nearbyPark.js
src/gatsby/src/components/park/parkHeader.js
src/gatsby/src/components/search/featureIcons.js
src/gatsby/src/components/search/parkCard.js
src/gatsby/src/styles/parks.scss
src/gatsby/src/templates/park.js

CMS-38
- Fix some nearby parks UI issues
- Fix gateOpenTime and gateCloseTime were not rendered

CMS-38: Fix some nearby parks ui issues

---

src/gatsby/gatsby-node.js

None
-  Fix gatsby build error, there was a typo

NOBUG: Fix gatsby error

---

src/gatsby/src/pages/about/management-plans/approved.js

CMS-123
- Update copy on approved management plans page

CM-227: Update copy on approved management plans page

---

src/gatsby/gatsby-node.js
src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/components/park/natureAndCulture.js
src/gatsby/src/components/park/parkAccessStatus.js
src/gatsby/src/components/park/parkDates.js
src/gatsby/src/components/park/parkHeader.js
src/gatsby/src/components/park/reservationsRequired.js
src/gatsby/src/components/park/safetyInfo.js
src/gatsby/src/components/park/specialNote.js
src/gatsby/src/components/park/visitResponsibly.js
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CMS-30
CMS-40
CMS-203 (partially done)
- Add visit responsibly section to the park page
- Add reservation required section to the park page
- Integrate some sections into the Know Before You Go section

CMS-30: Add visit responsibly section

---

src/gatsby/src/components/park/campingDetails.js
src/gatsby/src/components/park/parkHeader.js

CMS-226
Use the reservation URLs from the park-operations collection on the park pages when they are provided

CMS-226: Utilize custom reservation urls on park pages

---

src/cms/src/api/park-operation/content-types/park-operation/schema.json

CMS-231
Added new reservation URL fields.  
These will be used in the camping section of the redesigned park pages.

CMS-231: Add new reservation url fields

---

src/gatsby/src/components/park/parkOverview.js
src/gatsby/src/components/search/featureIcons.js

CMS-247
- Remove the anchor link from the show more highlight toggle

CMS-247: Remove anchor link from the show more highlight toggle

---

src/gatsby/src/components/park/contact.js
src/gatsby/src/styles/cmsSnippets/parkInfoPage.scss
src/gatsby/src/styles/global.scss
src/gatsby/src/templates/park.js

CMS-245
- Set width and height for icons to fix the issue that they are in the odd size while the page is loading
- Display tldr section after api data is loaded to fix the issue that some data is displayed later

CMS-245: Set width and height for icons

---

src/cms/src/api/protected-area/custom/protected-area-status.js

CMS-241
- Add search-area to park-access-statuses API
- For testing, visit `/api/park-access-statuses?populate=*`

CMS-241: Add search-area to park-access-statuses API

---

src/gatsby/src/components/park/nearbyPark.js

CMS-243
Fixed a Gatsby build error with nearby parks

CMS-243: Fix gatsby build error

---

src/gatsby/gatsby-config.js

CMS-243
Fix another build error with nearby parks

CMS-243: Fix build error

---

src/gatsby/gatsby-config.js

CMS-243
This fixes another error with nearby parks causing it to fail on alpha-dev

CMS-243: Fix nearby parks

---

src/gatsby/gatsby-config.js
src/gatsby/src/components/park/nearbyPark.js
src/gatsby/src/templates/park.js

CMS-243
Fix issues with nearby parks
- fix missing javascript check
- fix missing grapqh subqueries
- revert previous fix

CMS-243: Nearby parks fix

---

src/cms/src/api/protected-area/content-types/protected-area/schema.json
src/gatsby/gatsby-config.js
src/gatsby/gatsby-node.js
src/gatsby/src/components/park/about.js
src/gatsby/src/components/park/nearbyPark.js
src/gatsby/src/components/park/nearbyParks.js
src/gatsby/src/templates/park.js

CMS-259
- Restructure nearbyParks from 3 fields to 1 field in Strapi

CMS-259: Restructure nearbyParks from 3 fields to 1 field in Strapi

---

src/gatsby/src/components/park/about.js
src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/components/park/campingDetails.js
src/gatsby/src/components/park/contact.js
src/gatsby/src/components/park/mapLocation.js
src/gatsby/src/components/park/parkAccessStatus.js
src/gatsby/src/components/park/parkActivity.js
src/gatsby/src/components/park/parkDates.js
src/gatsby/src/components/park/parkFacility.js
src/gatsby/src/components/park/parkHeader.js
src/gatsby/src/components/park/parkOverview.js
src/gatsby/src/components/park/reconciliation.js
src/gatsby/src/components/park/reservationsRequired.js
src/gatsby/src/components/park/safetyInfo.js
src/gatsby/src/components/park/specialNote.js
src/gatsby/src/components/park/visitResponsibly.js
src/gatsby/src/components/search/featureIcons.js
src/gatsby/src/styles/parks.scss
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CMS-236
- Update anchor links on park page and site page

CMS-236: Update anchor links on park page and site page

---

src/gatsby/src/components/park/parkHeader.js
src/gatsby/src/styles/parks.scss

CMS-261
CMS-262
CMS-263
- Fix tldr section bugs

CMS-261: Fix tldr section bugs

---

src/gatsby/src/components/park/visitorGuidelines.js
src/gatsby/src/styles/parks.scss
src/gatsby/src/templates/park.js

CMS-29
- Fix visitor guideline section bugs

CMS-29: Fix visitor guideline section bugs

---

src/gatsby/src/styles/parks.scss

CMS-38
- Fix nearby parks styling issues

CMS-38: Fix nearby parks styling issues

---

src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/components/park/campingDetails.js
src/gatsby/src/components/park/parkActivity.js
src/gatsby/src/components/park/parkDates.js
src/gatsby/src/components/park/parkFacility.js

CMS-112
-  If there is only one accordion in a section, have it default to expanded and hide the Expand all and expand/collapse functionality

CMS-112: Update accordion function

---

src/gatsby/src/components/park/nearbyPark.js
src/gatsby/src/components/search/parkCard.js
src/gatsby/src/styles/search.scss
src/gatsby/src/utils/helpers.js

CMS-267
- Fix the issue when there's an image with an error in the carousel, all images become the default logo image
- The fix applies to the park cards on the Find a Park page and park cards in the Nearby parks on the Park page

CMS-267: Fix park photo carousel issue

---

src/gatsby/src/components/park/parkAccessStatus.js
src/gatsby/src/components/park/parkHeader.js
src/gatsby/src/components/search/parkCard.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CMS-264
- Update park access status link

CMS-264: Update park access status link

---

src/gatsby/src/components/park/parkDates.js
src/gatsby/src/components/park/parkFacility.js
src/gatsby/src/components/park/subArea.js
src/gatsby/src/styles/global.scss
src/gatsby/src/styles/parks.scss

CMS-33
CMS-272
- Update camping accordion styling
- Created this PR because I couldn't add updates to this PR: https://github.com/bcgov/bcparks.ca/pull/1389. I had an SSO issue even though I've already done it for authorization.
```
➜  strapi4 git:(CMS-33) git push             
ERROR: The 'bcgov' organization has enabled or enforced SAML SSO.
To access this repository, you must use the HTTPS remote with a personal access token or SSH with an SSH key and passphrase that has been authorized for this organization.
Visit https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/ for more information.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

CMS-33: Update camping accordion styling

---

src/gatsby/src/components/park/reservationsRequired.js
src/gatsby/src/templates/park.js

CMS-275
- Add conditions to display reservations required

CMS-275: Add conditions to display reservations required

---

src/cms/package-lock.json
src/cms/package.json

CMS-163
Bumped Strapi from 4.25.1 to 4.25.6
Also removed some unnecessary dependencies

CMS-163: Update to Strapi 4.25.6

---

src/gatsby/src/components/search/desktopFilters.js
src/gatsby/src/components/search/mobileFilters.js

CMS-253
- Change filter heading title activities to things to do

CMS-253: Change filter heading title activities to things to do

---

src/gatsby/src/components/park/nearbyPark.js

CMS-267
- Update nearby parks photos sorting

CMS-267: Update nearby parks photos sorting

---

src/gatsby/src/components/park/visitResponsibly.js

CMS-30
- Update visit responsibly logic

CMS-30: Update visit responsibly logic

---

src/gatsby/src/components/park/campingDetails.js

CMS-286
- Update the book camping button style

CMS-286: Update the book camping button style

---

src/gatsby/src/components/park/about.js

CMS-236
- Add another id to the about section subheading as a fallback

CMS-236: Add another id to the about section subheading as a fallback

---

src/gatsby/gatsby-node.js
src/gatsby/src/components/park/reservationsRequired.js
src/gatsby/src/templates/park.js

CMS-40
- Update reservation required logic

CMS-40: Update reservation required logic

---

src/cms/config/env/production/plugins.js

CMS-276
Updated the S3 config to the new format to fix upload error

CMS-276: Update S3 config to new format

---

src/gatsby/src/components/park/parkHeader.js
src/gatsby/src/styles/parks.scss

CMS-273
- Adjust link in tldr for first release

CMS-273: Adjust link in tldr for first release

---

src/cms/src/api/park-guideline/content-types/park-guideline/schema.json
src/cms/src/api/protected-area/content-types/protected-area/schema.json
src/cms/src/api/trail-report/content-types/trail-report/schema.json
src/cms/src/api/trail-report/controllers/trail-report.js
src/cms/src/api/trail-report/routes/trail-report.js
src/cms/src/api/trail-report/services/trail-report.js
src/gatsby/gatsby-config.js
src/gatsby/gatsby-node.js
src/gatsby/src/components/park/visitorGuidelines.js
src/gatsby/src/templates/park.js

CMS-29
- Add trail report collection and use it in the visitor guidelines section instead of the mediaLink field

CMS-29: Add trail report collection

---

src/gatsby/src/components/park/campingDetails.js

CMS-292
- Expand the camping accordion only if there is one accordion 
- Don't expand it if there are two accordions including the reservation accordion

CMS-292: Expand camping accordion if there is only one

---

src/cms/database/migrations/2024.07.29T00.00.18.remove-h3.js
src/cms/database/migrations/2024.07.29T00.00.19.plural-units.js
src/cms/src/api/camping-type/content-types/camping-type/schema.json
src/gatsby/src/components/park/campingDetails.js
src/gatsby/src/components/park/parkActivity.js
src/gatsby/src/components/park/parkDates.js
src/gatsby/src/components/park/parkFacility.js
src/gatsby/src/components/park/subArea.js
src/gatsby/src/styles/global.scss
src/gatsby/src/styles/parks.scss
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js
src/gatsby/src/utils/subAreaHelper.js

CMS-33
- Implement the new camping section layout
- Add subarea dates to applicable facilities & camping types
- Remove Dates of Operation section from park pages

WIP CMS-33: New camping section layout 

---

src/cms/src/api/guideline-type/content-types/guideline-type/schema.json
src/cms/src/api/park-guideline/content-types/park-guideline/schema.json
src/gatsby/gatsby-node.js
src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/components/park/visitorGuidelines.js
src/gatsby/src/styles/parks.scss
src/gatsby/src/templates/park.js

CMS-29
CMS-304
CMS-306
- Fix the spacing issue and add the hasTrailReport field to park-guideline

CMS-304: Fix spacing issue and add hasTrailReport field

---

src/gatsby/src/templates/park.js

CMS-37
- Fix gatsby build error: https://github.com/bcgov/bcparks.ca/actions/runs/10322257334/job/28577070998#step:11:247

CMS-37: Fix gatsby build error

---

src/gatsby/src/components/park/subArea.js

None
- Fix typo to fix gatsby build error: https://github.com/bcgov/bcparks.ca/actions/runs/10323979063/job/28582471104#step:11:173

NOBUG: Fix typo to fix gatsby build error

---

src/cms/src/api/park-operation/content-types/park-operation/schema.json
src/gatsby/gatsby-node.js
src/gatsby/src/components/park/reservationsRequired.js
src/gatsby/src/templates/park.js

CMS-246
- Remove hasPicnicShelterReservations field
- Use hasGroupPicnicReservations instead of hasPicnicShelterReservations

CMS-246: Remove hasPicnicShelterReservations field

---

src/gatsby/src/templates/park.js

CMS-203
- Add sorting by camping type name

CMS-203: Add sorting by camping type name

---

src/gatsby/src/components/park/nearbyPark.js
src/gatsby/src/components/search/parkCard.js
src/gatsby/src/utils/helpers.js

CMS-267
- Update handleImgError function

CMS-267: Update handleImgError function

---

src/admin/src/components/composite/advisoryForm/AdvisoryForm.js
src/admin/src/validators/AdvisoryValidator.js

CMS-99
- Update error messages for advisory form

CMS-99: Update error messages for advisory form

---

src/gatsby/src/styles/global.scss

CMS-288
- Update table colour in the accordion

CMS-288: Update table colour in the accordion

---

src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/components/park/campingDetails.js
src/gatsby/src/components/park/parkActivity.js
src/gatsby/src/components/park/parkDates.js
src/gatsby/src/components/park/parkFacility.js

CMS-301
- Update state for accordion expand all
- Fix the issue that after manually opening all the accordions in a section, the link to "Expand all" link remains the same

CMS-301: Update state for accordion expand all

---

src/gatsby/src/components/park/parkHeader.js

CMS-26
- Update tldr wording for park gate

CMS-26: Update tldr wording for park gate

---

src/gatsby/src/components/park/parkDates.js

None
- Fix loading issue on golden ears park page - error: "$ is not a function"
- HTMLArea component seemed to cause the issue for some reason so replace it with another component

NOBUG: Fix loading issue on golden ears park page

---

src/gatsby/src/components/park/nearbyPark.js
src/gatsby/src/components/search/parkCard.js
src/gatsby/src/utils/helpers.js

CMS-267
This adds a bunch of debugging stuff to the console to try to find the cause of the broken images on the alpha-dev and alpha-test servers. 
1. It will print the original URL for all the thumbnails
2. It will print the image URL and the error message in `handleImgError`
We can revert this commit after we solve the issue!

CMS-267: Add console debugging for thumbnail images

---

src/gatsby/src/components/park/campingDetails.js

CMS-311
- Display expand all button if there's one camping accordion including reservations

CMS-311: Display expand all button if there's one camping accordion including reservations

---

src/gatsby/src/components/park/nearbyPark.js
src/gatsby/src/components/search/parkCard.js
src/gatsby/src/utils/helpers.js

CMS-267
This removes the changes I made for debugging in #1428
(Reverts 6b39d9e81b37a24e5fa913dcccdf0f5a89c20852)

CMS-267: Revert console debugging for thumbnail images

---

src/gatsby/src/components/park/advisoryDetails.js

CMS-311
- Change advisories accordion toggle status with advisoriesWithFormatting

CMS-311: Change advisories accordion toggle status with advisoriesWithFormatting

---

src/gatsby/src/components/park/campingDetails.js
src/gatsby/src/styles/cmsSnippets/parkInfoPage.scss
src/gatsby/src/styles/parks.scss

CMS-271
- Add expand/collapse feature using hr for park camping type description

CMS-271: Add expand/collapse feature using hr for park camping type description

---

src/gatsby/src/styles/global.scss

CMS-307
- Add max-width inside accordion

CMS-307: Add max-width inside accordion

---

src/gatsby/src/components/park/parkHeader.js

CMS-315
- Display minutes for park operation in tldr

CMS-315: Display minutes for park operation in tldr

---

src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/templates/park.js

CMS-311
- Fix advisories accordion expand issue

CMS-311: Fix advisories accordion expand issue

---

src/gatsby/src/styles/global.scss
src/gatsby/src/styles/parks.scss

CMS-350
- Update table style
- Remove arcgis CSS since we no longer have it on the Park page

CMS-350: Update table style

---

src/gatsby/src/components/park/campingDetails.js
src/gatsby/src/components/park/parkOverview.js
src/gatsby/src/styles/parks.scss

CMS-310
- Add gradient to expandable description (Hightlight section and Camping section)

CMS-310: Add gradient to expandable description

---

src/gatsby/src/components/pageContent/pageMenu.js
src/gatsby/src/templates/park.js
src/gatsby/src/templates/parkSubPage.js
src/gatsby/src/templates/staticContent1.js

CMS-361
- Fix table of contents bug on park page
- Delete parkDatesRef since it's integrated into the camping section
- Code refactor

CMS-361: Fix table of contents bug on park page

---

src/gatsby/src/components/park/reservationsRequired.js

CMS-362
- Update reservations required text

CMS-362: Update reservations required text

---

src/gatsby/src/components/megaMenu.js
src/gatsby/src/styles/megaMenu/megaMenu.scss

CMS-61
- Change mega menu item with window icon alignment

CMS-61: Change mega menu item with window icon alignment

---

src/gatsby/gatsby-node.js
src/gatsby/src/components/park/campingDetails.js
src/gatsby/src/components/park/parkDates.js
src/gatsby/src/components/park/parkFacility.js
src/gatsby/src/styles/parks.scss
src/gatsby/src/templates/park.js

CMS-279
CMS-370
- Add reservation buttons in camping/facilities section
- Move dates of operation from camping accordion

CMS-279: Add reservation buttons in camping section

---

src/gatsby/src/components/park/campingDetails.js
src/gatsby/src/components/park/parkOverview.js
src/gatsby/src/styles/parks.scss

CMS-310
- Hide show more button and gradient if hr is at the bottom
- If the height is 261-299 pixels then we don't show the link, but if the height is more than 300 pixels then we show the link 
- We only show 260 pixels of the content by default

CMS-310: Hide show more button if hr is at the bottom

---

src/gatsby/src/components/park/about.js
src/gatsby/src/styles/global.scss
src/gatsby/src/styles/parks.scss
src/gatsby/src/templates/park.js

CMS-354
- Add accordions to about section

CMS-354: Add accordions to about section

---

src/cms/src/api/fire-ban-prohibition/content-types/fire-ban-prohibition/schema.json
src/cms/src/api/fire-ban-prohibition/services/fire-ban-prohibition.js

CMS-253
- added a new rescindedDate field to fire bans 
- added logic to check the effectiveDate and rescindedDate when propagating firebans

CMS-252: Support scheduling of firebans

---

src/gatsby/src/components/park/about.js
src/gatsby/src/styles/parks.scss

CMS-354
- Not display conservation in accordion if the park type is ecological reserve

CMS-354: Not display conservation in accordion if the park is ecological reserve

---

src/gatsby/src/components/park/campingDetails.js
src/gatsby/src/components/park/parkDates.js

CMS-279
- Display book shelter button in cabins and huts accordion

CMS-279: Display book shelter button in cabins and huts accordion

---

src/gatsby/src/components/park/contact.js
src/gatsby/src/templates/park.js

CMS-260
- Display default contact even if there is no data in `protectedArea.parkContact`

CMS-260: Display default contact even if there is no data in protectedArea.parkContact

---

src/gatsby/src/components/park/parkHeader.js
src/gatsby/src/components/park/subArea.js
src/gatsby/src/styles/global.scss
src/gatsby/src/styles/parks.scss

CMS-392
CMS-389
- Adjust links in tldr
- Adjust subarea layout

CMS-392: Adjust links in tldr

---

src/gatsby/gatsby-node.js

CMS-293
- Fix an issue that adding parkOperation to site did not work

CMS-293: Fix an issue that adding parkOperation to site did not work

---

src/gatsby/src/components/park/parkDates.js

CMS-279
- Update condition for reservation deep link buttons

CMS-279: Update condition for reservation deep link buttons

---

src/gatsby/src/components/park/about.js

CMS-399
- Change the order of about section contents

CMS-399: Change the order of about section contents

---

src/gatsby/src/components/park/parkHeader.js
src/gatsby/src/components/park/subArea.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CMS-367
- Change the wording in tldr
- Fix the issue that "Limited services" was not displayed in the Winter season on the park page

CMS-367: Change the wording in tldr

---

src/gatsby/src/components/park/contact.js
src/gatsby/src/components/park/visitorGuidelines.js

CMS-404
- Fix gatsby build errors
https://github.com/bcgov/bcparks.ca/actions/runs/10779774158/job/29894027313 
https://github.com/bcgov/bcparks.ca/actions/runs/10731361814/job/29761327520 
https://github.com/bcgov/bcparks.ca/actions/runs/10730742172/job/29759685996 
https://github.com/bcgov/bcparks.ca/actions/runs/10779774158/job/29894027313

CMS-404: Fix gatsby build errors

---

src/gatsby/src/components/park/parkDates.js

CMS-279
- Update reservation button condition

CMS-279: Update reservation button condition

---

src/gatsby/src/components/park/contact.js

CMS-404
- Fix gatsby build error: https://github.com/bcgov/bcparks.ca/actions/runs/10837796561/job/30074557551

CMS-404: Fix gatsby build error

---

src/cms/src/api/guideline-type/content-types/guideline-type/schema.json

CMS-313
- Add garbage unavailable option to guideline-type

CMS-313: Add garbage unavailable option to guideline-type

---

src/cms/src/plugins/strapi-plugin-ckeditor/admin/src/components/Input/CKEditor/theme/common.js
src/gatsby/src/styles/global.scss

CMS-358
- Update rte blockquote style

CMS-358: Update rte blockquote style

---

src/cms/src/plugins/strapi-plugin-ckeditor/admin/src/components/Input/CKEditor/theme/common.js

CMS-384
- Update a link style inside the callout box in RTE

CMS-384: Update a link style inside callout box in rte

---

src/gatsby/src/components/emergencyAlert.js
src/gatsby/src/styles/alert.scss

CMS-303
- Add `aria-label="Close urgent alert"` to the button for screen readers
- Code refactor

CMS-303: Add aria label to alert

---

src/cms/src/api/protected-area/content-types/protected-area/schema.json
src/cms/src/api/site/content-types/site/schema.json
src/cms/src/api/trail-report/content-types/trail-report/schema.json

CMS-364
- Change trail report relation with protected area and site

CMS-364: Change trail report relation with protected area and site

---

src/gatsby/src/components/park/parkAccessStatus.js
src/gatsby/src/components/park/parkHeader.js

CMS-395
- Check park access status to display park operation dates
- Hide the access status text in TLDR if the park advisory access status is "Closed"

CMS-395: Check park access status to display park operation dates

---

src/gatsby/src/templates/staticContent1.js
src/gatsby/src/templates/staticLanding1.js

None
- Add seo fallback to static landing and content page

NOBUG: Add seo fallback to static landing and content page

---

src/gatsby/src/components/park/subArea.js

CMS-391
- Align all notes to dates information

CMS-391: Align all notes to dates information

---

src/gatsby/src/components/park/about.js

CMS-410
- Update capitalization of cultural heritage

CMS-410: Update capitalization of cultural heritage

---

src/gatsby/src/utils/advisoryHelper.js

CMS-413
- Update link in winter season limited access advisory

CMS-413: Update link in winter season limited access advisory

---

src/gatsby/src/components/park/parkAccessStatus.js
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

NOBUG: Fix errors

---

src/gatsby/src/styles/global.scss

CMS-376: Update h5 style

---

src/cms/src/api/search-indexing/controllers/search-indexing.js
src/scheduler/elasticsearch/transformers/park/main.js

CMS-421
- Add filter that removes draft state activities and facilities to park search api

CMS-421: Add filter that removes draft state activities and facilities to park search api

---

src/gatsby/src/utils/advisoryHelper.js

CMS-413
- Update winter season advisory wording

CMS-413: Update winter season advisory wording

---

src/gatsby/src/components/park/parkHeader.js

CMS-369
- Add openNote to tldr on park page

CMS-369: Add openNote to tldr on park page

---

.github/workflows/build-dev.yaml
.github/workflows/deploy-alpha-test.yaml
.github/workflows/deploy-prod.yaml
.github/workflows/deploy-test.yaml
.github/workflows/on-tag-push.yaml
.github/workflows/publish-gatsby.yaml

None
- Fix the OpenShift error: https://github.com/bcgov/bcparks.ca/actions/runs/11352007520/job/31573823097#step:13:20
- Ref: https://github.com/actions/runner-images/blob/ubuntu24/20241006.1/images/ubuntu/Ubuntu2404-Readme.md

NOBUG: Fix openshift error

---

src/gatsby/src/styles/pageContent/pageMenu.scss

CMS-366
- Fix the mobile menu missing borders on iPhone

CMS-366: Fix the mobile menu missing borders on iPhone

---

src/gatsby/src/components/advisories/advisoryCard.js
src/gatsby/src/components/advisories/advisoryFilter.js
src/gatsby/src/components/advisories/advisoryList.js
src/gatsby/src/components/advisories/advisoryPageNav.js
src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/pages/active-advisories.js
src/gatsby/src/styles/advisories/advisoryCard.scss
src/gatsby/src/styles/advisories/advisoryFilter.scss
src/gatsby/src/styles/advisories/advisoryLegend.scss
src/gatsby/src/styles/advisories/advisoryPageNav.scss
src/gatsby/src/styles/global.scss

CMS-373
CMS-374
CMS-403
- Update active advisory page UI
- Update advisory UI on park page
- Update area pills display

CMS-373: Update active advisory page UI

---

src/gatsby/src/components/park/parkHeader.js

CMS-297
- Update gateOpenTime and gateCloseTime condition in tldr

CMS-297: Update gateOpenTime and gateCloseTime condition in tldr

---

src/gatsby/src/components/park/parkDates.js

CMS-398
- Add subArea id to subArea accordion in the camping section

CMS-398: Add subArea id to subArea accordion in the camping section

---

src/gatsby/src/components/park/parkAccessStatus.js
src/gatsby/src/components/search/parkCard.js
src/gatsby/src/styles/search.scss

CMS-129
- Change park card layout
- Fix an error `setIsParkOpen is not a function.`

CMS-129: Change park card layout

---

src/cms/src/plugins/strapi-plugin-ckeditor/admin/src/components/Input/CKEditor/theme/additional.js
src/gatsby/src/styles/global.scss

CMS-417
- Update rte table styling

CMS-417: Update rte table styling

---

src/gatsby/src/components/park/campingDetails.js

CMS-387
- Add scroll to each show more/less camping button

CMS-387: Add scroll to each show more/less camping button

---

src/gatsby/src/components/advisories/advisoryFilter.js

CMS-377
- Display an event type in the select field based on the url

CMS-377: Display an event type in the select field based on the url

---

src/gatsby/src/components/park/parkDates.js

CMS-398
- Fix the issue that there is no subArea id when there is one accordion

CMS-398: Fix the issue that there is no subArea id when there is one accordion

---

src/cms/src/plugins/strapi-plugin-ckeditor/admin/src/components/Input/CKEditor/theme/common.js
src/gatsby/src/styles/global.scss

CMS-384
- Match the callout styling on frontend and strapi

CMS-384: Match the callout styling on frontend and strapi

---

src/gatsby/src/components/park/campingDetails.js
src/gatsby/src/components/park/parkOverview.js

CMS-441
- Update show more highlights button wording

CMS-441: Update show more highlights button wording

---

src/gatsby/gatsby-browser.js

CMS-363
- Update snowplow tracking

CMS-363: Update snowplow tracking

---

src/cms/src/api/park-operation-sub-area/content-types/park-operation-sub-area/schema.json
src/cms/src/api/park-operation/content-types/park-operation/schema.json

CMS-447
- Add inReservationSystem boolean field in ParkOperationSubArea and ParkOperation

CMS-447: Add inReservationSystem boolean field in ParkOperationSubArea and ParkOperation

---

src/gatsby/src/components/park/parkHeader.js
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CMS-445
- Display gate opens at dawn or closes at dusk

CMS-445: Display gate opens at dawn or closes at dusk

---

src/cms/src/api/park-photo/content-types/park-photo/schema.json
src/gatsby/gatsby-node.js
src/gatsby/src/components/park/parkPhotoGallery.js
src/gatsby/src/styles/parks.scss
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CMS-93
CMS-95
- Add photographer credits to photos on the Park page
- Add resourceSpaceId field to the ParkPhotos collection type

CMS-93: Add photographer credits to photos

---

src/cms/src/api/park-contact/content-types/park-contact/lifecycles.js
src/gatsby/src/templates/park.js

CMS-469
- Fix park contact undefined issue
- Reopened a PR and copied it over from https://github.com/bcgov/bcparks.ca/pull/1514 since I needed to change the main branch

CMS-469: Fix park contact undefined issue

---

src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CMS-461
- Fix incorrect advisory count displayed on Park Operating dates page
- The issue happened because we didn't get the advisories data

CMS-461: Fix incorrect advisory count displayed on Park Operating dates page

---

src/gatsby/src/components/search/parkCard.js
src/gatsby/src/styles/search.scss

CMS-129
- Update park card layout

CMS-129: Update park card layout

---

src/gatsby/src/components/park/parkHeader.js

CMS-445
- Update logic to display park gate open/close time

CMS-445: Update logic to display park gate open/close time

---

src/gatsby/src/components/park/parkPhotoGallery.js

CMS-93
- Add 'Photo by' to photo credit

CMS-93: Add 'Photo by' to photo credit

---

src/cms/src/api/park-contact/content-types/park-contact/lifecycles.js

CMS-472
- Update park contact lifecycle in Strapi

CMS-472: Update park contact lifecycle in Strapi

---

src/gatsby/src/components/advisories/advisoryCard.js
src/gatsby/src/components/advisories/advisoryFilter.js
src/gatsby/src/components/advisories/advisoryList.js
src/gatsby/src/pages/active-advisories.js
src/gatsby/src/styles/advisories/advisoryCard.scss
src/gatsby/src/styles/global.scss

CMS-373
CMS-403
- Fix spacing issue on the active advisories page
- Update park pill badge styling
- Update advisories sorting

CMS-373: Fix spacing issue on active advisories page

---

src/gatsby/src/components/park/contact.js

CMS-478
- Remove hyphens from the phone number link

CMS-478: Remove hyphens from the phone number link

---

src/gatsby/src/components/advisories/advisoryCard.js
src/gatsby/src/components/advisories/advisoryList.js
src/gatsby/src/styles/global.scss

CMS-374
- Display 'Starts' when an advisory doesn't have an end date
- Update the accordion spacing on the mobile

CMS-374: Display 'Starts' when an advisory doesn't have an end date

---

src/scheduler/email-alerts/templates/public-advisory.ejs

CMS-475
- Fix the issue with the park pill spacing

CMS-475: Fix the issue with the park pill spacing

---

src/gatsby/src/components/park/subArea.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CMS-450
- Update text on park operating dates page

CMS-450: Update text on park operating dates page

---

src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CMS-450
- Include 'page' in the link span on the park operating dates page

CMS-450: Include 'page' in the link span on park operating dates page

---

src/gatsby/src/components/advisories/advisoryFilter.js
src/gatsby/src/pages/active-advisories.js
src/gatsby/src/styles/search.scss

CMS-511
- Fix the issue with typeahead on the active advisories page
- Add clear buttons to both fields
- Update message when there are no results
- Clear typed text by hitting enter if there is no match

CMS-511: Fix the issue with typeahead on active advisories page

---

src/gatsby/src/templates/park.js

CMS-400
- Fix the issue when navigating page section directly from a url
- I'm not 100% sure if it'll fix it since I couldn't recreate it on my local 🤔 Just applied the change based on their doc: https://www.npmjs.com/package/react-use-scrollspy

CMS-400: Fix the issue when navigating page section directly from a url

---

src/gatsby/gatsby-node.js
src/gatsby/src/components/park/campingDetails.js
src/gatsby/src/components/park/parkFacility.js
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CMS-516
- Fix the issue that standard callout boxes are not showing
- Fix the graphQL queries - it was in nested fields
- Add callout to the camping section

CMS-516: Fix the issue that standard callout boxes are not showing

---

src/gatsby/src/pages/active-advisories.js

CMS-511
- Remove the search result count line since it's a dup
- No need `my-2` if there is no text

CMS-511: Remove the search result count line

---

src/gatsby/src/components/advisories/advisoryFilter.js

CMS-511
- Open dropdown when the advisory type field is focused

CMS-511: Open dropdown when the advisory type field is focused

---

src/gatsby/src/components/park/parkAccessStatus.js

CMS-461
- Hide the check advisory link if the park doesn't have an advisory

CMS-461: Hide the check advisory link if the park doesn't have an advisory

---

src/cms/src/api/event-type/content-types/event-type/schema.json
src/cms/src/api/legacy-redirect/content-types/legacy-redirect/schema.json
src/cms/src/api/park-operation/content-types/park-operation/schema.json
src/cms/src/api/protected-area/content-types/protected-area/schema.json
src/cms/src/api/protected-area/custom/protected-area-status.js
src/cms/src/api/public-advisory-audit/content-types/public-advisory-audit/schema.json
src/gatsby/gatsby-node.js
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CMS-44
CMS-45
CMS-46
CMS-48
CMS-49
- CMS-44: Remove publishedRevisionNumber from publicAdvisoryAudit
- CMS-45: Add note to legacyRedirect
- CMS-46: Add description to eventType
- CMS-48: Add reservationNote to parkOperation
- CMS-49: Remove smoking ban fields and references

CMS-55: Clean up strapi

---

src/gatsby/src/components/search/noSearchResults.js
src/gatsby/src/pages/about/management-plans/approved.js
src/gatsby/src/pages/find-a-park.js
src/gatsby/src/pages/find-a-park/a-z-list.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CMS-473
- Update no results messaging
- Add no results messaging to the dates page, A-Z list page, and the approved page

CMS-473: Add no results messaging

---

src/gatsby/src/styles/search.scss

CMS-473
- Update no results styling
- Fix that bullet points were missing in the No result message

CMS-473: Update no results styling

---

src/gatsby/src/styles/listPage.scss
src/gatsby/src/styles/search.scss

CMS-560
- Fix icons that show up enlarged when the  page loads
- Code clean up

CMS-560: Fix icons show up enlarged when page loads

---

src/gatsby/src/components/search/cityNameSearch.js
src/gatsby/src/components/search/parkNameSearch.js

CMS-515
- Update no park name/city name messaging
- Add a custom menu item to the park name search field to display the message

CMS-515: Update no park name/city name messaging

---

src/gatsby/src/components/advisories/advisoryCard.js
src/gatsby/src/styles/advisories/advisoryCard.scss
src/gatsby/src/styles/bootstrapTheme.scss

CMS-563
- Fix incorrect pill styles on active advisories page

CMS-563: Fix incorrect pill styles on active advisories page

---

src/cms/src/api/emergency-alert/content-types/emergency-alert/lifecycles.js

CMS-559
- Add time zone to emergency-alert time fields

CMS-559: Add time zone to emergency-alert time fields

---

src/gatsby/src/styles/pageContent/pageMenu.scss
src/gatsby/src/styles/search.scss

CMS-568
CMS-569
- CMS-568: Update navigation spacing on mobile
- CMS-569: Update container width on the find a park page

CMS-568: Update navigation spacing on mobile

---

src/gatsby/src/components/footer.js
src/gatsby/src/components/megaMenu.js
src/gatsby/src/components/park/about.js
src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/components/park/parkActivity.js
src/gatsby/src/components/park/parkDates.js
src/gatsby/src/components/park/parkFacility.js
src/gatsby/src/components/search/filter.js
src/gatsby/src/pages/find-a-park.js
src/gatsby/src/utils/snowplowHelper.js

CMS-546
- Add snowplow custom calls to track
- which filter is clicked on the Find a Park page
- which park name is selected
- which city name is selected
- which keyword is used to search parks
- which accordion is clicked on the Park page
- which megamenu link/footer link is clicked
- For testing: We can't really test it on the local and DEV, so we need to check it on Alpha-TEST when it's merged

CMS-546: Add snowplow custom calls

---

src/cms/src/api/park-operation-sub-area/content-types/park-operation-sub-area/schema.json
src/cms/src/api/park-operation/content-types/park-operation/schema.json
src/gatsby/gatsby-node.js
src/gatsby/src/components/park/parkHeader.js
src/gatsby/src/components/park/subArea.js
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CMS-602
- Update note fields to rte fields
- Add `reservationsNote` to `parkOperationSubArea`
- Update template files since the rte field returns nested data through GraphQL

CMS-602: Update note fields to rte fields

---

src/gatsby/src/components/search/mainSearch.js
src/gatsby/src/pages/find-a-park.js

CMS-546
- Add snowplow custom call to search fields on the home page
- Update snowplow custom call on the find a park page

CMS-546: Add snowplow custom call to search fields on the home page

---

src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CMS-601
- Display book camping button if hasReservations is true

CMS-601: Display book camping button if hasReservations is true

---

src/gatsby/src/components/park/subArea.js
src/gatsby/src/styles/parks.scss

CMS-602
- Fix the list bullet point issue in the note display

CMS-602: Fix list bullet point issue in note display

---

src/cms/src/api/park-operation-date/content-types/park-operation-date/schema.json
src/cms/src/api/site/content-types/site/schema.json
src/gatsby/gatsby-config.js
src/gatsby/gatsby-node.js
src/gatsby/src/templates/site.js

CMS-611
- Add parkOperationDates to site

CMS-611: Add parkOperationDates to site

---

src/gatsby/src/components/search/parkNameSearch.js
src/gatsby/src/pages/find-a-park.js
src/gatsby/src/styles/global.scss

CMS-552
CMS-605
- Fix the park search redirect issue
- Fix the search button style when it's clicked
- Fix the error message issue that is displayed when the page transitions from the Home page to the Find a Park page

CMS-605: Fix park search redirect issue

---

src/gatsby/src/components/advisories/advisoryDate.js
src/gatsby/src/styles/advisories/advisoryDate.scss

CMS-616
- Hide advisory date if 'No date' is selected

CMS-616: Hide advisory date if 'No date' is selected

---

src/gatsby/src/components/park/parkFacility.js

CMS-645
- Update 'Book picnic shelter' logic to only display in picnic shelter facility

CMS-645: Update 'Book picnic shelter' logic to only display in picnic shelter facility

---

src/gatsby/src/components/footer.js
src/gatsby/src/components/megaMenu.js
src/gatsby/src/components/park/about.js
src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/components/park/parkActivity.js
src/gatsby/src/components/park/parkDates.js
src/gatsby/src/components/park/parkFacility.js
src/gatsby/src/components/search/filter.js
src/gatsby/src/components/search/mainSearch.js
src/gatsby/src/pages/find-a-park.js
src/gatsby/src/utils/snowplowHelper.js

CMS-686
- Change `label` to null for `search` action
- Add `url` to snowplow event obj for `link_click` action
- Remove “… accordion“ from `label` for `accordion_open` and `accordion_close` actions
- Fire the snowplow event with accumulated search conditions
- Not to clear the conditions when filters are selected/deleted
- Use useState to accumulate the conditions
- Fix incorrect search result number

CMS-686: Update snowplow events

---

src/gatsby/src/pages/find-a-park.js

CMS-686
- Update snowplow event to track park name and city name when they get updated
- Change `finalResults` with `useState` to with `useMemo`

CMS-686: Update snowplow event to track park name and city name

---

src/cms/src/api/park-operation-sub-area/content-types/park-operation-sub-area/schema.json
src/cms/src/api/site/content-types/site/schema.json
src/gatsby/gatsby-config.js
src/gatsby/gatsby-node.js
src/gatsby/src/templates/site.js

CMS-667
- Add a relation with `site` to `park-operation-sub-area`
- TODO: Remove `orcsSiteNumber` from `park-operation-sub-area` after the data migration
- ^ Does this affect to DOOT the data model?

CMS-667: Add a relation with site to park-operation-sub-area

---

src/gatsby/src/components/park/advisoryDetails.js
src/gatsby/src/pages/active-advisories.js
src/gatsby/src/utils/advisoryHelper.js

CMS-672
- Update advisory sorting
- New sorting order
1.   listingRank:DES
2.   urgency.sequence:DESC
3.   accessStatus.precedence:ASC
4.   eventType.precedence:ASC
5.   Display date

CMS-672: Update advisory sorting

---

src/gatsby/src/components/park/parkHeader.js
src/gatsby/src/components/park/subArea.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
src/gatsby/src/styles/parks.scss
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js
src/gatsby/src/utils/parkDatesHelper.js
src/gatsby/src/utils/subAreaHelper.js

CMS-567
- Display the subarea gate time and the notes on the park page and the site page
- Remove the year prefix if there are no multiple year dates on the park page
- Change the subarea notes layout

CMS-567: Display subarea gate time and notes on park page

---

src/gatsby/src/utils/snowplowHelper.js

CMS-767
- Update snowplow track event filters
- Use lowercase for all filter names
- Rename "Things to do" to "activities" to align with the schema

CMS-767: Update snowplow track event filters

---

src/gatsby/src/components/search/mainSearch.js

CMS-755
- Navigate to the park page from the home page if the park is selected from the option
- It directly goes to the Golden Ears Park page if a user selects "Golden Ears Park" from the option
- It goes to the Find a park page if a user searches "Gold"

CMS-755: Navigate to park page from home page if park is selected

---

src/gatsby/src/components/pageContent/pageMenu.js
src/gatsby/src/styles/pageContent/pageMenu.scss

CMS-646
- Update table of contents
- Add menu header "On this page" on both desktop and mobile screen
- Code refactor

CMS-646: Update table of contents

---

src/gatsby/src/styles/pageContent/pageMenu.scss
src/gatsby/src/styles/staticContent1.scss

CMS-646
- Fix an issue that the links have underlines on the desktop view

CMS-646: Fix underline on table of contents

---

src/scheduler/email-alerts/templates/public-advisory.ejs

CMS-537
- Update advisory link in email
- Apparently, I forgot to remove `bcparks` here 😅: https://github.com/bcgov/bcparks.ca/pull/1296

CMS-537: Update advisory link in email

---

src/gatsby/src/components/search/parkCard.js
src/gatsby/src/styles/search.scss

CMS-765
- Add `line-height` to the see all link on the Find a park page

CMS-765: Add line height to see all link on find a park page

---

src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js
src/gatsby/src/utils/subAreaHelper.js

CMS-823
- Fix displaying facilities with isActive false
- Add filter with `isActive` and `isFacilityOpen`
- Update activities and camping filtering too

CMS-823: Fix displaying facilities with isActive false

---

src/gatsby/src/pages/find-a-park.js
src/gatsby/src/pages/plan-your-trip/park-operating-dates.js

CMS-834
- Add a loading bar to the park operating dates page because the page takes time to load, and there was no indicator to show it’s working on loading the data
- Change the wording "Searching..." to "Loading..."

CMS-834: Add a loading bar to park operating dates page

---

src/gatsby/src/components/park/parkOverview.js

CMS-34
- If there was no Show more/less toggle button, audio clip wasn't displayed
- If there was `<hr>` at the end of the description, the toggle button wasn't displayed
- If there is an audio clip, display the toggle button, since it takes most of the height of the Highlight section
- If there is `<hr>` at the end of the description, and there is an audio clip, the toggle button should be displayed

CMS-34: Fix audio clip display issue

---

src/gatsby/src/components/audioButton.js
src/gatsby/src/components/park/about.js
src/gatsby/src/components/park/parkHeader.js
src/gatsby/src/components/park/parkOverview.js
src/gatsby/src/templates/park.js
src/gatsby/src/templates/site.js

CMS-868
- Display only one audio clip (audio player) at a time
- If a user clicks the audio button A and then clicks the audio button B, the audio player B doesn't get displayed
- If the `activeAudio` state matches the audio id of the element, display the matched audio player

CMS-868: Display only one audio clip at a time

---

src/gatsby/src/pages/plan-your-trip/park-operating-dates.js
src/gatsby/src/utils/parkDatesHelper.js

CMS-871
- Add date format for winter rate
- Convert "YYYY: MM/DD – MM/DD" to "MM/DD, YYYY – MM/DD, YYYY"

CMS-871: Add date format for winter rate

---

src/gatsby/src/components/audioButton.js

CMS-886
- Add description to the audio button component
- Display description if the audio button is not in the TLDR section

CMS-886: Add description to audio button component

---

src/gatsby/src/components/park/about.js

CMS-868
- Previously, the same audio was used in the Heritage and the History of the About section
- Filter audio clips by the `displayLocation` and display in the matched location

CMS-868: Filter audio clips in about section

---

src/gatsby/src/components/park/subArea.js

CMS-882
- Rename "Winter note" to "Off-season note" in the Camping section on the Park page and the Site page

CMS-882: Rename winter note to off-season note

---

src/gatsby/src/components/audioButton.js

CMS-34
- Update the audio credit as its format is grammatically awkward and has a misplaced comma

CMS-34: Update audio credit

---

.github/workflows/build-dev.yaml

CMS-1009
- Fix the build error: https://github.com/bcgov/bcparks.ca/actions/runs/15930953399
- Remove build admin from GitHub action

CMS-1009: Remove build admin from github action

---

src/cms/src/api/park-date-type/content-types/park-date-type/schema.json
src/cms/src/api/park-date-type/controllers/park-date-type.js
src/cms/src/api/park-date-type/routes/park-date-type.js
src/cms/src/api/park-date-type/services/park-date-type.js
src/cms/src/api/park-date/content-types/park-date/schema.json
src/cms/src/api/park-date/controllers/park-date.js
src/cms/src/api/park-date/routes/park-date.js
src/cms/src/api/park-date/services/park-date.js
src/cms/src/api/protected-area/content-types/protected-area/schema.json

CMS-1038
- Create park-date and park-date-type collection
- TODO: Add "parkArea" and "parkFeature" relations to park-date after they are created

CMS-1038: Create park-date and park-date-type collection

---

src/cms/src/api/park-gate/content-types/park-gate/schema.json
src/cms/src/api/park-gate/controllers/park-gate.js
src/cms/src/api/park-gate/routes/park-gate.js
src/cms/src/api/park-gate/services/park-gate.js

CMS-1214
- Create park-gate collection
- TODO: Add "parkArea" and "parkFeature" relations to park-date after they are created

CMS-1214: Create park-gate collection

---

src/cms/src/api/park-area/content-types/park-area/schema.json
src/cms/src/api/park-date/content-types/park-date/schema.json
src/cms/src/api/park-feature-type/content-types/park-feature-type/schema.json
src/cms/src/api/park-feature-type/controllers/park-feature-type.js
src/cms/src/api/park-feature-type/routes/park-feature-type.js
src/cms/src/api/park-feature-type/services/park-feature-type.js
src/cms/src/api/park-feature/content-types/park-feature/schema.json
src/cms/src/api/park-feature/controllers/park-feature.js
src/cms/src/api/park-feature/routes/park-feature.js
src/cms/src/api/park-feature/services/park-feature.js
src/cms/src/api/park-gate/content-types/park-gate/schema.json

CMS-1154
- Create park-feature and park-feature-type collection

CMS-1154: Create park-feature and park-feature-type collection

---

src/cms/database/migrations/2025.09.05T00.00.23.park-area-type.js
src/cms/database/migrations/2025.09.05T00.00.24.park-area.js
src/cms/database/migrations/2025.09.25T00.00.28.park-area-feature-rename.js
src/cms/src/api/park-area-type/content-types/park-area-type/schema.json
src/cms/src/api/park-area/content-types/park-area/schema.json

CMS-836
Minor updates to Strapi collections based on QA feedback

CMS-836: Fixes to park-area and park-area-type from QA

---

src/cms/database/migrations/2025.09.16T00.00.27.park-feature.js
src/cms/database/migrations/2025.09.26T00.00.29.park-areas-group-sites-rename.js
src/cms/src/api/park-feature/content-types/park-feature/schema.json

CMS-1154
Fix incorrectly named `groupSites` field

CMS-1154: Fix incorrectly named groupsSites field

---

src/gatsby/src/styles/home.scss
src/gatsby/src/styles/pageContent/linkCard.scss

CMS-1256
- Previously, the card height was fixed so that the content overflowed if it was long
- Adjust the card height based on content, especially on the mobile screen

CMS-1256: Update card component UI
